--TABELLA TEMPORANEA PER PERMETTERE
--L'ESECUZIONE DI ALCUNE PROCEDURE

CREATE GLOBAL TEMPORARY TABLE GIORNI_TEMP(
    DATA_GIORNO DATE,

    --PK
    CONSTRAINT PK_GIORNI_TEMP
        PRIMARY KEY(DATA_GIORNO)
)
ON COMMIT DELETE ROWS;
