--PERMETTE DI CONTROLLARE SE VI SONO
--STATI CICLI PRODUTTIVI CHE HANNO PRODOTTO MALE
CREATE VIEW VERIFICA_PRODUZIONE_AGRICOLA
AS 

SELECT 
    PA.DATA_PRODUZIONE_AGRICOLA,
    PA.DATA_INIZIO_CICLO_COLTIVAZIONE,
    PA.CODICE_CELLA_IDR,
    PA.NOME_STRUTTURA,
    PA.NOME_PRODOTTO,
    PA.QUANTITA AS QUANTITA_EFFETTIVA_PRODOTTA,
    TCTP.QUANTITA_STIMATE_PER_UNITA_SEMI*(
        (NVL(CCSM.QUANTITA,0)+NVL(CCPA.QUANTITA,0))
    ) AS QUANTITA_STIMATA,

    PA.QUANTITA-TCTP.QUANTITA_STIMATE_PER_UNITA_SEMI*(
        (NVL(CCSM.QUANTITA,0)+NVL(CCPA.QUANTITA,0))
    ) AS DIFFERENZA

FROM PRODUZIONE_AGRICOLA PA 
JOIN CICLO_COLTIVAZIONE CC 
ON CC.CODICE_CELLA_IDR=PA.CODICE_CELLA_IDR
AND CC.NOME_STRUTTURA=PA.NOME_STRUTTURA
AND CC.DATA_INIZIO=PA.DATA_INIZIO_CICLO_COLTIVAZIONE

JOIN TIPO_COLTURA_TIPO_PRODOTTO TCTP 
ON TCTP.NOME_PRODOTTO=PA.NOME_PRODOTTO
AND TCTP.NOME_TIPO_COLTURA=CC.NOME_TIPO_COLTURA

LEFT JOIN CICLO_COLT_UTILIZZA_SEMI_MISSIONE CCSM 
ON CCSM.DATA_INIZIO=CC.DATA_INIZIO
AND CCSM.CODICE_CELLA_IDR=CC.CODICE_CELLA_IDR
AND CCSM.NOME_STRUTTURA=CC.NOME_STRUTTURA

LEFT JOIN CICLO_COLT_UTILIZZA_PRODUZIONE_AGRICOLA CCPA
ON CCPA.DATA_INIZIO=CC.DATA_INIZIO
AND CCPA.CODICE_CELLA_IDR=CC.CODICE_CELLA_IDR
AND CCPA.NOME_STRUTTURA=CC.NOME_STRUTTURA

WHERE PA.QUANTITA-TCTP.QUANTITA_STIMATE_PER_UNITA_SEMI*(
        (NVL(CCSM.QUANTITA,0)+NVL(CCPA.QUANTITA,0))
    )<> 0
