--PERMETTE DI CONTROLLARE SE VI SONO
--STATI CICLI PRODUTTIVI CHE HANNO PRODOTTO MALE
CREATE VIEW PRODUZIONE_AGRICOLA_TOTALE 
AS

SELECT 
    PA.NOME_PRODOTTO,
    SUM(PA.QUANTITA) AS QUANTITA_PRODOTTA

FROM PRODUZIONE_AGRICOLA PA 
JOIN CICLO_COLTIVAZIONE CC 
ON CC.CODICE_CELLA_IDR=PA.CODICE_CELLA_IDR
AND CC.NOME_STRUTTURA=PA.NOME_STRUTTURA
AND CC.DATA_INIZIO=PA.DATA_INIZIO_CICLO_COLTIVAZIONE

JOIN TIPO_COLTURA_TIPO_PRODOTTO TCTP 
ON TCTP.NOME_PRODOTTO=PA.NOME_PRODOTTO
AND TCTP.NOME_TIPO_COLTURA=CC.NOME_TIPO_COLTURA

LEFT JOIN (
    SELECT 
        DATA_INIZIO,
        CODICE_CELLA_IDR,
        NOME_STRUTTURA,
        SUM(QUANTITA) AS QUANTITA
    FROM (
        SELECT 
            DATA_INIZIO,
            CODICE_CELLA_IDR,
            NOME_STRUTTURA,
            QUANTITA
        FROM CICLO_COLT_UTILIZZA_SEMI_MISSIONE

        UNION ALL

        SELECT 
            DATA_INIZIO,
            CODICE_CELLA_IDR,
            NOME_STRUTTURA,
            QUANTITA
        FROM CICLO_COLT_UTILIZZA_PRODUZIONE_AGRICOLA
    )
    GROUP BY DATA_INIZIO, CODICE_CELLA_IDR, NOME_STRUTTURA
) SEMI
ON SEMI.DATA_INIZIO=CC.DATA_INIZIO
AND SEMI.CODICE_CELLA_IDR=CC.CODICE_CELLA_IDR
AND SEMI.NOME_STRUTTURA=CC.NOME_STRUTTURA

GROUP BY PA.NOME_PRODOTTO
