CREATE VIEW SEMI_MISSIONE_DISPONIBILI
AS

SELECT SM2.NOME_SEMI, SM2.DATA_ARRIVO_SEMI, (SM2.QUANTITA_SEMI-SEMI_UTILIZZATI) AS SEMI_DISPONIBILI
FROM SEMI_MISSIONE SM2
JOIN SEMI_MISSISONE_UTILIZZATI USATI
ON USATI.NOME_SEMI=SM2.NOME_SEMI
AND USATI.DATA_ARRIVO_SEMI = SM2.DATA_ARRIVO_SEMI

GROUP BY SM2.NOME_SEMI,  SM2.DATA_ARRIVO_SEMI, SEMI_UTILIZZATI, SM2.QUANTITA_SEMI
;