CREATE OR REPLACE VIEW SEMI_PRODUZIONE_AGRICOLA_UTILIZZATI
AS

SELECT 
    NOME_PRODOTTO AS NOME_SEMI, 
    SUM(QUANTITA) AS SEMI_UTILIZZATI,
    CODICE_CELLA_IDR_PROD_AGR AS CODICE_CELLA_IDR,
    NOME_STRUTTURA_PROD_AGR AS NOME_STRUTTURA,
    DATA_INIZIO_CICLO_COLTIVAZIONE,
    DATA_PRODUZIONE_AGRICOLA

    
FROM CICLO_COLT_UTILIZZA_PRODUZIONE_AGRICOLA CC
GROUP BY 
    NOME_PRODOTTO,
    CODICE_CELLA_IDR_PROD_AGR,
    NOME_STRUTTURA_PROD_AGR,
    DATA_INIZIO_CICLO_COLTIVAZIONE,
    DATA_PRODUZIONE_AGRICOLA
;