CREATE VIEW SEMI_PRODUZIONE_AGRICOLA_DISPONIBILI
AS

SELECT 
    PA.NOME_PRODOTTO AS NOME_SEMI, 
    (PA.QUANTITA-NVL(UTI.SEMI_UTILIZZATI, 0)) AS SEMI_DISPONIBILI, 
    PA.DATA_PRODUZIONE_AGRICOLA, 
    PA.DATA_INIZIO_CICLO_COLTIVAZIONE, 
    PA.CODICE_CELLA_IDR, 
    PA.NOME_STRUTTURA

FROM PRODUZIONE_AGRICOLA PA 
JOIN TIPO_COLTURA TC 
ON PA.NOME_PRODOTTO=TC.NOME_SEMI --IN QUESTO MODO ESCLUDIAMO I PRODOTTI NON SEMI

LEFT JOIN SEMI_PRODUZIONE_AGRICOLA_UTILIZZATI  UTI 
ON UTI.NOME_SEMI=PA.NOME_PRODOTTO
AND UTI.DATA_PRODUZIONE_AGRICOLA=PA.DATA_PRODUZIONE_AGRICOLA
AND UTI.DATA_INIZIO_CICLO_COLTIVAZIONE=PA.DATA_INIZIO_CICLO_COLTIVAZIONE
AND UTI.CODICE_CELLA_IDR=PA.CODICE_CELLA_IDR
AND UTI.NOME_STRUTTURA=PA.NOME_STRUTTURA
;
