CREATE VIEW SEMI_DISPONIBILI 
AS

SELECT 
    NOME_SEMI,
    SUM(SEMI_DISPONIBILI) AS SEMI_DISPONIBILI
FROM (
    SELECT 
        NOME_SEMI,
        SUM(SEMI_DISPONIBILI) AS SEMI_DISPONIBILI
    FROM SEMI_PRODUZIONE_AGRICOLA_DISPONIBILI
    GROUP BY NOME_SEMI

    UNION ALL

    SELECT 
        NOME_SEMI,
        SUM(SEMI_DISPONIBILI) AS SEMI_DISPONIBILI
    FROM SEMI_MISSIONE_DISPONIBILI
    GROUP BY NOME_SEMI
)
GROUP BY NOME_SEMI
