CREATE VIEW VERIFICA_PRODUZIONE_ANIMALE
AS

SELECT 
    PA.DATA_PRODUZIONE,
    PA.NUMERO_BLOCCO,
    PA.NOME_STRUTTURA,
    PA.NOME_PRODOTTO,
    PA.QUANTITA AS QUANTITA_EFFETTIVA_PRODOTTA,
    NVL(SUM(PDS.QUANTITA_STIMATA_GIORNALIERA), 0) AS QUANTITA_STIMATA,
    PA.QUANTITA - NVL(SUM(PDS.QUANTITA_STIMATA_GIORNALIERA), 0) AS DIFFERENZA

FROM PRODUZIONE_ANIMALE PA

JOIN ANIMALE_ALLOCATO_BLOCCO AAB
ON AAB.NUMERO_BLOCCO=PA.NUMERO_BLOCCO
AND AAB.NOME_STRUTTURA=PA.NOME_STRUTTURA
AND AAB.DATA_ALLOCAZIONE <= PA.DATA_PRODUZIONE
AND (
    AAB.DATA_DEALLOCAZIONE IS NULL
    OR AAB.DATA_DEALLOCAZIONE > PA.DATA_PRODUZIONE
)

JOIN ANIMALE A
ON A.ETICHETTA=AAB.ETICHETTA_ANIMALE

JOIN STADIO_CRESCITA SC
ON SC.NOME_TIPO_ANIMALE=A.NOME_TIPO_ANIMALE
AND SC.ETA_MINIMA_MESI=(
    SELECT MAX(SC2.ETA_MINIMA_MESI)
    FROM STADIO_CRESCITA SC2
    WHERE SC2.NOME_TIPO_ANIMALE=A.NOME_TIPO_ANIMALE
    AND SC2.ETA_MINIMA_MESI<= 
        ((EXTRACT(YEAR FROM PA.DATA_PRODUZIONE)-A.ANNO_NASCITA)*12)
        +(EXTRACT(MONTH FROM PA.DATA_PRODUZIONE)-A.MESE_NASCITA)
)

LEFT JOIN PRODOTTO_DA_STADIO_CRESCITA PDS
ON PDS.NOME_PRODOTTO=PA.NOME_PRODOTTO
AND PDS.NOME_STADIO_CRESCITA=SC.NOME_STADIO_CRESCITA
AND PDS.NOME_TIPO_ANIMALE=SC.NOME_TIPO_ANIMALE

GROUP BY 
    PA.DATA_PRODUZIONE,
    PA.NUMERO_BLOCCO,
    PA.NOME_STRUTTURA,
    PA.NOME_PRODOTTO,
    PA.QUANTITA
HAVING (PA.QUANTITA - NVL(SUM(PDS.QUANTITA_STIMATA_GIORNALIERA), 0))<> 0