CREATE VIEW CONSUMO_CICLI_COLTIVAZIONE
AS

SELECT 
    MC.NOME_MODALITA_COLTIVAZIONE,
    MC.NOME_PRODOTTO,
    SUM(MC.ACQUA_ORA*(24)*(NVL((CC.DATA_FINE_EFFETTIVA - CC.DATA_INIZIO),TC.DURATA_CICLO_COLTURA_GIORNI))) AS QUANTITA_ACQUA,
    SUM(MC.QUANTITA_SOLUZIONE_ORA *(24)*(NVL((CC.DATA_FINE_EFFETTIVA - CC.DATA_INIZIO),TC.DURATA_CICLO_COLTURA_GIORNI))) AS QUANTITA_SOLUZIONE
FROM CICLO_COLTIVAZIONE CC

JOIN MODALITA_COLTIVAZIONE MC
ON MC.NOME_MODALITA_COLTIVAZIONE=CC.NOME_MOD_COLTIVAZIONE

JOIN TIPO_COLTURA TC 
ON TC.NOME_TIPO_COLTURA=CC.NOME_TIPO_COLTURA

GROUP BY MC.NOME_MODALITA_COLTIVAZIONE, MC.NOME_PRODOTTO;