CREATE OR REPLACE PACKAGE SIMULATORE_ANIMALE AS
    PROCEDURE RUN_SIMULAZIONE(
        P_DATA_FINE IN DATE DEFAULT TRUNC(SYSDATE)
    );

    PROCEDURE SIMULA_GIORNO(
        P_DATA IN DATE
    );

    PROCEDURE SIMULA_BLOCCO(
        P_NUMERO_BLOCCO IN BLOCCO_ANIMALE.NUMERO_BLOCCO%TYPE,
        P_NOME_STRUTTURA IN BLOCCO_ANIMALE.NOME_STRUTTURA%TYPE,
        P_DATA IN DATE
    );

    PROCEDURE SIMULA_ANIMALE(
        P_ETICHETTA_ANIMALE IN ANIMALE.ETICHETTA%TYPE,
        P_NUMERO_BLOCCO IN BLOCCO_ANIMALE.NUMERO_BLOCCO%TYPE,
        P_NOME_STRUTTURA IN BLOCCO_ANIMALE.NOME_STRUTTURA%TYPE,
        P_DATA IN DATE
    );
END SIMULATORE_ANIMALE;
/

CREATE OR REPLACE PACKAGE BODY SIMULATORE_ANIMALE AS
    SUBTYPE T_NOME IS VARCHAR(60);

    FUNCTION RANDOM_NUMBER(
        P_MIN IN NUMBER,
        P_MAX IN NUMBER
    ) RETURN NUMBER IS
    BEGIN
        RETURN DBMS_RANDOM.VALUE(P_MIN, P_MAX);
    END RANDOM_NUMBER;

    FUNCTION RANDOM_TRIANGULAR(
        P_MIN IN NUMBER,
        P_MAX IN NUMBER,
        P_MODE IN NUMBER
    ) RETURN NUMBER IS
        V_U NUMBER := DBMS_RANDOM.VALUE(0, 1);
        V_C NUMBER := (P_MODE - P_MIN) / (P_MAX - P_MIN);
    BEGIN
        IF V_U < V_C THEN
            RETURN P_MIN + SQRT(V_U * (P_MAX - P_MIN) * (P_MODE - P_MIN));
        END IF;

        RETURN P_MAX - SQRT((1 - V_U) * (P_MAX - P_MIN) * (P_MAX - P_MODE));
    END RANDOM_TRIANGULAR;

    FUNCTION GET_SIM_START_DAY RETURN DATE IS
        V_MIN_ALLOCAZIONE DATE;
    BEGIN
        SELECT MIN(DATA_ALLOCAZIONE)
        INTO V_MIN_ALLOCAZIONE
        FROM ANIMALE_ALLOCATO_BLOCCO;

        RETURN V_MIN_ALLOCAZIONE;
    END GET_SIM_START_DAY;

    FUNCTION GET_ETA_MESI(
        P_MESE_NASCITA IN ANIMALE.MESE_NASCITA%TYPE,
        P_ANNO_NASCITA IN ANIMALE.ANNO_NASCITA%TYPE,
        P_DATA IN DATE
    ) RETURN NUMBER IS
    BEGIN
        RETURN GREATEST(
            0,
            (EXTRACT(YEAR FROM P_DATA) - P_ANNO_NASCITA) * 12 +
            (EXTRACT(MONTH FROM P_DATA) - P_MESE_NASCITA)
        );
    END GET_ETA_MESI;

    FUNCTION GET_STADIO_CRESCITA(
        P_NOME_TIPO_ANIMALE IN ANIMALE.NOME_TIPO_ANIMALE%TYPE,
        P_ETA_MESI IN NUMBER
    ) RETURN T_NOME IS
        V_NOME_STADIO T_NOME;
    BEGIN
        SELECT NOME_STADIO_CRESCITA
        INTO V_NOME_STADIO
        FROM (
            SELECT SC.NOME_STADIO_CRESCITA
            FROM STADIO_CRESCITA SC
            WHERE SC.NOME_TIPO_ANIMALE = P_NOME_TIPO_ANIMALE
            AND SC.ETA_MINIMA_MESI <= P_ETA_MESI
            ORDER BY SC.ETA_MINIMA_MESI DESC
        )
        WHERE ROWNUM = 1;

        RETURN V_NOME_STADIO;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN NULL;
    END GET_STADIO_CRESCITA;

    FUNCTION GET_HEALTH_FACTOR(
        P_ETICHETTA_ANIMALE IN ANIMALE.ETICHETTA%TYPE,
        P_DATA IN DATE
    ) RETURN NUMBER IS
        V_STATO_SALUTE VISITA_VETERINARIA.STATO_SALUTE%TYPE;
    BEGIN
        SELECT STATO_SALUTE
        INTO V_STATO_SALUTE
        FROM (
            SELECT VV.STATO_SALUTE
            FROM VISITA_VETERINARIA VV
            WHERE VV.ETICHETTA_ANIMALE = P_ETICHETTA_ANIMALE
            AND VV.DATA_VISITA <= TRUNC(P_DATA)
            ORDER BY VV.DATA_VISITA DESC
        )
        WHERE ROWNUM = 1;

        IF V_STATO_SALUTE = 'CRITICO' THEN
            RETURN 0.25;
        ELSIF V_STATO_SALUTE = 'DISCRETO' THEN
            RETURN 0.75;
        END IF;

        RETURN 1;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN 1;
    END GET_HEALTH_FACTOR;

    FUNCTION HAS_ACTIVE_PRESCRIPTION(
        P_ETICHETTA_ANIMALE IN ANIMALE.ETICHETTA%TYPE,
        P_DATA IN DATE
    ) RETURN BOOLEAN IS
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO V_COUNT
        FROM PRESCRIZIONE_ANIMALE PA
        WHERE PA.ETICHETTA_ANIMALE = P_ETICHETTA_ANIMALE
        AND TRUNC(P_DATA) BETWEEN PA.DATA_VISITA AND PA.DATA_VISITA + PA.DURATA_GIORNI - 1;

        RETURN V_COUNT > 0;
    END HAS_ACTIVE_PRESCRIPTION;

    FUNCTION GET_PRESCRIPTION_FACTOR(
        P_ETICHETTA_ANIMALE IN ANIMALE.ETICHETTA%TYPE,
        P_DATA IN DATE
    ) RETURN NUMBER IS
    BEGIN
        IF HAS_ACTIVE_PRESCRIPTION(P_ETICHETTA_ANIMALE, P_DATA) THEN
            RETURN 0.6;
        END IF;

        RETURN 1;
    END GET_PRESCRIPTION_FACTOR;

    PROCEDURE ADD_PRODUZIONE_ANIMALE(
        P_DATA_PRODUZIONE IN PRODUZIONE_ANIMALE.DATA_PRODUZIONE%TYPE,
        P_NUMERO_BLOCCO IN PRODUZIONE_ANIMALE.NUMERO_BLOCCO%TYPE,
        P_NOME_STRUTTURA IN PRODUZIONE_ANIMALE.NOME_STRUTTURA%TYPE,
        P_NOME_PRODOTTO IN PRODUZIONE_ANIMALE.NOME_PRODOTTO%TYPE,
        P_QUANTITA IN PRODUZIONE_ANIMALE.QUANTITA%TYPE
    ) IS
    BEGIN
        MERGE INTO PRODUZIONE_ANIMALE PA
        USING (
            SELECT
                TRUNC(P_DATA_PRODUZIONE) AS DATA_PRODUZIONE,
                P_NUMERO_BLOCCO AS NUMERO_BLOCCO,
                P_NOME_STRUTTURA AS NOME_STRUTTURA,
                P_NOME_PRODOTTO AS NOME_PRODOTTO,
                ROUND(P_QUANTITA, 2) AS QUANTITA
            FROM DUAL
        ) SRC
        ON (
            PA.DATA_PRODUZIONE = SRC.DATA_PRODUZIONE
            AND PA.NUMERO_BLOCCO = SRC.NUMERO_BLOCCO
            AND PA.NOME_STRUTTURA = SRC.NOME_STRUTTURA
            AND PA.NOME_PRODOTTO = SRC.NOME_PRODOTTO
        )
        WHEN MATCHED THEN
            UPDATE SET PA.QUANTITA = PA.QUANTITA + SRC.QUANTITA
        WHEN NOT MATCHED THEN
            INSERT (
                DATA_PRODUZIONE,
                NUMERO_BLOCCO,
                NOME_STRUTTURA,
                NOME_PRODOTTO,
                QUANTITA
            ) VALUES (
                SRC.DATA_PRODUZIONE,
                SRC.NUMERO_BLOCCO,
                SRC.NOME_STRUTTURA,
                SRC.NOME_PRODOTTO,
                SRC.QUANTITA
            );
    END ADD_PRODUZIONE_ANIMALE;

    PROCEDURE SIMULA_ANIMALE(
        P_ETICHETTA_ANIMALE IN ANIMALE.ETICHETTA%TYPE,
        P_NUMERO_BLOCCO IN BLOCCO_ANIMALE.NUMERO_BLOCCO%TYPE,
        P_NOME_STRUTTURA IN BLOCCO_ANIMALE.NOME_STRUTTURA%TYPE,
        P_DATA IN DATE
    ) IS
        V_NOME_TIPO_ANIMALE ANIMALE.NOME_TIPO_ANIMALE%TYPE;
        V_SESSO ANIMALE.SESSO%TYPE;
        V_MESE_NASCITA ANIMALE.MESE_NASCITA%TYPE;
        V_ANNO_NASCITA ANIMALE.ANNO_NASCITA%TYPE;
        V_ETA_MESI NUMBER;
        V_NOME_STADIO T_NOME;
        V_HEALTH_FACTOR NUMBER;
        V_PRESCRIPTION_FACTOR NUMBER;
        V_QUANTITA NUMBER;
    BEGIN
        SELECT
            A.NOME_TIPO_ANIMALE,
            A.SESSO,
            A.MESE_NASCITA,
            A.ANNO_NASCITA
        INTO
            V_NOME_TIPO_ANIMALE,
            V_SESSO,
            V_MESE_NASCITA,
            V_ANNO_NASCITA
        FROM ANIMALE A
        WHERE A.ETICHETTA = P_ETICHETTA_ANIMALE;

        V_ETA_MESI := GET_ETA_MESI(V_MESE_NASCITA, V_ANNO_NASCITA, TRUNC(P_DATA));
        V_NOME_STADIO := GET_STADIO_CRESCITA(V_NOME_TIPO_ANIMALE, V_ETA_MESI);

        IF V_NOME_STADIO IS NULL THEN
            RETURN;
        END IF;

        V_HEALTH_FACTOR := GET_HEALTH_FACTOR(P_ETICHETTA_ANIMALE, P_DATA);
        V_PRESCRIPTION_FACTOR := GET_PRESCRIPTION_FACTOR(P_ETICHETTA_ANIMALE, P_DATA);

        FOR PROD IN (
            SELECT
                PDSC.NOME_PRODOTTO,
                PDSC.QUANTITA_STIMATA_GIORNALIERA
            FROM PRODOTTO_DA_STADIO_CRESCITA PDSC
            WHERE PDSC.NOME_TIPO_ANIMALE = V_NOME_TIPO_ANIMALE
            AND PDSC.NOME_STADIO_CRESCITA = V_NOME_STADIO
        ) LOOP
            IF NOT (
                (PROD.NOME_PRODOTTO LIKE 'Latte%' AND V_SESSO != 'F')
                OR (PROD.NOME_PRODOTTO LIKE 'Uova%' AND V_SESSO != 'F')
            ) THEN
                V_QUANTITA :=
                    PROD.QUANTITA_STIMATA_GIORNALIERA *
                    V_HEALTH_FACTOR *
                    V_PRESCRIPTION_FACTOR *
                    RANDOM_TRIANGULAR(0.75, 1.25, 1.0);

                IF V_QUANTITA > 0 THEN
                    ADD_PRODUZIONE_ANIMALE(
                        TRUNC(P_DATA),
                        P_NUMERO_BLOCCO,
                        P_NOME_STRUTTURA,
                        PROD.NOME_PRODOTTO,
                        V_QUANTITA
                    );
                END IF;
            END IF;
        END LOOP;
    END SIMULA_ANIMALE;

    PROCEDURE SIMULA_BLOCCO(
        P_NUMERO_BLOCCO IN BLOCCO_ANIMALE.NUMERO_BLOCCO%TYPE,
        P_NOME_STRUTTURA IN BLOCCO_ANIMALE.NOME_STRUTTURA%TYPE,
        P_DATA IN DATE
    ) IS
        V_COUNT_ANIMALI NUMBER := 0;
    BEGIN
        FOR ANIM IN (
            SELECT AAB.ETICHETTA_ANIMALE
            FROM ANIMALE_ALLOCATO_BLOCCO AAB
            WHERE AAB.NUMERO_BLOCCO = P_NUMERO_BLOCCO
            AND AAB.NOME_STRUTTURA = P_NOME_STRUTTURA
            AND AAB.DATA_ALLOCAZIONE <= TRUNC(P_DATA)
            AND (AAB.DATA_DEALLOCAZIONE IS NULL OR AAB.DATA_DEALLOCAZIONE > TRUNC(P_DATA))
        ) LOOP
            V_COUNT_ANIMALI := V_COUNT_ANIMALI + 1;
            SIMULA_ANIMALE(
                ANIM.ETICHETTA_ANIMALE,
                P_NUMERO_BLOCCO,
                P_NOME_STRUTTURA,
                TRUNC(P_DATA)
            );
        END LOOP;

        IF V_COUNT_ANIMALI > 0 THEN
            DBMS_OUTPUT.PUT_LINE(
                'Block ' || P_NOME_STRUTTURA || ' ' || P_NUMERO_BLOCCO ||
                ': simulated ' || V_COUNT_ANIMALI || ' animals'
            );
        END IF;
    END SIMULA_BLOCCO;

    PROCEDURE SIMULA_GIORNO(
        P_DATA IN DATE
    ) IS
    BEGIN
        FOR BLOCCO IN (
            SELECT NUMERO_BLOCCO, NOME_STRUTTURA
            FROM BLOCCO_ANIMALE
            WHERE DATA_MONTAGGIO <= TRUNC(P_DATA)
            AND (DATA_SMONTAGGIO IS NULL OR DATA_SMONTAGGIO > TRUNC(P_DATA))
        ) LOOP
            SIMULA_BLOCCO(
                BLOCCO.NUMERO_BLOCCO,
                BLOCCO.NOME_STRUTTURA,
                TRUNC(P_DATA)
            );
        END LOOP;
    END SIMULA_GIORNO;

    PROCEDURE RUN_SIMULAZIONE(
        P_DATA_FINE IN DATE DEFAULT TRUNC(SYSDATE)
    ) IS
        V_CURRENT_DAY DATE := GET_SIM_START_DAY;
    BEGIN
        IF V_CURRENT_DAY IS NULL THEN
            DBMS_OUTPUT.PUT_LINE('No animal simulation start day found');
            RETURN;
        END IF;

        WHILE V_CURRENT_DAY < TRUNC(P_DATA_FINE) LOOP
            SIMULA_GIORNO(V_CURRENT_DAY);
            V_CURRENT_DAY := V_CURRENT_DAY + 1;
        END LOOP;

        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE;
    END RUN_SIMULAZIONE;
END SIMULATORE_ANIMALE;
/
