CREATE OR REPLACE PACKAGE SIMULATORE AS
    PROCEDURE RUN_SIMULAZIONE(
        P_DATA_FINE IN DATE DEFAULT TRUNC(SYSDATE)
    );

    PROCEDURE SIMULA_GIORNO(
        P_DATA IN DATE
    );

    PROCEDURE SIMULA_CELLA(
        P_CODICE_CELLA_IDR IN CELLA_IDROPONICA.CODICE_CELLA_IDR%TYPE,
        P_NOME_STRUTTURA IN CELLA_IDROPONICA.NOME_STRUTTURA%TYPE,
        P_DATA IN DATE
    );

    PROCEDURE START_CICLO_COLTIVAZIONE(
        P_CODICE_CELLA_IDR IN CELLA_IDROPONICA.CODICE_CELLA_IDR%TYPE,
        P_NOME_STRUTTURA IN CELLA_IDROPONICA.NOME_STRUTTURA%TYPE,
        P_DATA IN DATE
    );
END SIMULATORE;
/

CREATE OR REPLACE PACKAGE BODY SIMULATORE AS
    SUBTYPE T_NOME IS VARCHAR(60);

    FUNCTION RANDOM_NUMBER(
        P_MIN IN NUMBER,
        P_MAX IN NUMBER
    ) RETURN NUMBER IS
    BEGIN
        RETURN DBMS_RANDOM.VALUE(P_MIN, P_MAX);
    END RANDOM_NUMBER;

    FUNCTION RANDOM_INT(
        P_MIN IN PLS_INTEGER,
        P_MAX IN PLS_INTEGER
    ) RETURN PLS_INTEGER IS
    BEGIN
        RETURN TRUNC(DBMS_RANDOM.VALUE(P_MIN, P_MAX + 1));
    END RANDOM_INT;

    FUNCTION RANDOM_TRIANGULAR(
        P_MIN IN NUMBER,
        P_MAX IN NUMBER,
        P_MODE IN NUMBER
    ) RETURN NUMBER IS
        V_U NUMBER := DBMS_RANDOM.VALUE(0, 1);
        V_C NUMBER := (P_MODE - P_MIN) / (P_MAX - P_MIN);
    BEGIN
        IF V_U < V_C THEN
            RETURN P_MIN + SQRT(V_U * (P_MAX - P_MIN) * (P_MODE - P_MIN));
        END IF;

        RETURN P_MAX - SQRT((1 - V_U) * (P_MAX - P_MIN) * (P_MAX - P_MODE));
    END RANDOM_TRIANGULAR;

    FUNCTION IS_CELLA_WORKING(
        P_CODICE_CELLA_IDR IN CELLA_IDROPONICA.CODICE_CELLA_IDR%TYPE,
        P_NOME_STRUTTURA IN CELLA_IDROPONICA.NOME_STRUTTURA%TYPE
    ) RETURN BOOLEAN IS
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO V_COUNT
        FROM CICLO_COLTIVAZIONE CC
        WHERE CC.DATA_FINE_EFFETTIVA IS NULL
        AND CC.CODICE_CELLA_IDR = P_CODICE_CELLA_IDR
        AND CC.NOME_STRUTTURA = P_NOME_STRUTTURA;

        RETURN V_COUNT > 0;
    END IS_CELLA_WORKING;

    FUNCTION GET_SIM_START_DAY RETURN DATE IS
        V_MIN_ANIMALE DATE;
        V_MIN_CELLA DATE;
    BEGIN
        SELECT MIN(DATA_ALLOCAZIONE)
        INTO V_MIN_ANIMALE
        FROM ANIMALE_ALLOCATO_BLOCCO;

        SELECT MIN(DATA_MONTAGGIO)
        INTO V_MIN_CELLA
        FROM CELLA_IDROPONICA;

        IF V_MIN_ANIMALE IS NULL THEN
            RETURN V_MIN_CELLA;
        ELSIF V_MIN_CELLA IS NULL THEN
            RETURN V_MIN_ANIMALE;
        END IF;

        RETURN LEAST(V_MIN_ANIMALE, V_MIN_CELLA);
    END GET_SIM_START_DAY;

    FUNCTION GET_CYCLE_DURATION(
        P_DATA_INIZIO IN CICLO_COLTIVAZIONE.DATA_INIZIO%TYPE,
        P_CODICE_CELLA_IDR IN CICLO_COLTIVAZIONE.CODICE_CELLA_IDR%TYPE,
        P_NOME_STRUTTURA IN CICLO_COLTIVAZIONE.NOME_STRUTTURA%TYPE,
        P_NOME_TIPO_COLTURA IN CICLO_COLTIVAZIONE.NOME_TIPO_COLTURA%TYPE
    ) RETURN NUMBER IS
        V_DURATA NUMBER;
    BEGIN
        BEGIN
            SELECT MAX(TC.DURATA_CICLO_COLTURA_GIORNI)
            INTO V_DURATA
            FROM TIPO_COLTURA TC
            WHERE TC.NOME_SEMI IN (
                SELECT CCSM.NOME_SEMI
                FROM CICLO_COLT_UTILIZZA_SEMI_MISSIONE CCSM
                WHERE CCSM.DATA_INIZIO = P_DATA_INIZIO
                AND CCSM.CODICE_CELLA_IDR = P_CODICE_CELLA_IDR
                AND CCSM.NOME_STRUTTURA = P_NOME_STRUTTURA

                UNION

                SELECT CCPA.NOME_PRODOTTO
                FROM CICLO_COLT_UTILIZZA_PRODUZIONE_AGRICOLA CCPA
                WHERE CCPA.DATA_INIZIO = P_DATA_INIZIO
                AND CCPA.CODICE_CELLA_IDR = P_CODICE_CELLA_IDR
                AND CCPA.NOME_STRUTTURA = P_NOME_STRUTTURA
            );
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                V_DURATA := NULL;
        END;

        IF V_DURATA IS NULL THEN
            SELECT TC.DURATA_CICLO_COLTURA_GIORNI
            INTO V_DURATA
            FROM TIPO_COLTURA TC
            WHERE TC.NOME_TIPO_COLTURA = P_NOME_TIPO_COLTURA;
        END IF;

        RETURN V_DURATA;
    END GET_CYCLE_DURATION;

    FUNCTION GET_PLANTED_SEED_QUANTITY(
        P_DATA_INIZIO IN CICLO_COLTIVAZIONE.DATA_INIZIO%TYPE,
        P_CODICE_CELLA_IDR IN CICLO_COLTIVAZIONE.CODICE_CELLA_IDR%TYPE,
        P_NOME_STRUTTURA IN CICLO_COLTIVAZIONE.NOME_STRUTTURA%TYPE
    ) RETURN NUMBER IS
        V_QUANTITA NUMBER;
    BEGIN
        SELECT NVL(SUM(Q), 0)
        INTO V_QUANTITA
        FROM (
            SELECT CCSM.QUANTITA AS Q
            FROM CICLO_COLT_UTILIZZA_SEMI_MISSIONE CCSM
            WHERE CCSM.DATA_INIZIO = P_DATA_INIZIO
            AND CCSM.CODICE_CELLA_IDR = P_CODICE_CELLA_IDR
            AND CCSM.NOME_STRUTTURA = P_NOME_STRUTTURA

            UNION ALL

            SELECT CCPA.QUANTITA AS Q
            FROM CICLO_COLT_UTILIZZA_PRODUZIONE_AGRICOLA CCPA
            WHERE CCPA.DATA_INIZIO = P_DATA_INIZIO
            AND CCPA.CODICE_CELLA_IDR = P_CODICE_CELLA_IDR
            AND CCPA.NOME_STRUTTURA = P_NOME_STRUTTURA
        );

        RETURN V_QUANTITA;
    END GET_PLANTED_SEED_QUANTITY;

    FUNCTION END_CYCLE_PROB(
        P_DAYS_FROM_START IN NUMBER,
        P_EXPECTED_DAYS IN NUMBER
    ) RETURN BOOLEAN IS
        V_MAX_DAYS PLS_INTEGER := GREATEST(P_DAYS_FROM_START, P_EXPECTED_DAYS);
        V_MIN_DAYS PLS_INTEGER := LEAST(P_DAYS_FROM_START, P_EXPECTED_DAYS);
        V_N PLS_INTEGER;
    BEGIN
        V_N := RANDOM_INT(V_MIN_DAYS, V_MAX_DAYS);

        IF V_N = V_MAX_DAYS THEN
            RETURN TRUE;
        END IF;

        IF V_MAX_DAYS != P_EXPECTED_DAYS THEN
            RETURN RANDOM_INT(1, 10) = 10;
        END IF;

        RETURN FALSE;
    END END_CYCLE_PROB;

    FUNCTION IS_CYCLE_FAILED(
        P_DAYS_FROM_START IN NUMBER,
        P_EXPECTED_DAYS IN NUMBER
    ) RETURN BOOLEAN IS
    BEGIN
        RETURN P_DAYS_FROM_START < (P_EXPECTED_DAYS * 0.8);
    END IS_CYCLE_FAILED;

    FUNCTION IS_REUSABLE_SEED_PRODUCT(
        P_NOME_PRODOTTO IN T_NOME
    ) RETURN BOOLEAN IS
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO V_COUNT
        FROM TIPO_COLTURA TC
        WHERE TC.NOME_SEMI = P_NOME_PRODOTTO;

        RETURN V_COUNT > 0;
    END IS_REUSABLE_SEED_PRODUCT;

    FUNCTION GET_TIPO_COLTURA_BY_SEED(
        P_NOME_SEMI IN T_NOME
    ) RETURN T_NOME IS
        V_NOME_TIPO_COLTURA T_NOME;
    BEGIN
        SELECT NOME_TIPO_COLTURA
        INTO V_NOME_TIPO_COLTURA
        FROM (
            SELECT TC.NOME_TIPO_COLTURA
            FROM TIPO_COLTURA TC
            WHERE UPPER(TC.NOME_SEMI) = UPPER(P_NOME_SEMI)
            ORDER BY DBMS_RANDOM.VALUE
        )
        WHERE ROWNUM = 1;

        RETURN V_NOME_TIPO_COLTURA;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN NULL;
    END GET_TIPO_COLTURA_BY_SEED;

    FUNCTION GET_MOD_COLT_BY_TIPO_COLTURA(
        P_NOME_TIPO_COLTURA IN T_NOME
    ) RETURN T_NOME IS
        V_NOME_MODALITA T_NOME;
    BEGIN
        SELECT NOME_MODALITA_COLTIVAZIONE
        INTO V_NOME_MODALITA
        FROM (
            SELECT TCMC.NOME_MODALITA_COLTIVAZIONE
            FROM TIPO_COLT_ACCETTA_MOD_COLT TCMC
            WHERE UPPER(TCMC.NOME_TIPO_COLTURA) = UPPER(P_NOME_TIPO_COLTURA)
            ORDER BY DBMS_RANDOM.VALUE
        )
        WHERE ROWNUM = 1;

        RETURN V_NOME_MODALITA;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN NULL;
    END GET_MOD_COLT_BY_TIPO_COLTURA;

    PROCEDURE INSERT_COLTIVATION_CYCLE(
        P_DATA_INIZIO IN CICLO_COLTIVAZIONE.DATA_INIZIO%TYPE,
        P_CODICE_CELLA_IDR IN CICLO_COLTIVAZIONE.CODICE_CELLA_IDR%TYPE,
        P_NOME_STRUTTURA IN CICLO_COLTIVAZIONE.NOME_STRUTTURA%TYPE,
        P_NOME_MOD_COLTIVAZIONE IN CICLO_COLTIVAZIONE.NOME_MOD_COLTIVAZIONE%TYPE,
        P_NOME_TIPO_COLTURA IN CICLO_COLTIVAZIONE.NOME_TIPO_COLTURA%TYPE
    ) IS
    BEGIN
        INSERT INTO CICLO_COLTIVAZIONE (
            DATA_INIZIO,
            CODICE_CELLA_IDR,
            NOME_STRUTTURA,
            DATA_FINE_EFFETTIVA,
            NOME_MOD_COLTIVAZIONE,
            NOME_TIPO_COLTURA
        ) VALUES (
            P_DATA_INIZIO,
            P_CODICE_CELLA_IDR,
            P_NOME_STRUTTURA,
            NULL,
            P_NOME_MOD_COLTIVAZIONE,
            P_NOME_TIPO_COLTURA
        );
    END INSERT_COLTIVATION_CYCLE;

    PROCEDURE INSERT_CYCLE_USE_MISSION_SEED(
        P_DATA_INIZIO IN CICLO_COLT_UTILIZZA_SEMI_MISSIONE.DATA_INIZIO%TYPE,
        P_CODICE_CELLA_IDR IN CICLO_COLT_UTILIZZA_SEMI_MISSIONE.CODICE_CELLA_IDR%TYPE,
        P_NOME_STRUTTURA IN CICLO_COLT_UTILIZZA_SEMI_MISSIONE.NOME_STRUTTURA%TYPE,
        P_NOME_SEMI IN CICLO_COLT_UTILIZZA_SEMI_MISSIONE.NOME_SEMI%TYPE,
        P_DATA_ARRIVO_SEMI IN CICLO_COLT_UTILIZZA_SEMI_MISSIONE.DATA_ARRIVO_SEMI%TYPE,
        P_QUANTITA IN CICLO_COLT_UTILIZZA_SEMI_MISSIONE.QUANTITA%TYPE
    ) IS
    BEGIN
        INSERT INTO CICLO_COLT_UTILIZZA_SEMI_MISSIONE (
            DATA_INIZIO,
            CODICE_CELLA_IDR,
            NOME_STRUTTURA,
            NOME_SEMI,
            DATA_ARRIVO_SEMI,
            QUANTITA
        ) VALUES (
            P_DATA_INIZIO,
            P_CODICE_CELLA_IDR,
            P_NOME_STRUTTURA,
            P_NOME_SEMI,
            P_DATA_ARRIVO_SEMI,
            P_QUANTITA
        );
    END INSERT_CYCLE_USE_MISSION_SEED;

    PROCEDURE INSERT_CYCLE_USE_AGRI_PRODUCTION(
        P_DATA_INIZIO IN CICLO_COLT_UTILIZZA_PRODUZIONE_AGRICOLA.DATA_INIZIO%TYPE,
        P_CODICE_CELLA_IDR IN CICLO_COLT_UTILIZZA_PRODUZIONE_AGRICOLA.CODICE_CELLA_IDR%TYPE,
        P_NOME_STRUTTURA IN CICLO_COLT_UTILIZZA_PRODUZIONE_AGRICOLA.NOME_STRUTTURA%TYPE,
        P_DATA_PRODUZIONE_AGRICOLA IN CICLO_COLT_UTILIZZA_PRODUZIONE_AGRICOLA.DATA_PRODUZIONE_AGRICOLA%TYPE,
        P_DATA_INIZIO_CICLO_COLT IN CICLO_COLT_UTILIZZA_PRODUZIONE_AGRICOLA.DATA_INIZIO_CICLO_COLTIVAZIONE%TYPE,
        P_CODICE_CELLA_IDR_PROD IN CICLO_COLT_UTILIZZA_PRODUZIONE_AGRICOLA.CODICE_CELLA_IDR_PROD_AGR%TYPE,
        P_NOME_STRUTTURA_PROD IN CICLO_COLT_UTILIZZA_PRODUZIONE_AGRICOLA.NOME_STRUTTURA_PROD_AGR%TYPE,
        P_NOME_PRODOTTO IN CICLO_COLT_UTILIZZA_PRODUZIONE_AGRICOLA.NOME_PRODOTTO%TYPE,
        P_QUANTITA IN CICLO_COLT_UTILIZZA_PRODUZIONE_AGRICOLA.QUANTITA%TYPE
    ) IS
    BEGIN
        INSERT INTO CICLO_COLT_UTILIZZA_PRODUZIONE_AGRICOLA (
            DATA_INIZIO,
            CODICE_CELLA_IDR,
            NOME_STRUTTURA,
            DATA_PRODUZIONE_AGRICOLA,
            DATA_INIZIO_CICLO_COLTIVAZIONE,
            CODICE_CELLA_IDR_PROD_AGR,
            NOME_STRUTTURA_PROD_AGR,
            NOME_PRODOTTO,
            QUANTITA
        ) VALUES (
            P_DATA_INIZIO,
            P_CODICE_CELLA_IDR,
            P_NOME_STRUTTURA,
            P_DATA_PRODUZIONE_AGRICOLA,
            P_DATA_INIZIO_CICLO_COLT,
            P_CODICE_CELLA_IDR_PROD,
            P_NOME_STRUTTURA_PROD,
            P_NOME_PRODOTTO,
            P_QUANTITA
        );
    END INSERT_CYCLE_USE_AGRI_PRODUCTION;

    PROCEDURE INSERT_AGRI_PRODUCTION(
        P_DATA_PRODUZIONE IN PRODUZIONE_AGRICOLA.DATA_PRODUZIONE_AGRICOLA%TYPE,
        P_DATA_INIZIO_CICLO IN PRODUZIONE_AGRICOLA.DATA_INIZIO_CICLO_COLTIVAZIONE%TYPE,
        P_CODICE_CELLA_IDR IN PRODUZIONE_AGRICOLA.CODICE_CELLA_IDR%TYPE,
        P_NOME_STRUTTURA IN PRODUZIONE_AGRICOLA.NOME_STRUTTURA%TYPE,
        P_NOME_PRODOTTO IN PRODUZIONE_AGRICOLA.NOME_PRODOTTO%TYPE,
        P_QUANTITA IN PRODUZIONE_AGRICOLA.QUANTITA%TYPE
    ) IS
    BEGIN
        INSERT INTO PRODUZIONE_AGRICOLA (
            DATA_PRODUZIONE_AGRICOLA,
            DATA_INIZIO_CICLO_COLTIVAZIONE,
            CODICE_CELLA_IDR,
            NOME_STRUTTURA,
            NOME_PRODOTTO,
            QUANTITA
        ) VALUES (
            P_DATA_PRODUZIONE,
            P_DATA_INIZIO_CICLO,
            P_CODICE_CELLA_IDR,
            P_NOME_STRUTTURA,
            P_NOME_PRODOTTO,
            ROUND(P_QUANTITA, 2)
        );
    END INSERT_AGRI_PRODUCTION;

    PROCEDURE END_CYCLE(
        P_DATA_INIZIO IN CICLO_COLTIVAZIONE.DATA_INIZIO%TYPE,
        P_CODICE_CELLA_IDR IN CICLO_COLTIVAZIONE.CODICE_CELLA_IDR%TYPE,
        P_NOME_STRUTTURA IN CICLO_COLTIVAZIONE.NOME_STRUTTURA%TYPE,
        P_DATA_FINE IN CICLO_COLTIVAZIONE.DATA_FINE_EFFETTIVA%TYPE
    ) IS
    BEGIN
        UPDATE CICLO_COLTIVAZIONE
        SET DATA_FINE_EFFETTIVA = P_DATA_FINE
        WHERE DATA_INIZIO = P_DATA_INIZIO
        AND CODICE_CELLA_IDR = P_CODICE_CELLA_IDR
        AND NOME_STRUTTURA = P_NOME_STRUTTURA;
    END END_CYCLE;

    PROCEDURE START_CICLO_COLTIVAZIONE(
        P_CODICE_CELLA_IDR IN CELLA_IDROPONICA.CODICE_CELLA_IDR%TYPE,
        P_NOME_STRUTTURA IN CELLA_IDROPONICA.NOME_STRUTTURA%TYPE,
        P_DATA IN DATE
    ) IS
        V_NOME_SEMI T_NOME;
        V_DATA_ARRIVO_SEMI DATE;
        V_DATA_PRODUZIONE_AGRICOLA DATE;
        V_DATA_INIZIO_CICLO_COLT DATE;
        V_CODICE_CELLA_IDR_PROD CELLA_IDROPONICA.CODICE_CELLA_IDR%TYPE;
        V_NOME_STRUTTURA_PROD CELLA_IDROPONICA.NOME_STRUTTURA%TYPE;
        V_QUANTITA_RESIDUA NUMBER;
        V_TO_PLANT NUMBER;
        V_NOME_TIPO_COLTURA T_NOME;
        V_NOME_MODALITA T_NOME;
        V_USE_AGRI_PRODUCTION BOOLEAN := FALSE;
    BEGIN
        IF RANDOM_INT(1, 3) != 3 THEN
            RETURN;
        END IF;

        BEGIN
            SELECT
                DATA_PRODUZIONE_AGRICOLA,
                DATA_INIZIO_CICLO_COLTIVAZIONE,
                CODICE_CELLA_IDR,
                NOME_STRUTTURA,
                NOME_PRODOTTO,
                QUANTITA_RESIDUA
            INTO
                V_DATA_PRODUZIONE_AGRICOLA,
                V_DATA_INIZIO_CICLO_COLT,
                V_CODICE_CELLA_IDR_PROD,
                V_NOME_STRUTTURA_PROD,
                V_NOME_SEMI,
                V_QUANTITA_RESIDUA
            FROM (
                SELECT
                    DATA_PRODUZIONE_AGRICOLA,
                    DATA_INIZIO_CICLO_COLTIVAZIONE,
                    CODICE_CELLA_IDR,
                    NOME_STRUTTURA,
                    NOME_PRODOTTO,
                    QUANTITA_RESIDUA
                FROM (
                    SELECT
                        PA.DATA_PRODUZIONE_AGRICOLA,
                        PA.DATA_INIZIO_CICLO_COLTIVAZIONE,
                        PA.CODICE_CELLA_IDR,
                        PA.NOME_STRUTTURA,
                        PA.NOME_PRODOTTO,
                        PA.QUANTITA - NVL((
                            SELECT SUM(CCPA.QUANTITA)
                            FROM CICLO_COLT_UTILIZZA_PRODUZIONE_AGRICOLA CCPA
                            WHERE CCPA.DATA_PRODUZIONE_AGRICOLA = PA.DATA_PRODUZIONE_AGRICOLA
                            AND CCPA.DATA_INIZIO_CICLO_COLTIVAZIONE = PA.DATA_INIZIO_CICLO_COLTIVAZIONE
                            AND CCPA.CODICE_CELLA_IDR_PROD_AGR = PA.CODICE_CELLA_IDR
                            AND CCPA.NOME_STRUTTURA_PROD_AGR = PA.NOME_STRUTTURA
                            AND CCPA.NOME_PRODOTTO = PA.NOME_PRODOTTO
                        ), 0) AS QUANTITA_RESIDUA
                    FROM PRODUZIONE_AGRICOLA PA
                    WHERE PA.NOME_PRODOTTO IN (
                        SELECT TC.NOME_SEMI
                        FROM TIPO_COLTURA TC
                    )
                )
                WHERE QUANTITA_RESIDUA >= 2
                ORDER BY DBMS_RANDOM.VALUE
            )
            WHERE ROWNUM = 1;

            V_USE_AGRI_PRODUCTION := TRUE;
        EXCEPTION
            WHEN NO_DATA_FOUND THEN
                V_USE_AGRI_PRODUCTION := FALSE;
        END;

        IF NOT V_USE_AGRI_PRODUCTION THEN
            BEGIN
                SELECT NOME_SEMI, DATA_ARRIVO_SEMI, QUANTITA_RESIDUA
                INTO V_NOME_SEMI, V_DATA_ARRIVO_SEMI, V_QUANTITA_RESIDUA
                FROM (
                    SELECT
                        NOME_SEMI,
                        DATA_ARRIVO_SEMI,
                        QUANTITA_RESIDUA
                    FROM (
                        SELECT
                            SM.NOME_SEMI,
                            SM.DATA_ARRIVO_SEMI,
                            SM.QUANTITA_SEMI - NVL((
                                SELECT SUM(CCSM.QUANTITA)
                                FROM CICLO_COLT_UTILIZZA_SEMI_MISSIONE CCSM
                                WHERE CCSM.DATA_ARRIVO_SEMI = SM.DATA_ARRIVO_SEMI
                                AND CCSM.NOME_SEMI = SM.NOME_SEMI
                            ), 0) AS QUANTITA_RESIDUA
                        FROM SEMI_MISSIONE SM
                    )
                    WHERE QUANTITA_RESIDUA >= 2
                    ORDER BY DBMS_RANDOM.VALUE
                )
                WHERE ROWNUM = 1;
            EXCEPTION
                WHEN NO_DATA_FOUND THEN
                    DBMS_OUTPUT.PUT_LINE('No available seeds');
                    RETURN;
            END;
        END IF;

        V_NOME_TIPO_COLTURA := GET_TIPO_COLTURA_BY_SEED(V_NOME_SEMI);
        IF V_NOME_TIPO_COLTURA IS NULL THEN
            RETURN;
        END IF;

        V_NOME_MODALITA := GET_MOD_COLT_BY_TIPO_COLTURA(V_NOME_TIPO_COLTURA);
        IF V_NOME_MODALITA IS NULL THEN
            RETURN;
        END IF;

        V_TO_PLANT := ROUND(RANDOM_NUMBER(0.5, LEAST(V_QUANTITA_RESIDUA, 3)), 3);

        INSERT_COLTIVATION_CYCLE(
            TRUNC(P_DATA),
            P_CODICE_CELLA_IDR,
            P_NOME_STRUTTURA,
            V_NOME_MODALITA,
            V_NOME_TIPO_COLTURA
        );

        IF V_USE_AGRI_PRODUCTION THEN
            INSERT_CYCLE_USE_AGRI_PRODUCTION(
                TRUNC(P_DATA),
                P_CODICE_CELLA_IDR,
                P_NOME_STRUTTURA,
                V_DATA_PRODUZIONE_AGRICOLA,
                V_DATA_INIZIO_CICLO_COLT,
                V_CODICE_CELLA_IDR_PROD,
                V_NOME_STRUTTURA_PROD,
                V_NOME_SEMI,
                V_TO_PLANT
            );
        ELSE
            INSERT_CYCLE_USE_MISSION_SEED(
                TRUNC(P_DATA),
                P_CODICE_CELLA_IDR,
                P_NOME_STRUTTURA,
                V_NOME_SEMI,
                V_DATA_ARRIVO_SEMI,
                V_TO_PLANT
            );
        END IF;

        DBMS_OUTPUT.PUT_LINE(
            'Started a new coltivation cycle in cell: ' ||
            P_CODICE_CELLA_IDR || ' ' || P_NOME_STRUTTURA
        );
    END START_CICLO_COLTIVAZIONE;

    PROCEDURE SIMULA_CELLA(
        P_CODICE_CELLA_IDR IN CELLA_IDROPONICA.CODICE_CELLA_IDR%TYPE,
        P_NOME_STRUTTURA IN CELLA_IDROPONICA.NOME_STRUTTURA%TYPE,
        P_DATA IN DATE
    ) IS
        V_DATA_INIZIO CICLO_COLTIVAZIONE.DATA_INIZIO%TYPE;
        V_NOME_TIPO_COLTURA CICLO_COLTIVAZIONE.NOME_TIPO_COLTURA%TYPE;
        V_DURATA NUMBER;
        V_DAYS_FROM_START NUMBER;
        V_PLANTED_QUANTITY NUMBER;
        V_PRODUCTED NUMBER;
    BEGIN
        IF NOT IS_CELLA_WORKING(P_CODICE_CELLA_IDR, P_NOME_STRUTTURA) THEN
            START_CICLO_COLTIVAZIONE(P_CODICE_CELLA_IDR, P_NOME_STRUTTURA, P_DATA);
            RETURN;
        END IF;

        SELECT DATA_INIZIO, NOME_TIPO_COLTURA
        INTO V_DATA_INIZIO, V_NOME_TIPO_COLTURA
        FROM (
            SELECT CC.DATA_INIZIO, CC.NOME_TIPO_COLTURA
            FROM CICLO_COLTIVAZIONE CC
            WHERE CC.CODICE_CELLA_IDR = P_CODICE_CELLA_IDR
            AND CC.NOME_STRUTTURA = P_NOME_STRUTTURA
            ORDER BY CC.DATA_INIZIO DESC
        )
        WHERE ROWNUM = 1;

        V_DURATA := GET_CYCLE_DURATION(
            V_DATA_INIZIO,
            P_CODICE_CELLA_IDR,
            P_NOME_STRUTTURA,
            V_NOME_TIPO_COLTURA
        );
        V_DAYS_FROM_START := TRUNC(P_DATA) - TRUNC(V_DATA_INIZIO);

        DBMS_OUTPUT.PUT_LINE(
            'Cell ' || P_NOME_STRUTTURA || ' ' || P_CODICE_CELLA_IDR ||
            ' is now working from ' || V_DAYS_FROM_START || '/' || V_DURATA
        );

        IF END_CYCLE_PROB(V_DAYS_FROM_START, V_DURATA) THEN
            V_PLANTED_QUANTITY := GET_PLANTED_SEED_QUANTITY(
                V_DATA_INIZIO,
                P_CODICE_CELLA_IDR,
                P_NOME_STRUTTURA
            );

            IF NOT IS_CYCLE_FAILED(V_DAYS_FROM_START, V_DURATA) THEN
                FOR PROD IN (
                    SELECT
                        NOME_PRODOTTO,
                        QUANTITA_STIMATE_PER_UNITA_SEMI
                    FROM TIPO_COLTURA_TIPO_PRODOTTO
                    WHERE NOME_TIPO_COLTURA = V_NOME_TIPO_COLTURA
                ) LOOP
                    V_PRODUCTED :=
                        V_PLANTED_QUANTITY *
                        PROD.QUANTITA_STIMATE_PER_UNITA_SEMI *
                        RANDOM_TRIANGULAR(0.5, 1.5, 1.0);

                    IF IS_REUSABLE_SEED_PRODUCT(PROD.NOME_PRODOTTO) THEN
                        V_PRODUCTED := GREATEST(
                            V_PRODUCTED,
                            V_PLANTED_QUANTITY * RANDOM_NUMBER(1.8, 3.0)
                        );
                    END IF;

                    INSERT_AGRI_PRODUCTION(
                        TRUNC(P_DATA),
                        V_DATA_INIZIO,
                        P_CODICE_CELLA_IDR,
                        P_NOME_STRUTTURA,
                        PROD.NOME_PRODOTTO,
                        V_PRODUCTED
                    );
                END LOOP;
            END IF;

            END_CYCLE(
                V_DATA_INIZIO,
                P_CODICE_CELLA_IDR,
                P_NOME_STRUTTURA,
                TRUNC(P_DATA)
            );

            DBMS_OUTPUT.PUT_LINE(
                'Cell ' || P_NOME_STRUTTURA || ' ' || P_CODICE_CELLA_IDR ||
                ' has now ended the cycle'
            );
        END IF;
    END SIMULA_CELLA;

    PROCEDURE SIMULA_GIORNO(
        P_DATA IN DATE
    ) IS
    BEGIN
        FOR CELL IN (
            SELECT CODICE_CELLA_IDR, NOME_STRUTTURA
            FROM CELLA_IDROPONICA
            WHERE DATA_MONTAGGIO <= TRUNC(P_DATA)
            AND (DATA_SMONTAGGIO IS NULL OR DATA_SMONTAGGIO > TRUNC(P_DATA))
        ) LOOP
            SIMULA_CELLA(
                CELL.CODICE_CELLA_IDR,
                CELL.NOME_STRUTTURA,
                TRUNC(P_DATA)
            );
        END LOOP;
    END SIMULA_GIORNO;

    PROCEDURE RUN_SIMULAZIONE(
        P_DATA_FINE IN DATE DEFAULT TRUNC(SYSDATE)
    ) IS
        V_CURRENT_DAY DATE := GET_SIM_START_DAY;
    BEGIN
        IF V_CURRENT_DAY IS NULL THEN
            DBMS_OUTPUT.PUT_LINE('No simulation start day found');
            RETURN;
        END IF;

        WHILE V_CURRENT_DAY < TRUNC(P_DATA_FINE) LOOP
            SIMULA_GIORNO(V_CURRENT_DAY);
            V_CURRENT_DAY := V_CURRENT_DAY + 1;
        END LOOP;

        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE;
    END RUN_SIMULAZIONE;
END SIMULATORE;
/
