CREATE OR REPLACE PACKAGE SIMULATORE_SENSORI AS
    PROCEDURE RUN_SIMULAZIONE(
        P_DATA_FINE IN DATE DEFAULT TRUNC(SYSDATE),
        P_MINUTI_INTERVALLO IN NUMBER DEFAULT 60
    );

    PROCEDURE SIMULA_GIORNO(
        P_DATA IN DATE,
        P_MINUTI_INTERVALLO IN NUMBER DEFAULT 60
    );

    PROCEDURE SIMULA_SENSORE(
        P_SERIALE IN SENSORE.SERIALE%TYPE,
        P_NOME_PRODUTTORE IN SENSORE.NOME_PRODUTTORE%TYPE,
        P_NOME_MODELLO IN SENSORE.NOME_MODELLO%TYPE,
        P_DATA_ORA IN DATE,
        P_MINUTI_INTERVALLO IN NUMBER DEFAULT 60
    );
END SIMULATORE_SENSORI;
/

CREATE OR REPLACE PACKAGE BODY SIMULATORE_SENSORI AS
    SUBTYPE T_NOME IS VARCHAR(60);

    FUNCTION RANDOM_NUMBER(
        P_MIN IN NUMBER,
        P_MAX IN NUMBER
    ) RETURN NUMBER IS
    BEGIN
        RETURN DBMS_RANDOM.VALUE(P_MIN, P_MAX);
    END RANDOM_NUMBER;

    FUNCTION CLAMP(
        P_VALUE IN NUMBER,
        P_MIN IN NUMBER,
        P_MAX IN NUMBER
    ) RETURN NUMBER IS
    BEGIN
        RETURN LEAST(GREATEST(P_VALUE, P_MIN), P_MAX);
    END CLAMP;

    FUNCTION GET_SIM_START_DAY RETURN DATE IS
        V_MIN_CELLA DATE;
        V_MIN_BLOCCO DATE;
    BEGIN
        SELECT MIN(DATA_MONTAGGIO)
        INTO V_MIN_CELLA
        FROM CELLA_IDR_CONTIENE_SENSORE;

        SELECT MIN(DATA_MONTAGGIO)
        INTO V_MIN_BLOCCO
        FROM BLOCCO_ANIMALE_CONTIENE_SENSORE;

        IF V_MIN_CELLA IS NULL THEN
            RETURN V_MIN_BLOCCO;
        ELSIF V_MIN_BLOCCO IS NULL THEN
            RETURN V_MIN_CELLA;
        END IF;

        RETURN LEAST(V_MIN_CELLA, V_MIN_BLOCCO);
    END GET_SIM_START_DAY;

    FUNCTION IS_SENSOR_ACTIVE(
        P_SERIALE IN SENSORE.SERIALE%TYPE,
        P_NOME_PRODUTTORE IN SENSORE.NOME_PRODUTTORE%TYPE,
        P_NOME_MODELLO IN SENSORE.NOME_MODELLO%TYPE,
        P_DATA_ORA IN DATE
    ) RETURN BOOLEAN IS
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO V_COUNT
        FROM SENSORE S
        WHERE S.SERIALE = P_SERIALE
        AND S.NOME_PRODUTTORE = P_NOME_PRODUTTORE
        AND S.NOME_MODELLO = P_NOME_MODELLO
        AND (
            EXISTS (
                SELECT 1
                FROM CELLA_IDR_CONTIENE_SENSORE CICS
                JOIN CELLA_IDROPONICA CI
                    ON CI.CODICE_CELLA_IDR = CICS.CODICE_CELLA_IDR
                    AND CI.NOME_STRUTTURA = CICS.NOME_STRUTTURA
                WHERE CICS.SERIALE = S.SERIALE
                AND CICS.NOME_PRODUTTORE = S.NOME_PRODUTTORE
                AND CICS.NOME_MODELLO = S.NOME_MODELLO
                AND CICS.DATA_MONTAGGIO <= TRUNC(P_DATA_ORA)
                AND (CICS.DATA_SMONTAGGIO IS NULL OR CICS.DATA_SMONTAGGIO > TRUNC(P_DATA_ORA))
                AND CI.DATA_MONTAGGIO <= TRUNC(P_DATA_ORA)
                AND (CI.DATA_SMONTAGGIO IS NULL OR CI.DATA_SMONTAGGIO > TRUNC(P_DATA_ORA))
            )
            OR
            EXISTS (
                SELECT 1
                FROM BLOCCO_ANIMALE_CONTIENE_SENSORE BACS
                JOIN BLOCCO_ANIMALE BA
                    ON BA.NUMERO_BLOCCO = BACS.NUMERO_BLOCCO
                    AND BA.NOME_STRUTTURA = BACS.NOME_STRUTTURA
                WHERE BACS.SERIALE = S.SERIALE
                AND BACS.NOME_PRODUTTORE = S.NOME_PRODUTTORE
                AND BACS.NOME_MODELLO = S.NOME_MODELLO
                AND BACS.DATA_MONTAGGIO <= TRUNC(P_DATA_ORA)
                AND (BACS.DATA_SMONTAGGIO IS NULL OR BACS.DATA_SMONTAGGIO > TRUNC(P_DATA_ORA))
                AND BA.DATA_MONTAGGIO <= TRUNC(P_DATA_ORA)
                AND (BA.DATA_SMONTAGGIO IS NULL OR BA.DATA_SMONTAGGIO > TRUNC(P_DATA_ORA))
            )
        );

        RETURN V_COUNT > 0;
    END IS_SENSOR_ACTIVE;

    FUNCTION GET_ACTIVE_CELL_MODALITA(
        P_CODICE_CELLA_IDR IN CELLA_IDROPONICA.CODICE_CELLA_IDR%TYPE,
        P_NOME_STRUTTURA IN CELLA_IDROPONICA.NOME_STRUTTURA%TYPE,
        P_DATA_ORA IN DATE
    ) RETURN T_NOME IS
        V_NOME_MODALITA T_NOME;
    BEGIN
        SELECT NOME_MOD_COLTIVAZIONE
        INTO V_NOME_MODALITA
        FROM (
            SELECT CC.NOME_MOD_COLTIVAZIONE
            FROM CICLO_COLTIVAZIONE CC
            WHERE CC.CODICE_CELLA_IDR = P_CODICE_CELLA_IDR
            AND CC.NOME_STRUTTURA = P_NOME_STRUTTURA
            AND CC.DATA_INIZIO <= TRUNC(P_DATA_ORA)
            AND (CC.DATA_FINE_EFFETTIVA IS NULL OR CC.DATA_FINE_EFFETTIVA > TRUNC(P_DATA_ORA))
            ORDER BY CC.DATA_INIZIO DESC
        )
        WHERE ROWNUM = 1;

        RETURN V_NOME_MODALITA;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN NULL;
    END GET_ACTIVE_CELL_MODALITA;

    FUNCTION GET_CELL_TEMPERATURE(
        P_CODICE_CELLA_IDR IN CELLA_IDROPONICA.CODICE_CELLA_IDR%TYPE,
        P_NOME_STRUTTURA IN CELLA_IDROPONICA.NOME_STRUTTURA%TYPE,
        P_DATA_ORA IN DATE
    ) RETURN NUMBER IS
        V_NOME_MODALITA T_NOME;
        V_TEMP_MIN NUMBER;
        V_TEMP_MAX NUMBER;
        V_TARGET NUMBER;
        V_HOUR NUMBER := TO_NUMBER(TO_CHAR(P_DATA_ORA, 'HH24'));
        V_DAY_WAVE NUMBER;
    BEGIN
        V_NOME_MODALITA := GET_ACTIVE_CELL_MODALITA(P_CODICE_CELLA_IDR, P_NOME_STRUTTURA, P_DATA_ORA);

        IF V_NOME_MODALITA IS NULL THEN
            RETURN RANDOM_NUMBER(289, 296);
        END IF;

        SELECT TEMPERATURA_MIN, TEMPERATURA_MAX
        INTO V_TEMP_MIN, V_TEMP_MAX
        FROM MODALITA_COLTIVAZIONE
        WHERE NOME_MODALITA_COLTIVAZIONE = V_NOME_MODALITA;

        V_TARGET := (V_TEMP_MIN + V_TEMP_MAX) / 2;
        V_DAY_WAVE := CASE
            WHEN V_HOUR BETWEEN 11 AND 17 THEN RANDOM_NUMBER(0.3, 1.2)
            WHEN V_HOUR BETWEEN 0 AND 5 THEN RANDOM_NUMBER(-1.2, -0.3)
            ELSE RANDOM_NUMBER(-0.5, 0.5)
        END;

        RETURN V_TARGET + V_DAY_WAVE + RANDOM_NUMBER(-0.4, 0.4);
    END GET_CELL_TEMPERATURE;

    FUNCTION GET_CELL_HUMIDITY(
        P_CODICE_CELLA_IDR IN CELLA_IDROPONICA.CODICE_CELLA_IDR%TYPE,
        P_NOME_STRUTTURA IN CELLA_IDROPONICA.NOME_STRUTTURA%TYPE,
        P_DATA_ORA IN DATE
    ) RETURN NUMBER IS
        V_NOME_MODALITA T_NOME;
        V_UMIDITA_MIN NUMBER;
        V_UMIDITA_MAX NUMBER;
        V_TARGET NUMBER;
        V_HOUR NUMBER := TO_NUMBER(TO_CHAR(P_DATA_ORA, 'HH24'));
    BEGIN
        V_NOME_MODALITA := GET_ACTIVE_CELL_MODALITA(P_CODICE_CELLA_IDR, P_NOME_STRUTTURA, P_DATA_ORA);

        IF V_NOME_MODALITA IS NULL THEN
            RETURN RANDOM_NUMBER(45, 65);
        END IF;

        SELECT UMIDITA_MIN, UMIDITA_MAX
        INTO V_UMIDITA_MIN, V_UMIDITA_MAX
        FROM MODALITA_COLTIVAZIONE
        WHERE NOME_MODALITA_COLTIVAZIONE = V_NOME_MODALITA;

        V_TARGET := (V_UMIDITA_MIN + V_UMIDITA_MAX) / 2;

        IF V_HOUR BETWEEN 12 AND 18 THEN
            RETURN V_TARGET + RANDOM_NUMBER(-6, 1);
        END IF;

        RETURN V_TARGET + RANDOM_NUMBER(-2, 6);
    END GET_CELL_HUMIDITY;

    FUNCTION GET_CELL_ENERGY(
        P_CODICE_CELLA_IDR IN CELLA_IDROPONICA.CODICE_CELLA_IDR%TYPE,
        P_NOME_STRUTTURA IN CELLA_IDROPONICA.NOME_STRUTTURA%TYPE,
        P_DATA_ORA IN DATE,
        P_MINUTI_INTERVALLO IN NUMBER
    ) RETURN NUMBER IS
        V_NOME_MODALITA T_NOME;
        V_ORE_LUCE NUMBER;
        V_SISTEMA_ILLUMINAZIONE MODALITA_COLTIVAZIONE.SISTEMA_ILLUMINAZIONE%TYPE;
        V_HOUR NUMBER := TO_NUMBER(TO_CHAR(P_DATA_ORA, 'HH24'));
        V_KW NUMBER;
    BEGIN
        V_NOME_MODALITA := GET_ACTIVE_CELL_MODALITA(P_CODICE_CELLA_IDR, P_NOME_STRUTTURA, P_DATA_ORA);

        IF V_NOME_MODALITA IS NULL THEN
            RETURN RANDOM_NUMBER(0.02, 0.08) * (P_MINUTI_INTERVALLO / 60);
        END IF;

        SELECT ORE_LUCE_GIORNO, SISTEMA_ILLUMINAZIONE
        INTO V_ORE_LUCE, V_SISTEMA_ILLUMINAZIONE
        FROM MODALITA_COLTIVAZIONE
        WHERE NOME_MODALITA_COLTIVAZIONE = V_NOME_MODALITA;

        V_KW := CASE V_SISTEMA_ILLUMINAZIONE
            WHEN 'LED_FULL' THEN RANDOM_NUMBER(0.9, 1.6)
            WHEN 'LED_BIANCO' THEN RANDOM_NUMBER(0.6, 1.1)
            WHEN 'LED_BLU' THEN RANDOM_NUMBER(0.4, 0.8)
            WHEN 'LED_VIOLA' THEN RANDOM_NUMBER(0.5, 0.9)
            WHEN 'FLUORESCENTE' THEN RANDOM_NUMBER(1.2, 2.1)
            ELSE RANDOM_NUMBER(0.1, 0.3)
        END;

        IF V_HOUR >= V_ORE_LUCE THEN
            V_KW := V_KW * RANDOM_NUMBER(0.15, 0.35);
        END IF;

        RETURN V_KW * (P_MINUTI_INTERVALLO / 60);
    END GET_CELL_ENERGY;

    FUNCTION GET_BLOCK_TARGET_TEMP(
        P_NUMERO_BLOCCO IN BLOCCO_ANIMALE.NUMERO_BLOCCO%TYPE,
        P_NOME_STRUTTURA IN BLOCCO_ANIMALE.NOME_STRUTTURA%TYPE,
        P_DATA_ORA IN DATE
    ) RETURN NUMBER IS
        V_TEMP NUMBER;
    BEGIN
        SELECT AVG(TA.TEMPERATURA_IDEALE)
        INTO V_TEMP
        FROM ANIMALE_ALLOCATO_BLOCCO AAB
        JOIN ANIMALE A
            ON A.ETICHETTA = AAB.ETICHETTA_ANIMALE
        JOIN TIPO_ANIMALE TA
            ON TA.NOME_TIPO_ANIMALE = A.NOME_TIPO_ANIMALE
        WHERE AAB.NUMERO_BLOCCO = P_NUMERO_BLOCCO
        AND AAB.NOME_STRUTTURA = P_NOME_STRUTTURA
        AND AAB.DATA_ALLOCAZIONE <= TRUNC(P_DATA_ORA)
        AND (AAB.DATA_DEALLOCAZIONE IS NULL OR AAB.DATA_DEALLOCAZIONE > TRUNC(P_DATA_ORA));

        RETURN NVL(V_TEMP, 293);
    END GET_BLOCK_TARGET_TEMP;

    FUNCTION GET_BLOCK_TARGET_HUMIDITY(
        P_NUMERO_BLOCCO IN BLOCCO_ANIMALE.NUMERO_BLOCCO%TYPE,
        P_NOME_STRUTTURA IN BLOCCO_ANIMALE.NOME_STRUTTURA%TYPE,
        P_DATA_ORA IN DATE
    ) RETURN NUMBER IS
        V_UMIDITA NUMBER;
    BEGIN
        SELECT AVG(TA.UMIDITA_IDEALE)
        INTO V_UMIDITA
        FROM ANIMALE_ALLOCATO_BLOCCO AAB
        JOIN ANIMALE A
            ON A.ETICHETTA = AAB.ETICHETTA_ANIMALE
        JOIN TIPO_ANIMALE TA
            ON TA.NOME_TIPO_ANIMALE = A.NOME_TIPO_ANIMALE
        WHERE AAB.NUMERO_BLOCCO = P_NUMERO_BLOCCO
        AND AAB.NOME_STRUTTURA = P_NOME_STRUTTURA
        AND AAB.DATA_ALLOCAZIONE <= TRUNC(P_DATA_ORA)
        AND (AAB.DATA_DEALLOCAZIONE IS NULL OR AAB.DATA_DEALLOCAZIONE > TRUNC(P_DATA_ORA));

        RETURN NVL(V_UMIDITA, 55);
    END GET_BLOCK_TARGET_HUMIDITY;

    FUNCTION GET_BLOCK_ANIMAL_COUNT(
        P_NUMERO_BLOCCO IN BLOCCO_ANIMALE.NUMERO_BLOCCO%TYPE,
        P_NOME_STRUTTURA IN BLOCCO_ANIMALE.NOME_STRUTTURA%TYPE,
        P_DATA_ORA IN DATE
    ) RETURN NUMBER IS
        V_COUNT NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO V_COUNT
        FROM ANIMALE_ALLOCATO_BLOCCO AAB
        WHERE AAB.NUMERO_BLOCCO = P_NUMERO_BLOCCO
        AND AAB.NOME_STRUTTURA = P_NOME_STRUTTURA
        AND AAB.DATA_ALLOCAZIONE <= TRUNC(P_DATA_ORA)
        AND (AAB.DATA_DEALLOCAZIONE IS NULL OR AAB.DATA_DEALLOCAZIONE > TRUNC(P_DATA_ORA));

        RETURN V_COUNT;
    END GET_BLOCK_ANIMAL_COUNT;

    FUNCTION GET_BLOCK_TEMPERATURE(
        P_NUMERO_BLOCCO IN BLOCCO_ANIMALE.NUMERO_BLOCCO%TYPE,
        P_NOME_STRUTTURA IN BLOCCO_ANIMALE.NOME_STRUTTURA%TYPE,
        P_DATA_ORA IN DATE
    ) RETURN NUMBER IS
        V_TARGET NUMBER;
        V_HOUR NUMBER := TO_NUMBER(TO_CHAR(P_DATA_ORA, 'HH24'));
    BEGIN
        V_TARGET := GET_BLOCK_TARGET_TEMP(P_NUMERO_BLOCCO, P_NOME_STRUTTURA, P_DATA_ORA);

        IF V_HOUR BETWEEN 12 AND 17 THEN
            RETURN V_TARGET + RANDOM_NUMBER(0.2, 1.0);
        ELSIF V_HOUR BETWEEN 0 AND 5 THEN
            RETURN V_TARGET + RANDOM_NUMBER(-1.0, -0.2);
        END IF;

        RETURN V_TARGET + RANDOM_NUMBER(-0.5, 0.5);
    END GET_BLOCK_TEMPERATURE;

    FUNCTION GET_BLOCK_HUMIDITY(
        P_NUMERO_BLOCCO IN BLOCCO_ANIMALE.NUMERO_BLOCCO%TYPE,
        P_NOME_STRUTTURA IN BLOCCO_ANIMALE.NOME_STRUTTURA%TYPE,
        P_DATA_ORA IN DATE
    ) RETURN NUMBER IS
        V_TARGET NUMBER;
        V_COUNT NUMBER;
    BEGIN
        V_TARGET := GET_BLOCK_TARGET_HUMIDITY(P_NUMERO_BLOCCO, P_NOME_STRUTTURA, P_DATA_ORA);
        V_COUNT := GET_BLOCK_ANIMAL_COUNT(P_NUMERO_BLOCCO, P_NOME_STRUTTURA, P_DATA_ORA);

        RETURN V_TARGET + LEAST(V_COUNT * 1.2, 8) + RANDOM_NUMBER(-4, 4);
    END GET_BLOCK_HUMIDITY;

    FUNCTION GET_BLOCK_ENERGY(
        P_NUMERO_BLOCCO IN BLOCCO_ANIMALE.NUMERO_BLOCCO%TYPE,
        P_NOME_STRUTTURA IN BLOCCO_ANIMALE.NOME_STRUTTURA%TYPE,
        P_DATA_ORA IN DATE,
        P_MINUTI_INTERVALLO IN NUMBER
    ) RETURN NUMBER IS
        V_COUNT NUMBER;
        V_KW NUMBER;
    BEGIN
        V_COUNT := GET_BLOCK_ANIMAL_COUNT(P_NUMERO_BLOCCO, P_NOME_STRUTTURA, P_DATA_ORA);
        V_KW := 0.15 + (V_COUNT * RANDOM_NUMBER(0.08, 0.18));

        IF TO_NUMBER(TO_CHAR(P_DATA_ORA, 'HH24')) BETWEEN 6 AND 21 THEN
            V_KW := V_KW + RANDOM_NUMBER(0.25, 0.7);
        ELSE
            V_KW := V_KW + RANDOM_NUMBER(0.05, 0.2);
        END IF;

        RETURN V_KW * (P_MINUTI_INTERVALLO / 60);
    END GET_BLOCK_ENERGY;

    PROCEDURE REGISTRA_MISURAZIONE(
        P_SERIALE IN REGISTRAZIONE_SENSORE.SERIALE%TYPE,
        P_DATA_SECONDI IN REGISTRAZIONE_SENSORE.DATA_SECONDI%TYPE,
        P_NOME_PRODUTTORE IN REGISTRAZIONE_SENSORE.NOME_PRODUTTORE%TYPE,
        P_NOME_MODELLO IN REGISTRAZIONE_SENSORE.NOME_MODELLO%TYPE,
        P_MISURAZIONE IN REGISTRAZIONE_SENSORE.MISURAZIONE%TYPE
    ) IS
    BEGIN
        MERGE INTO REGISTRAZIONE_SENSORE RS
        USING (
            SELECT
                P_SERIALE AS SERIALE,
                P_DATA_SECONDI AS DATA_SECONDI,
                P_NOME_PRODUTTORE AS NOME_PRODUTTORE,
                P_NOME_MODELLO AS NOME_MODELLO,
                P_MISURAZIONE AS MISURAZIONE
            FROM DUAL
        ) SRC
        ON (
            RS.SERIALE = SRC.SERIALE
            AND RS.DATA_SECONDI = SRC.DATA_SECONDI
            AND RS.NOME_PRODUTTORE = SRC.NOME_PRODUTTORE
            AND RS.NOME_MODELLO = SRC.NOME_MODELLO
        )
        WHEN MATCHED THEN
            UPDATE SET RS.MISURAZIONE = SRC.MISURAZIONE
        WHEN NOT MATCHED THEN
            INSERT (
                SERIALE,
                DATA_SECONDI,
                NOME_PRODUTTORE,
                NOME_MODELLO,
                MISURAZIONE
            ) VALUES (
                SRC.SERIALE,
                SRC.DATA_SECONDI,
                SRC.NOME_PRODUTTORE,
                SRC.NOME_MODELLO,
                SRC.MISURAZIONE
            );
    END REGISTRA_MISURAZIONE;

    FUNCTION APPLY_SENSOR_NOISE(
        P_VALUE IN NUMBER,
        P_GRANDEZZA IN TIPO_SENSORE.GRANDEZZA_MISURATA%TYPE,
        P_PRECISIONE IN TIPO_SENSORE.PRECISIONE%TYPE
    ) RETURN NUMBER IS
        V_NOISE NUMBER;
    BEGIN
        IF P_GRANDEZZA = 'ENERGIA' THEN
            V_NOISE := GREATEST(0.01, P_VALUE * 0.03 * P_PRECISIONE);
        ELSIF P_GRANDEZZA = 'TEMPERATURA' THEN
            V_NOISE := 0.2 * P_PRECISIONE;
        ELSIF P_GRANDEZZA = 'UMIDITA' THEN
            V_NOISE := 0.8 * P_PRECISIONE;
        ELSE
            V_NOISE := P_PRECISIONE;
        END IF;

        RETURN P_VALUE + RANDOM_NUMBER(-V_NOISE, V_NOISE);
    END APPLY_SENSOR_NOISE;

    PROCEDURE SIMULA_SENSORE(
        P_SERIALE IN SENSORE.SERIALE%TYPE,
        P_NOME_PRODUTTORE IN SENSORE.NOME_PRODUTTORE%TYPE,
        P_NOME_MODELLO IN SENSORE.NOME_MODELLO%TYPE,
        P_DATA_ORA IN DATE,
        P_MINUTI_INTERVALLO IN NUMBER DEFAULT 60
    ) IS
        V_GRANDEZZA TIPO_SENSORE.GRANDEZZA_MISURATA%TYPE;
        V_VALORE_MIN TIPO_SENSORE.VALORE_MIN%TYPE;
        V_VALORE_MAX TIPO_SENSORE.VALORE_MAX%TYPE;
        V_PRECISIONE TIPO_SENSORE.PRECISIONE%TYPE;
        V_NUMERO_BLOCCO BLOCCO_ANIMALE.NUMERO_BLOCCO%TYPE;
        V_CODICE_CELLA_IDR CELLA_IDROPONICA.CODICE_CELLA_IDR%TYPE;
        V_NOME_STRUTTURA STRUTTURA.NOME_STRUTTURA%TYPE;
        V_VALUE NUMBER;
    BEGIN
        IF NOT IS_SENSOR_ACTIVE(P_SERIALE, P_NOME_PRODUTTORE, P_NOME_MODELLO, P_DATA_ORA) THEN
            RETURN;
        END IF;

        SELECT
            GRANDEZZA_MISURATA,
            VALORE_MIN,
            VALORE_MAX,
            PRECISIONE,
            NUMERO_BLOCCO,
            CODICE_CELLA_IDR,
            NOME_STRUTTURA
        INTO
            V_GRANDEZZA,
            V_VALORE_MIN,
            V_VALORE_MAX,
            V_PRECISIONE,
            V_NUMERO_BLOCCO,
            V_CODICE_CELLA_IDR,
            V_NOME_STRUTTURA
        FROM (
            SELECT
                TS.GRANDEZZA_MISURATA,
                TS.VALORE_MIN,
                TS.VALORE_MAX,
                TS.PRECISIONE,
                CAST(NULL AS CHAR(4)) AS NUMERO_BLOCCO,
                CICS.CODICE_CELLA_IDR,
                CICS.NOME_STRUTTURA
            FROM SENSORE S
            JOIN TIPO_SENSORE TS
                ON TS.NOME_PRODUTTORE = S.NOME_PRODUTTORE
                AND TS.NOME_MODELLO = S.NOME_MODELLO
            JOIN CELLA_IDR_CONTIENE_SENSORE CICS
                ON CICS.SERIALE = S.SERIALE
                AND CICS.NOME_PRODUTTORE = S.NOME_PRODUTTORE
                AND CICS.NOME_MODELLO = S.NOME_MODELLO
            WHERE S.SERIALE = P_SERIALE
            AND S.NOME_PRODUTTORE = P_NOME_PRODUTTORE
            AND S.NOME_MODELLO = P_NOME_MODELLO
            AND CICS.DATA_MONTAGGIO <= TRUNC(P_DATA_ORA)
            AND (CICS.DATA_SMONTAGGIO IS NULL OR CICS.DATA_SMONTAGGIO > TRUNC(P_DATA_ORA))

            UNION ALL

            SELECT
                TS.GRANDEZZA_MISURATA,
                TS.VALORE_MIN,
                TS.VALORE_MAX,
                TS.PRECISIONE,
                BACS.NUMERO_BLOCCO,
                CAST(NULL AS CHAR(4)) AS CODICE_CELLA_IDR,
                BACS.NOME_STRUTTURA
            FROM SENSORE S
            JOIN TIPO_SENSORE TS
                ON TS.NOME_PRODUTTORE = S.NOME_PRODUTTORE
                AND TS.NOME_MODELLO = S.NOME_MODELLO
            JOIN BLOCCO_ANIMALE_CONTIENE_SENSORE BACS
                ON BACS.SERIALE = S.SERIALE
                AND BACS.NOME_PRODUTTORE = S.NOME_PRODUTTORE
                AND BACS.NOME_MODELLO = S.NOME_MODELLO
            WHERE S.SERIALE = P_SERIALE
            AND S.NOME_PRODUTTORE = P_NOME_PRODUTTORE
            AND S.NOME_MODELLO = P_NOME_MODELLO
            AND BACS.DATA_MONTAGGIO <= TRUNC(P_DATA_ORA)
            AND (BACS.DATA_SMONTAGGIO IS NULL OR BACS.DATA_SMONTAGGIO > TRUNC(P_DATA_ORA))
        )
        WHERE ROWNUM = 1;

        IF V_CODICE_CELLA_IDR IS NOT NULL THEN
            IF V_GRANDEZZA = 'TEMPERATURA' THEN
                V_VALUE := GET_CELL_TEMPERATURE(V_CODICE_CELLA_IDR, V_NOME_STRUTTURA, P_DATA_ORA);
            ELSIF V_GRANDEZZA = 'UMIDITA' THEN
                V_VALUE := GET_CELL_HUMIDITY(V_CODICE_CELLA_IDR, V_NOME_STRUTTURA, P_DATA_ORA);
            ELSIF V_GRANDEZZA = 'ENERGIA' THEN
                V_VALUE := GET_CELL_ENERGY(V_CODICE_CELLA_IDR, V_NOME_STRUTTURA, P_DATA_ORA, P_MINUTI_INTERVALLO);
            ELSE
                V_VALUE := RANDOM_NUMBER(V_VALORE_MIN, V_VALORE_MAX);
            END IF;
        ELSE
            IF V_GRANDEZZA = 'TEMPERATURA' THEN
                V_VALUE := GET_BLOCK_TEMPERATURE(V_NUMERO_BLOCCO, V_NOME_STRUTTURA, P_DATA_ORA);
            ELSIF V_GRANDEZZA = 'UMIDITA' THEN
                V_VALUE := GET_BLOCK_HUMIDITY(V_NUMERO_BLOCCO, V_NOME_STRUTTURA, P_DATA_ORA);
            ELSIF V_GRANDEZZA = 'ENERGIA' THEN
                V_VALUE := GET_BLOCK_ENERGY(V_NUMERO_BLOCCO, V_NOME_STRUTTURA, P_DATA_ORA, P_MINUTI_INTERVALLO);
            ELSE
                V_VALUE := RANDOM_NUMBER(V_VALORE_MIN, V_VALORE_MAX);
            END IF;
        END IF;

        V_VALUE := CLAMP(APPLY_SENSOR_NOISE(V_VALUE, V_GRANDEZZA, V_PRECISIONE), V_VALORE_MIN, V_VALORE_MAX);

        REGISTRA_MISURAZIONE(
            P_SERIALE,
            P_DATA_ORA,
            P_NOME_PRODUTTORE,
            P_NOME_MODELLO,
            ROUND(V_VALUE, 2)
        );
    END SIMULA_SENSORE;

    PROCEDURE SIMULA_GIORNO(
        P_DATA IN DATE,
        P_MINUTI_INTERVALLO IN NUMBER DEFAULT 60
    ) IS
        V_DATA_ORA DATE := TRUNC(P_DATA);
        V_FINE_GIORNO DATE := TRUNC(P_DATA) + 1;
        V_STEP NUMBER := GREATEST(P_MINUTI_INTERVALLO, 1) / 1440;
    BEGIN
        WHILE V_DATA_ORA < V_FINE_GIORNO LOOP
            FOR SENS IN (
                SELECT SERIALE, NOME_PRODUTTORE, NOME_MODELLO
                FROM SENSORE
            ) LOOP
                SIMULA_SENSORE(
                    SENS.SERIALE,
                    SENS.NOME_PRODUTTORE,
                    SENS.NOME_MODELLO,
                    V_DATA_ORA,
                    GREATEST(P_MINUTI_INTERVALLO, 1)
                );
            END LOOP;

            V_DATA_ORA := V_DATA_ORA + V_STEP;
        END LOOP;

        DBMS_OUTPUT.PUT_LINE('Sensor day simulated: ' || TO_CHAR(TRUNC(P_DATA), 'YYYY-MM-DD'));
    END SIMULA_GIORNO;

    PROCEDURE RUN_SIMULAZIONE(
        P_DATA_FINE IN DATE DEFAULT TRUNC(SYSDATE),
        P_MINUTI_INTERVALLO IN NUMBER DEFAULT 60
    ) IS
        V_CURRENT_DAY DATE := GET_SIM_START_DAY;
    BEGIN
        IF V_CURRENT_DAY IS NULL THEN
            DBMS_OUTPUT.PUT_LINE('No sensor simulation start day found');
            RETURN;
        END IF;

        WHILE V_CURRENT_DAY < TRUNC(P_DATA_FINE) LOOP
            SIMULA_GIORNO(V_CURRENT_DAY, GREATEST(P_MINUTI_INTERVALLO, 1));
            V_CURRENT_DAY := V_CURRENT_DAY + 1;
        END LOOP;

        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE;
    END RUN_SIMULAZIONE;
END SIMULATORE_SENSORI;
/
