--NOME_PRODUTTORE, NOME_MODELLO, VALORE_MIN, VALORE_MAX, PRECISIONE, GRANDEZZA_MISURATA, UNITA_MISURA, FREQUENZA_RILEVAMENTO_HZ
INSERT INTO TIPO_SENSORE VALUES ('MESA', 'ENERGY-SENSOR-V3', 0.0, 5000.0, 1, 'ENERGIA', 'kWh', 1);
INSERT INTO TIPO_SENSORE VALUES ('SpaceTech', 'HUM-SENSOR-V1', 0.0, 100.0, 1, 'UMIDITA', '%', 1);
INSERT INTO TIPO_SENSORE VALUES ('Cainiao', 'TEMP-SENSOR-V2', 240.0, 330.0, 1, 'TEMPERATURA', 'K', 1);
COMMIT;
