--SERIALE, NOME_PRODUTTORE, NOME_MODELLO

--CELLE IDROPONICHE
INSERT INTO SENSORE VALUES ('SENS-000A-SA-ENERGY-01', 'MESA', 'ENERGY-SENSOR-V3');
INSERT INTO SENSORE VALUES ('SENS-000A-SA-HUM-01', 'SpaceTech', 'HUM-SENSOR-V1');
INSERT INTO SENSORE VALUES ('SENS-000A-SA-TEMP-01', 'Cainiao', 'TEMP-SENSOR-V2');

INSERT INTO SENSORE VALUES ('SENS-000B-SA-ENERGY-01', 'MESA', 'ENERGY-SENSOR-V3');
INSERT INTO SENSORE VALUES ('SENS-000B-SA-HUM-01', 'SpaceTech', 'HUM-SENSOR-V1');
INSERT INTO SENSORE VALUES ('SENS-000B-SA-TEMP-01', 'Cainiao', 'TEMP-SENSOR-V2');

INSERT INTO SENSORE VALUES ('SENS-000A-SA2-ENERGY-01', 'MESA', 'ENERGY-SENSOR-V3');
INSERT INTO SENSORE VALUES ('SENS-000A-SA2-HUM-01', 'SpaceTech', 'HUM-SENSOR-V1');
INSERT INTO SENSORE VALUES ('SENS-000A-SA2-TEMP-01', 'Cainiao', 'TEMP-SENSOR-V2');

INSERT INTO SENSORE VALUES ('SENS-000B-SA2-ENERGY-01', 'MESA', 'ENERGY-SENSOR-V3');
INSERT INTO SENSORE VALUES ('SENS-000B-SA2-HUM-01', 'SpaceTech', 'HUM-SENSOR-V1');
INSERT INTO SENSORE VALUES ('SENS-000B-SA2-TEMP-01', 'Cainiao', 'TEMP-SENSOR-V2');

INSERT INTO SENSORE VALUES ('SENS-000C-SA2-ENERGY-01', 'MESA', 'ENERGY-SENSOR-V3');
INSERT INTO SENSORE VALUES ('SENS-000C-SA2-HUM-01', 'SpaceTech', 'HUM-SENSOR-V1');
INSERT INTO SENSORE VALUES ('SENS-000C-SA2-TEMP-01', 'Cainiao', 'TEMP-SENSOR-V2');


--BLOCCHI ANIMALI
INSERT INTO SENSORE VALUES ('SENS-BLOCK-0001-SZ-ENERGY-01', 'MESA', 'ENERGY-SENSOR-V3');
INSERT INTO SENSORE VALUES ('SENS-BLOCK-0001-SZ-HUM-01', 'SpaceTech', 'HUM-SENSOR-V1');
INSERT INTO SENSORE VALUES ('SENS-BLOCK-0001-SZ-TEMP-01', 'Cainiao', 'TEMP-SENSOR-V2');

INSERT INTO SENSORE VALUES ('SENS-BLOCK-0002-SZ-ENERGY-01', 'MESA', 'ENERGY-SENSOR-V3');
INSERT INTO SENSORE VALUES ('SENS-BLOCK-0002-SZ-HUM-01', 'SpaceTech', 'HUM-SENSOR-V1');
INSERT INTO SENSORE VALUES ('SENS-BLOCK-0002-SZ-TEMP-01', 'Cainiao', 'TEMP-SENSOR-V2');

INSERT INTO SENSORE VALUES ('SENS-BLOCK-0003-SZ-ENERGY-01', 'MESA', 'ENERGY-SENSOR-V3');
INSERT INTO SENSORE VALUES ('SENS-BLOCK-0003-SZ-HUM-01', 'SpaceTech', 'HUM-SENSOR-V1');
INSERT INTO SENSORE VALUES ('SENS-BLOCK-0003-SZ-TEMP-01', 'Cainiao', 'TEMP-SENSOR-V2');

COMMIT;
