--SERIALE, NOME_PRODUTTORE, NOME_MODELLO, NUMERO_BLOCCO, NUMERO_CELLA_IDR, NOME_STRUTTURA

--CELLE IDROPONICHE
INSERT INTO SENSORE VALUES ('SENS-000A-SA-ENERGY-01', 'MESA', 'ENERGY-SENSOR-V3', NULL, '000A', 'Struttura Agricola');
INSERT INTO SENSORE VALUES ('SENS-000A-SA-HUM-01', 'SpaceTech', 'HUM-SENSOR-V1', NULL, '000A', 'Struttura Agricola');
INSERT INTO SENSORE VALUES ('SENS-000A-SA-TEMP-01', 'Cainiao', 'TEMP-SENSOR-V2', NULL, '000A', 'Struttura Agricola');

INSERT INTO SENSORE VALUES ('SENS-000B-SA-ENERGY-01', 'MESA', 'ENERGY-SENSOR-V3', NULL, '000B', 'Struttura Agricola');
INSERT INTO SENSORE VALUES ('SENS-000B-SA-HUM-01', 'SpaceTech', 'HUM-SENSOR-V1', NULL, '000B', 'Struttura Agricola');
INSERT INTO SENSORE VALUES ('SENS-000B-SA-TEMP-01', 'Cainiao', 'TEMP-SENSOR-V2', NULL, '000B', 'Struttura Agricola');

INSERT INTO SENSORE VALUES ('SENS-000A-SA2-ENERGY-01', 'MESA', 'ENERGY-SENSOR-V3', NULL, '000A', 'Struttura Agricola II');
INSERT INTO SENSORE VALUES ('SENS-000A-SA2-HUM-01', 'SpaceTech', 'HUM-SENSOR-V1', NULL, '000A', 'Struttura Agricola II');
INSERT INTO SENSORE VALUES ('SENS-000A-SA2-TEMP-01', 'Cainiao', 'TEMP-SENSOR-V2', NULL, '000A', 'Struttura Agricola II');

INSERT INTO SENSORE VALUES ('SENS-000B-SA2-ENERGY-01', 'MESA', 'ENERGY-SENSOR-V3', NULL, '000B', 'Struttura Agricola II');
INSERT INTO SENSORE VALUES ('SENS-000B-SA2-HUM-01', 'SpaceTech', 'HUM-SENSOR-V1', NULL, '000B', 'Struttura Agricola II');
INSERT INTO SENSORE VALUES ('SENS-000B-SA2-TEMP-01', 'Cainiao', 'TEMP-SENSOR-V2', NULL, '000B', 'Struttura Agricola II');

INSERT INTO SENSORE VALUES ('SENS-000C-SA2-ENERGY-01', 'MESA', 'ENERGY-SENSOR-V3', NULL, '000C', 'Struttura Agricola II');
INSERT INTO SENSORE VALUES ('SENS-000C-SA2-HUM-01', 'SpaceTech', 'HUM-SENSOR-V1', NULL, '000C', 'Struttura Agricola II');
INSERT INTO SENSORE VALUES ('SENS-000C-SA2-TEMP-01', 'Cainiao', 'TEMP-SENSOR-V2', NULL, '000C', 'Struttura Agricola II');


--BLOCCHI ANIMALI
INSERT INTO SENSORE VALUES ('SENS-BLOCK-0001-SZ-ENERGY-01', 'MESA', 'ENERGY-SENSOR-V3', '0001', NULL, 'Struttura Zootecnica');
INSERT INTO SENSORE VALUES ('SENS-BLOCK-0001-SZ-HUM-01', 'SpaceTech', 'HUM-SENSOR-V1', '0001', NULL, 'Struttura Zootecnica');
INSERT INTO SENSORE VALUES ('SENS-BLOCK-0001-SZ-TEMP-01', 'Cainiao', 'TEMP-SENSOR-V2', '0001', NULL, 'Struttura Zootecnica');

INSERT INTO SENSORE VALUES ('SENS-BLOCK-0002-SZ-ENERGY-01', 'MESA', 'ENERGY-SENSOR-V3', '0002', NULL, 'Struttura Zootecnica');
INSERT INTO SENSORE VALUES ('SENS-BLOCK-0002-SZ-HUM-01', 'SpaceTech', 'HUM-SENSOR-V1', '0002', NULL, 'Struttura Zootecnica');
INSERT INTO SENSORE VALUES ('SENS-BLOCK-0002-SZ-TEMP-01', 'Cainiao', 'TEMP-SENSOR-V2', '0002', NULL, 'Struttura Zootecnica');

INSERT INTO SENSORE VALUES ('SENS-BLOCK-0003-SZ-ENERGY-01', 'MESA', 'ENERGY-SENSOR-V3', '0003', NULL, 'Struttura Zootecnica');
INSERT INTO SENSORE VALUES ('SENS-BLOCK-0003-SZ-HUM-01', 'SpaceTech', 'HUM-SENSOR-V1', '0003', NULL, 'Struttura Zootecnica');
INSERT INTO SENSORE VALUES ('SENS-BLOCK-0003-SZ-TEMP-01', 'Cainiao', 'TEMP-SENSOR-V2', '0003', NULL, 'Struttura Zootecnica');

COMMIT;
