--NOME_TIPO_ANIMALE, SPECIE, VITA_MEDIA_ANNI, MODALITA_RIPRODUZIONE, GIORNI_GESTAZIONE, UMIDITA_IDEALE, SPAZIO_MINIMO_MQ, TEMPERATURA_IDEALE
INSERT INTO TIPO_ANIMALE VALUES ('Bovino', 'Bos taurus', 20, 'VIVIPARA', 283, 60, 12.00, 291.15);
INSERT INTO TIPO_ANIMALE VALUES ('Capra', 'Capra hircus', 15, 'VIVIPARA', 150, 55, 3.00, 291.15);
INSERT INTO TIPO_ANIMALE VALUES ('Gallina', 'Gallus gallus domesticus', 8, 'OVIPARA', 21, 60, 0.30, 295.15);

COMMIT;
