--NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE, LIVELLO_BIOSICUREZZA_MINIMO, ETA_MINIMA_MESI
INSERT INTO STADIO_CRESCITA VALUES ('Vitello', 'Bovino', 'ALTO', 0);
INSERT INTO STADIO_CRESCITA VALUES ('Giovane', 'Bovino', 'MEDIO', 12);
INSERT INTO STADIO_CRESCITA VALUES ('Adulto', 'Bovino', 'BASSO', 24);

INSERT INTO STADIO_CRESCITA VALUES ('Capretto', 'Capra', 'ALTO', 0);
INSERT INTO STADIO_CRESCITA VALUES ('Giovane', 'Capra', 'MEDIO', 8);
INSERT INTO STADIO_CRESCITA VALUES ('Adulto', 'Capra', 'BASSO', 18);

INSERT INTO STADIO_CRESCITA VALUES ('Pulcino', 'Gallina', 'ALTO', 0);
INSERT INTO STADIO_CRESCITA VALUES ('Giovane', 'Gallina', 'MEDIO', 2);
INSERT INTO STADIO_CRESCITA VALUES ('Adulto', 'Gallina', 'BASSO', 12);

INSERT INTO STADIO_CRESCITA VALUES ('Cucciolo', 'Coniglio', 'ALTO', 0);
INSERT INTO STADIO_CRESCITA VALUES ('Giovane', 'Coniglio', 'MEDIO', 3);
INSERT INTO STADIO_CRESCITA VALUES ('Adulto', 'Coniglio', 'BASSO', 6);

COMMIT;
