--NOME_DIETA, OBIETTIVO_DIETA

INSERT INTO DIETA_ANIMALE VALUES ('Dieta Bovino Vitello', 'CRESCITA');
INSERT INTO DIETA_ANIMALE VALUES ('Dieta Bovino Giovane', 'CRESCITA');
INSERT INTO DIETA_ANIMALE VALUES ('Dieta Bovino Adulto', 'MANTENIMENTO');
INSERT INTO DIETA_ANIMALE VALUES ('Dieta Bovino Adulto V2', 'RIPRODUZIONE');

INSERT INTO DIETA_ANIMALE VALUES ('Dieta Capra Capretto', 'CRESCITA');
INSERT INTO DIETA_ANIMALE VALUES ('Dieta Capra Giovane', 'CRESCITA');
INSERT INTO DIETA_ANIMALE VALUES ('Dieta Capra Adulto', 'MANTENIMENTO');

INSERT INTO DIETA_ANIMALE VALUES ('Dieta Gallina Pulcino', 'CRESCITA');
INSERT INTO DIETA_ANIMALE VALUES ('Dieta Gallina Giovane', 'CRESCITA');
INSERT INTO DIETA_ANIMALE VALUES ('Dieta Gallina Adulto', 'MANTENIMENTO');

INSERT INTO DIETA_ANIMALE VALUES ('Dieta Coniglio Cucciolo', 'CRESCITA');
INSERT INTO DIETA_ANIMALE VALUES ('Dieta Coniglio Giovane', 'CRESCITA');
INSERT INTO DIETA_ANIMALE VALUES ('Dieta Coniglio Giovane V2', 'CRESCITA');
INSERT INTO DIETA_ANIMALE VALUES ('Dieta Coniglio Adulto', 'MANTENIMENTO');

COMMIT;
