CREATE TABLE TIPO_ANIMALE(
    NOME_TIPO_ANIMALE VARCHAR2(30),
    SPECIE VARCHAR2(30),
    VITA_MEDIA_ANNI NUMBER(5,2),
    MODALITA_RIPRODUZIONE VARCHAR2(15),
    GIORNI_GESTAZIONE NUMBER(3,0),
    UMIDITA_IDEALE NUMBER(3,0) --UMIDITA IN PERCENTUALE
        CONSTRAINT NN_TIPO_ANIMALE_UMIDITA NOT NULL,
    SPAZIO_MINIMO_MQ NUMBER(2,2)
        CONSTRAINT NN_TIPO_ANIMALE_SPAZIO_MINIMO NOT NULL,
    TEMPERATURA_IDEALE NUMBER(3,0) --TEMPERATURA IN KELVIN
        CONSTRAINT NN_TIPO_ANIMALE_TEMPERATURA NOT NULL,

    --PK
    CONSTRAINT PK_TIPO_ANIMALE PRIMARY KEY(NOME_TIPO_ANIMALE),

    --CHECK
    CONSTRAINT CK_TIPO_ANIMALE_VITA_MEDIA_ANNI
        CHECK (VITA_MEDIA_ANNI > 0),
    
    CONSTRAINT CK_TIPO_ANIMALE_MODALITA_RIPRODUZIONE
        CHECK (MODALITA_RIPRODUZIONE IN (
                'OVIPARA', --DEPONE UOVA
                'VIVIPARA', --PARTORISCE FIGLI VIVI
                'OVOVIVIPARA',  --UOVA SI SCHIUDONO ALL'INTERNO DEL CORPO MATERNO
                'PARTENOGENESI', --RIPRODUZIONE ASESSUATA
                'ASESSUATA' --RIPRODUZIONE SENZA FECONDAZIONE
            )),
    
    CONSTRAINT CK_TIPO_ANIMALE_GIORNI_GESTAZIONE
        CHECK (GIORNI_GESTAZIONE > 0),
    
    CONSTRAINT CK_TIPO_ANIMALE_UMIDITA
        CHECK (UMIDITA_IDEALE >= 0 AND UMIDITA_IDEALE <= 100),

    CONSTRAINT CK_TIPO_ANIMALE_SPAZIO_MINIMO
        CHECK (SPAZIO_MINIMO_MQ >0),
    
    CONSTRAINT CK_TIPO_ANIMALE_TEMPERATURA
        CHECK (TEMPERATURA_IDEALE > 230 AND TEMPERATURA_IDEALE < 320) --TRA -43°C E 47°C
);