CREATE TABLE ANIMALE(
    ETICHETTA CHAR(10),
    DATA_USCITA DATE,
    ETICHETTA_GENITORE CHAR(10),
    SESSO CHAR(1),
    MESE_NASCITA NUMBER(2,0) 
        CONSTRAINT NN_ANIMALE_MESE_NASCITA NOT NULL,
    ANNO_NASCITA NUMBER(4,0) 
        CONSTRAINT NN_ANIMALE_ANNO_NASCITA NOT NULL,
    DATA_INGRESSO DATE 
        CONSTRAINT NN_ANIMALE_DATA_INGRESSO NOT NULL,
    NOME_TIPO_ANIMALE VARCHAR2(30) 
        CONSTRAINT NN_ANIMALE_FK_TIPO_ANIMALE NOT NULL,

    --PK
    CONSTRAINT PK_ANIMALE PRIMARY KEY (ETICHETTA),

    --FK
    CONSTRAINT FK_ANIMALE_TIPO_ANIMALE 
        FOREIGN KEY (NOME_TIPO_ANIMALE)
        REFERENCES TIPO_ANIMALE (NOME_TIPO_ANIMALE),

    CONSTRAINT FK_ANIMALE_GENITORE
        FOREIGN KEY (ETICHETTA_GENITORE)
        REFERENCES ANIMALE (ETICHETTA),
    
    --CHECK
    CONSTRAINT CK_ANIMALE_ETICHETTA
        CHECK (REGEXP_LIKE(ETICHETTA, '^[0-9]+$')), --ETICHETTA NUMERICA

    CONSTRAINT CK_ANIMALE_SESSO 
        CHECK (SESSO IN ('M', 'F', 'I')), --MASCHIO, FEMMINA, INDETERMINATO (BIOLOGICAMENTE IMPOSSIBILE)

    CONSTRAINT CK_ANIMALE_ANNO_NASCITA 
        CHECK (ANNO_NASCITA >= 1900),
    
    CONSTRAINT CK_ANIMALE_MESE_NASCITA
        CHECK (MESE_NASCITA >= 1 AND MESE_NASCITA <= 12),

    CONSTRAINT CK_ANIMALE_DATA_INGRESSO
        CHECK (DATA_INGRESSO >= DATE '2026-01-01'),
    
    CONSTRAINT CK_ANIMALE_DATA_USCITA
        CHECK (DATA_USCITA IS NULL OR DATA_USCITA >= DATA_INGRESSO)
);