CREATE TABLE STADIO_CRESCITA(
    NOME_STADIO_CRESCITA VARCHAR2(30), 
    NOME_TIPO_ANIMALE VARCHAR2(30),
    LIVELLO_BIOSICUREZZA_MINIMO VARCHAR2(15)
        CONSTRAINT NN_STADIO_CRESCITA_LIVELLO_BIOSICUREZZA_MINIMO NOT NULL,
    ETA_MINIMA_MESI NUMBER(4,0)
        CONSTRAINT NN_STADIO_CRESCITA_ETA_MINIMA NOT NULL,
    
    
    --PK
    CONSTRAINT PK_STADIO_CRESCITA PRIMARY KEY (NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE),

    --FK
    CONSTRAINT FK_STADIO_CRESCITA_TIPO_ANIMALE
        FOREIGN KEY (NOME_TIPO_ANIMALE)
        REFERENCES TIPO_ANIMALE (NOME_TIPO_ANIMALE),
    
    --CHECK
    CONSTRAINT CK_STADIO_CRESCITA_LIVELLO_BIOSICUREZZA_MINIMO
        CHECK (LIVELLO_BIOSICUREZZA_MINIMO IN (
                'BASSO',
                'MEDIO',
                'ALTO'
            )),

    CONSTRAINT CK_STADIO_CRESCITA_ETA_MINIMA
        CHECK (ETA_MINIMA_MESI >= 0)
);