CREATE TABLE DIETA_ANIMALE( --DIETA GIORNALIERA
    NOME_DIETA VARCHAR2(30),
    OBIETTIVO_DIETA VARCHAR2(30)
        CONSTRAINT NN_DIETA_ANIMALE_OBIETTIVO NOT NULL,

    --PK
    CONSTRAINT PK_DIETA_ANIMALE PRIMARY KEY (NOME_DIETA),

    --CHECK
    CONSTRAINT CK_DIETA_ANIMALE_OBIETTIVO
        CHECK (OBIETTIVO_DIETA IN (
                'MANTENIMENTO',
                'CRESCITA',
                'RIPRODUZIONE',
                'INGRASSO',
                'DIMAGRIMENTO'
        ))
);