CREATE TABLE VACCINO(
    NOME_VACCINO VARCHAR2(30), --PK
    NOME_TIPO_ANIMALE VARCHAR2(30), --PK/FK
    NOME_STADIO_CRESCITA VARCHAR2(30), --PK/FK
    NOME_VACCINO_PROPEDEUTICO VARCHAR2(30), --FK
    NOME_STADIO_CRESCITA_PROPEDEUTICO VARCHAR2(30), --FK
    NOME_TIPO_ANIMALE_PROPEDEUTICO VARCHAR2(30), --FK
    IS_VACCINO_OBBLIGATORIO NUMBER(1,0),
    ETA_MINIMA_MESI NUMBER(4,0)
        CONSTRAINT NN_TIPO_VACCINO_ETA_MINIMA NOT NULL,
    DOSE_ML NUMBER(4,2)
        CONSTRAINT NN_TIPO_VACCINO_DOSE NOT NULL,

    --PK
    CONSTRAINT PK_VACCINO 
        PRIMARY KEY (NOME_VACCINO, NOME_TIPO_ANIMALE, NOME_STADIO_CRESCITA),
    
    --FK
    CONSTRAINT FK_VACCINO_PROPEDEUTICO
        FOREIGN KEY (NOME_VACCINO_PROPEDEUTICO, NOME_TIPO_ANIMALE_PROPEDEUTICO, NOME_STADIO_CRESCITA_PROPEDEUTICO)
        REFERENCES VACCINO (NOME_VACCINO, NOME_TIPO_ANIMALE, NOME_STADIO_CRESCITA),

    CONSTRAINT FK_VACCINO_STADIO_CRESCITA
        FOREIGN KEY (NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE)
        REFERENCES STADIO_CRESCITA (NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE),

    --CHECK
    CONSTRAINT CK_VACCINO_IS_OBBLIGATORIO
        CHECK (IS_VACCINO_OBBLIGATORIO IN (1, 0)),

    CONSTRAINT CK_VACCINO_ETA_MINIMA 
        CHECK (ETA_MINIMA_MESI >= 0),
    
    CONSTRAINT CK_VACCINO_DOSE
        CHECK (DOSE_ML > 0)
);