CREATE TABLE PRESCRIZIONE_ANIMALE(
    ETICHETTA_ANIMALE CHAR(10),
    DATA_VISITA DATE,
    NOME_PRODOTTO VARCHAR(60)
        CONSTRAINT NN_PRESCRIZIONE_ANIMALE_NOME_PRODOTTO NOT NULL,
    DURATA_GIORNI NUMBER(4,0)
        CONSTRAINT NN_PRESCRIZIONE_ANIMALE_DURATA_GIORNI NOT NULL,
    QUANTITA_GIORNALIERA NUMBER(6,2)
        CONSTRAINT NN_PRESCRIZIONE_ANIMALE_QUANTITA_GIORNALIERA NOT NULL,
    
    --PK
    CONSTRAINT PK_PRESCRIZIONE_ANIMALE 
        PRIMARY KEY(ETICHETTA_ANIMALE, DATA_VISITA, NOME_PRODOTTO),

    --FK
    CONSTRAINT FK_PRESCRIZIONE_ANIMALE_VISITA_VETERINARIA
        FOREIGN KEY(ETICHETTA_ANIMALE, DATA_VISITA)
        REFERENCES VISITA_VETERINARIA (ETICHETTA_ANIMALE, DATA_VISITA),

    CONSTRAINT FK_PRESCRIZIONE_ANIMALE_PRODOTTO
        FOREIGN KEY(NOME_PRODOTTO)
        REFERENCES TIPO_PRODOTTO (NOME_PRODOTTO),

    --CHECK
    CONSTRAINT CK_PRESCRIZIONE_DURATA_GIORNI
        CHECK(DURATA_GIORNI > 0),
    
    CONSTRAINT CK_PRESCRIZIONE_ANIMALE_QUANTITA_GIORNALIERA
        CHECK(QUANTITA_GIORNALIERA > 0)
);
