CREATE TABLE VISITA_VETERINARIA(
    ETICHETTA_ANIMALE CHAR(10),
    DATA_VISITA DATE,
    STATO_SALUTE VARCHAR2(10)
        CONSTRAINT NN_VISITA_VETERINARIA_STATO_SALUTE NOT NULL,
    TIPO_VISITA VARCHAR(20)
        CONSTRAINT NN_VISITA_VETERINARIA_TIPO_VISITA NOT NULL,
    
    --PK
    CONSTRAINT PK_VISITA_VETERINARIA
        PRIMARY KEY (ETICHETTA_ANIMALE, DATA_VISITA),

    --FK
    CONSTRAINT FK_VISITA_VETERINARIA_ANIMALE
        FOREIGN KEY (ETICHETTA_ANIMALE)
        REFERENCES ANIMALE (ETICHETTA),

    --CHECK
    CONSTRAINT CK_VISITA_VETERINARIA_STATO_SALUTE
        CHECK (STATO_SALUTE IN(
                'BUONO',
                'DISCRETO',
                'CRITICO'
        )),

    CONSTRAINT CK_VISITA_VETERINARIA_TIPO_VISITA
        CHECK (TIPO_VISITA IN(
                'ROUTINE',
                'EMERGENZA',
                'GESTAZIONE',
                'INGRESSO',
                'BIOSICUREZZA'
        ))
);