CREATE TABLE PRESCRIZIONE_ANIMALE(
    NOME_FARMACO VARCHAR2(30),
    ETICHETTA_ANIMALE CHAR(10),
    DATA_VISITA DATE,
    UNITA_MISURA VARCHAR(30)
        CONSTRAINT NN_PRESCRIZIONE_ANIMALE_UNITA_MISURA NOT NULL,
    DURATA_GIORNI NUMBER(4,0)
        CONSTRAINT NN_PRESCRIZIONE_ANIMALE_DURATA_GIORNI NOT NULL,
    QUANTITA_GIORNALIERA NUMBER(6,2)
        CONSTRAINT NN_PRESCRIZIONE_ANIMALE_QUANTITA_GIORNALIERA NOT NULL,
    
    --PK
    CONSTRAINT PK_PRESCRIZIONE_ANIMALE 
        PRIMARY KEY(NOME_FARMACO, ETICHETTA_ANIMALE, DATA_VISITA),

    --FK
    CONSTRAINT FK_PRESCRIZIONE_ANIMALE_VISITA_VETERINARIA
        FOREIGN KEY(ETICHETTA_ANIMALE, DATA_VISITA)
        REFERENCES VISITA_VETERINARIA (ETICHETTA_ANIMALE, DATA_VISITA),

    --CHECK
    CONSTRAINT CK_PRESCRIZIONE_DURATA_GIORNI
        CHECK(DURATA_GIORNI > 0),
    
    CONSTRAINT CK_PRESCRIZIONE_ANIMALE_QUANTITA_GIORNALIERA
        CHECK(QUANTITA_GIORNALIERA > 0)
);