CREATE TABLE PRODUZIONE_ANIMALE(
    DATA_PRODUZIONE DATE,
    NUMERO_BLOCCO CHAR(4),
    NOME_STRUTTURA VARCHAR2(30),
    CODICE_AREA CHAR(4),
    NOME_PRODOTTO VARCHAR2(30),
    QUANTITA NUMBER(6,2)
        CONSTRAINT NN_PRODUZIONE_ANIMALE_QUANTITA NOT NULL,
    
    --PK
    CONSTRAINT PK_PRODUZIONE_ANIMALE
        PRIMARY KEY (
                DATA_PRODUZIONE,
                NUMERO_BLOCCO,
                NOME_STRUTTURA, 
                CODICE_AREA,
                NOME_PRODOTTO
            ),
    
    --FK 
    CONSTRAINT FK_PRODUZIONE_ANIMALE_PRODOTTO
        FOREIGN KEY (NOME_PRODOTTO)
        REFERENCES TIPO_PRODOTTO (NOME_PRODOTTO),
    
    --CHECK
    CONSTRAINT CK_PRODUZIONE_ANIMALE_QUANTITA
        CHECK (QUANTITA > 0)
);