CREATE TABLE STADIO_CRESCITA_PREVEDE_DIETA(
    NOME_STADIO_CRESCITA VARCHAR2(30),
    NOME_TIPO_ANIMALE VARCHAR2(30),
    NOME_DIETA VARCHAR2(30),
    DATA_INIZIO DATE,
    DATA_FINE DATE,

    --PK
    CONSTRAINT PK_STADIO_CRESCITA_PREVEDE_DIETA 
        PRIMARY KEY (NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE, NOME_DIETA, DATA_INIZIO),
    
    --FK
    CONSTRAINT FK_SCPD_STADIO_CRESCITA
        FOREIGN KEY (NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE)
        REFERENCES STADIO_CRESCITA (NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE),

    CONSTRAINT FK_SCPD_DIETA_ANIMALE
        FOREIGN KEY (NOME_DIETA)
        REFERENCES DIETA_ANIMALE (NOME_DIETA),

    --CHECK
    CONSTRAINT CK_SCPD_DATA_INIZIO
        CHECK (DATA_INIZIO >= DATE '2026-01-01')
);