CREATE TABLE DIETA_COMPRENDE_PRODOTTO(
    NOME_PRODOTTO VARCHAR2(30),
    NOME_DIETA VARCHAR2(30),
    QUANTITA_GRAMMI NUMBER(7,2)
        CONSTRAINT NN_DCP_QUANTITA_GRAMMI NOT NULL,

    --PK 
    CONSTRAINT PK_DIETA_COMPRENDE_PRODOTTO 
        PRIMARY KEY(NOME_PRODOTTO, NOME_DIETA),

    --FK
    CONSTRAINT FK_DCP_PRODOTTO
        FOREIGN KEY (NOME_PRODOTTO)
        REFERENCES TIPO_PRODOTTO (NOME_PRODOTTO),

    CONSTRAINT FK_DCP_DIETA_ANIMALE
        FOREIGN KEY (NOME_DIETA)
        REFERENCES DIETA_ANIMALE (NOME_DIETA),

    --CHECK 
    CONSTRAINT CK_DCP_QUANTITA_GRAMMI
        CHECK(QUANTITA_GRAMMI > 0)
);