CREATE TABLE ANIMALE_ALLERGICO_SOSTANZA(
    ETICHETTA_ANIMALE CHAR(10),
    NOME_SOSTANZA VARCHAR2(30),
    DATA_ATTESTAZIONE DATE,

    --PK
    CONSTRAINT PK_AAS
        PRIMARY KEY(ETICHETTA_ANIMALE, NOME_SOSTANZA),
    
    --FK
    CONSTRAINT FK_AAS_ANIMALE
        FOREIGN KEY (ETICHETTA_ANIMALE)
        REFERENCES ANIMALE (ETICHETTA),

    CONSTRAINT FK_AAS_SOSTANZA
        FOREIGN KEY (NOME_SOSTANZA)
        REFERENCES SOSTANZA (NOME_SOSTANZA)
);