CREATE TABLE ANIMALE_PREVEDE_DIETA_SPECIALE(
    ETICHETTA_ANIMALE CHAR(10),
    NOME_DIETA VARCHAR2(30),
    DATA_INIZIO DATE,
    DATA_FINE DATE,

    --PK
    CONSTRAINT PK_APDS
        PRIMARY KEY(ETICHETTA_ANIMALE, NOME_DIETA, DATA_INIZIO),

    --FK
    CONSTRAINT FK_APDS_ANIMALE
        FOREIGN KEY (ETICHETTA_ANIMALE)
        REFERENCES ANIMALE (ETICHETTA),

    CONSTRAINT FK_APDS_DIETA_ANIMALE
        FOREIGN KEY (NOME_DIETA)
        REFERENCES DIETA_ANIMALE (NOME_DIETA),
    
    --CHECK
    CONSTRAINT CK_APDS_DATA_INIZIO
        CHECK (DATA_INIZIO >= DATE '2026-01-01')
);