CREATE TABLE PRODOTTO_DA_STADIO_CRESCITA(
    NOME_PRODOTTO VARCHAR2(30),
    NOME_STADIO_CRESCITA VARCHAR2(30), 
    NOME_TIPO_ANIMALE VARCHAR2(30),

    --PK
    CONSTRAINT PK_PDSC
        PRIMARY KEY (NOME_PRODOTTO, NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE),

    --FK
    CONSTRAINT FK_PDSC_TIPO_PRODOTTO
        FOREIGN KEY (NOME_PRODOTTO)
        REFERENCES TIPO_PRODOTTO (NOME_PRODOTTO),

    CONSTRAINT FK_PDSC_STADIO_CRESCITA
        FOREIGN KEY (NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE)
        REFERENCES STADIO_CRESCITA (NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE)
);