CREATE TABLE ANIMALE_ALLOCATO_BLOCCO(
    NUMERO_BLOCCO CHAR(4),
    NOME_STRUTTURA VARCHAR2(30),
    CODICE_AREA CHAR(4),
    ETICHETTA_ANIMALE CHAR(10),
    DATA_ALLOCAZIONE DATE,
    DATA_DEALLOCAIONE DATE,

    --PK
    CONSTRAINT PK_ANIMALE_ALLOCATO_BLOCCO
        PRIMARY KEY (NUMERO_BLOCCO, NOME_STRUTTURA, CODICE_AREA, ETICHETTA_ANIMALE, DATA_ALLOCAZIONE),

    --FK
    CONSTRAINT FK_ANIMALE_ALLOCATO_BLOCCO_ANIMALE
        FOREIGN KEY (ETICHETTA_ANIMALE)
        REFERENCES ANIMALE (ETICHETTA),

    CONSTRAINT FK_ANIMALE_ALLOCATO_BLOCCO_TO_BLOCCO
        FOREIGN KEY (NUMERO_BLOCCO, CODICE_AREA, NOME_STRUTTURA)
        REFERENCES BLOCCO_ANIMALE (NUMERO_BLOCCO, CODICE_AREA, NOME_STRUTTURA)
);