CREATE ROLE R_GESTIONE_PRODOTTI;


GRANT INSERT ON TIPO_PRODOTTO TO R_GESTIONE_PRODOTTI;
GRANT INSERT ON UNITA_DI_MISURA TO R_GESTIONE_PRODOTTI;

GRANT SELECT ON TIPO_PRODOTTO TO R_GESTIONE_PRODOTTI;
GRANT SELECT ON UNITA_DI_MISURA TO R_GESTIONE_PRODOTTI;