CREATE ROLE R_GESTIONE_STRUTTURE;

--EXECURE
GRANT EXECUTE ON SPOSTA_SENSORE TO R_GESTIONE_STRUTTURE;

--INSERT
--STRUTTURA
GRANT INSERT ON STRUTTURA TO R_GESTIONE_STRUTTURE;
GRANT INSERT ON BLOCCO_ANIMALE TO R_GESTIONE_STRUTTURE;
GRANT INSERT ON CELLA_IDROPONICA TO R_GESTIONE_STRUTTURE;
GRANT INSERT ON TIPO_SENSORE TO R_GESTIONE_STRUTTURE;
GRANT INSERT ON SENSORE TO R_GESTIONE_STRUTTURE;
GRANT INSERT ON REGISTRAZIONE_SENSORE TO R_GESTIONE_STRUTTURE;

--ASSOCIAZIONI
GRANT INSERT ON BLOCCO_ANIMALE_CONTIENE_SENSORE TO R_GESTIONE_STRUTTURE;
GRANT INSERT ON CELLA_IDR_CONTIENE_SENSORE TO R_GESTIONE_STRUTTURE;


--SELECT
--VISTE
GRANT SELECT ON ALLOCAZIONI_SENSORI TO R_GESTIONE_STRUTTURE;
GRANT SELECT ON ELEMENTI_PRODUTTIVI TO R_GESTIONE_STRUTTURE;
GRANT SELECT ON ANOMALIA_SENSORE TO R_GESTIONE_STRUTTURE;


--STRUTTURA
GRANT SELECT ON STRUTTURA TO R_GESTIONE_STRUTTURE;
GRANT SELECT ON BLOCCO_ANIMALE TO R_GESTIONE_STRUTTURE;
GRANT SELECT ON CELLA_IDROPONICA TO R_GESTIONE_STRUTTURE;
GRANT SELECT ON TIPO_SENSORE TO R_GESTIONE_STRUTTURE;
GRANT SELECT ON SENSORE TO R_GESTIONE_STRUTTURE;
GRANT SELECT ON REGISTRAZIONE_SENSORE TO R_GESTIONE_STRUTTURE;

--ASSOCIAZIONI
GRANT SELECT ON BLOCCO_ANIMALE_CONTIENE_SENSORE TO R_GESTIONE_STRUTTURE;
GRANT SELECT ON CELLA_IDR_CONTIENE_SENSORE TO R_GESTIONE_STRUTTURE;



