CREATE ROLE R_GESTIONE_ANIMALI;

GRANT R_GESTIONE_PRODOTTI TO R_GESTIONE_ANIMALI; 

--EXECUTE
GRANT EXECUTE ON REGISTRA_NUOVO_ANIMALE TO R_GESTIONE_ANIMALI;
GRANT EXECUTE ON TRASFERISCI_ANIMALE TO R_GESTIONE_ANIMALI;
GRANT EXECUTE ON VERIFICA_CONSUMI_ANIMALI TO R_GESTIONE_ANIMALI;
GRANT EXECUTE ON CAMBIA_DIETA TO R_GESTIONE_ANIMALI;

--INSERT
--ANIMALE
GRANT INSERT ON TIPO_ANIMALE TO R_GESTIONE_ANIMALI;
GRANT INSERT ON STADIO_CRESCITA TO R_GESTIONE_ANIMALI;
GRANT INSERT ON DIETA_ANIMALE TO R_GESTIONE_ANIMALI;
GRANT INSERT ON VISITA_VETERINARIA TO R_GESTIONE_ANIMALI;
GRANT INSERT ON PRESCRIZIONE_ANIMALE TO R_GESTIONE_ANIMALI;
GRANT INSERT ON PRODUZIONE_ANIMALE TO R_GESTIONE_ANIMALI;

--ASSOCIAZIONI
GRANT INSERT ON STADIO_CRESCITA_PREVEDE_DIETA TO R_GESTIONE_ANIMALI;
GRANT INSERT ON DIETA_COMPRENDE_PRODOTTO TO R_GESTIONE_ANIMALI;
GRANT INSERT ON PRODOTTO_CONTIENE_SOSTANZA TO R_GESTIONE_ANIMALI;
GRANT INSERT ON STADIO_CRESCITA_INTOLLERANTE_SOSTANZA TO R_GESTIONE_ANIMALI;
GRANT INSERT ON BLOCCO_AMMETTE_TIPO_ANIMALE TO R_GESTIONE_ANIMALI; --AGGIUNGERE DOCUMENTAZIONE
GRANT INSERT ON PRODOTTO_DA_STADIO_CRESCITA TO R_GESTIONE_ANIMALI;
GRANT INSERT ON PRODOTTO_CONTIENE_SOSTANZA TO R_GESTIONE_ANIMALI;


--SELECT
--VISTE
GRANT SELECT ON VERIFICA_PRODUZIONE_ANIMALE TO R_GESTIONE_ANIMALI;
GRANT SELECT ON PRODUZIONE_ANIMALE_TOTALE TO R_GESTIONE_ANIMALI;

--ANIMALE
GRANT SELECT ON TIPO_ANIMALE TO R_GESTIONE_ANIMALI;
GRANT SELECT ON ANIMALE TO R_GESTIONE_ANIMALI;
GRANT SELECT ON STADIO_CRESCITA TO R_GESTIONE_ANIMALI;
GRANT SELECT ON DIETA_ANIMALE TO R_GESTIONE_ANIMALI;
GRANT SELECT ON VISITA_VETERINARIA TO R_GESTIONE_ANIMALI;
GRANT SELECT ON PRESCRIZIONE_ANIMALE TO R_GESTIONE_ANIMALI;
GRANT SELECT ON PRODUZIONE_ANIMALE TO R_GESTIONE_ANIMALI;


--ASSOCIAZIONI
GRANT SELECT ON STADIO_CRESCITA_PREVEDE_DIETA TO R_GESTIONE_ANIMALI;
GRANT SELECT ON DIETA_COMPRENDE_PRODOTTO TO R_GESTIONE_ANIMALI;
GRANT SELECT ON PRODOTTO_CONTIENE_SOSTANZA TO R_GESTIONE_ANIMALI;
GRANT SELECT ON STADIO_CRESCITA_INTOLLERANTE_SOSTANZA TO R_GESTIONE_ANIMALI;
GRANT SELECT ON BLOCCO_AMMETTE_TIPO_ANIMALE TO R_GESTIONE_ANIMALI; --AGGIUNGERE DOCUMENTAZIONE
GRANT SELECT ON PRODOTTO_DA_STADIO_CRESCITA TO R_GESTIONE_ANIMALI;
GRANT SELECT ON PRODOTTO_CONTIENE_SOSTANZA TO R_GESTIONE_ANIMALI;
GRANT SELECT ON ANIMALE_ALLOCATO_BLOCCO TO R_GESTIONE_ANIMALI;


--STRUTTURE
GRANT SELECT ON BLOCCO_ANIMALE TO R_GESTIONE_ANIMALI;
GRANT SELECT ON STRUTTURA TO R_GESTIONE_ANIMALI;
