CREATE ROLE R_GESTIONE_AGRICOLA;

GRANT R_GESTIONE_PRODOTTI TO R_GESTIONE_AGRICOLA;


--EXECUTE
GRANT EXECUTE ON INIZIA_CICLO_COLTIVAZIONE_SEMI_ATUOMATICI TO R_GESTIONE_AGRICOLA;
GRANT EXECUTE ON COMPARA_MODALITA_COLTIVAZIONE TO R_GESTIONE_AGRICOLA;
GRANT EXECUTE ON BILANCIO TO R_GESTIONE_AGRICOLA;
GRANT EXECUTE ON TERMINA_CICLO_COLTIVAZIONE TO R_GESTIONE_AGRICOLA;

--INSERT
--AGRICOLTURA
GRANT INSERT ON MODALITA_COLTIVAZIONE TO R_GESTIONE_AGRICOLA;
GRANT INSERT ON TIPO_COLTURA TO R_GESTIONE_AGRICOLA;
GRANT INSERT ON PRODUZIONE_AGRICOLA TO R_GESTIONE_AGRICOLA;
GRANT INSERT ON SEMI_MISSIONE TO R_GESTIONE_AGRICOLA;

--ASSOCIAZIONI
GRANT INSERT ON CELLA_IDR_RISPETTA_MOD_COLT TO R_GESTIONE_AGRICOLA;
GRANT INSERT ON TIPO_COLT_ACCETTA_MOD_COLT TO R_GESTIONE_AGRICOLA;
GRANT INSERT ON TIPO_COLTURA_TIPO_PRODOTTO TO R_GESTIONE_AGRICOLA;


--SELECT
--VISTE
GRANT SELECT ON SEMI_MISSISONE_UTILIZZATI TO R_GESTIONE_AGRICOLA;
GRANT SELECT ON SEMI_MISSIONE_DISPONIBILI TO R_GESTIONE_AGRICOLA;
GRANT SELECT ON SEMI_PRODUZIONE_AGRICOLA_UTILIZZATI TO R_GESTIONE_AGRICOLA;
GRANT SELECT ON SEMI_PRODUZIONE_AGRICOLA_DISPONIBILI TO R_GESTIONE_AGRICOLA;
GRANT SELECT ON SEMI_DISPONIBILI TO R_GESTIONE_AGRICOLA;
GRANT SELECT ON CONSUMO_CICLI_COLTIVAZIONE TO R_GESTIONE_AGRICOLA;
GRANT SELECT ON VERIFICA_PRODUZIONE_AGRICOLA TO R_GESTIONE_AGRICOLA;
GRANT SELECT ON CONSUMO_CICLI_COLTIVAZIONE_2 TO R_GESTIONE_AGRICOLA;
GRANT SELECT ON PRODUZIONE_AGRICOLA_TOTALE TO R_GESTIONE_AGRICOLA;

--AGRICOLTURA
GRANT SELECT ON MODALITA_COLTIVAZIONE TO R_GESTIONE_AGRICOLA;
GRANT SELECT ON TIPO_COLTURA TO R_GESTIONE_AGRICOLA;
GRANT SELECT ON CICLO_COLTIVAZIONE TO R_GESTIONE_AGRICOLA;
GRANT SELECT ON PRODUZIONE_AGRICOLA TO R_GESTIONE_AGRICOLA;
GRANT SELECT ON SEMI_MISSIONE TO R_GESTIONE_AGRICOLA;

--ASSOCIAZIONI
GRANT SELECT ON CELLA_IDR_RISPETTA_MOD_COLT TO R_GESTIONE_AGRICOLA;
GRANT SELECT ON TIPO_COLT_ACCETTA_MOD_COLT TO R_GESTIONE_AGRICOLA;
GRANT SELECT ON TIPO_COLTURA_TIPO_PRODOTTO TO R_GESTIONE_AGRICOLA;
GRANT SELECT ON CICLO_COLT_UTILIZZA_SEMI_MISSIONE TO R_GESTIONE_AGRICOLA;
GRANT SELECT ON CICLO_COLT_UTILIZZA_PRODUZIONE_AGRICOLA TO R_GESTIONE_AGRICOLA;


--STRUTTURA
GRANT SELECT ON STRUTTURA TO R_GESTIONE_AGRICOLA;
GRANT SELECT ON CELLA_IDROPONICA TO R_GESTIONE_AGRICOLA;