from python.DB.action.getter.base import get_data_base

def get_available_mission_seeds():
    return get_data_base(
        "SELECT "
            "SM.*, "
            "SM.QUANTITA_SEMI AS QUANTITA_RESIDUA "
        "FROM SEMI_MISSIONE SM "
        "WHERE NOT EXISTS("
            "SELECT * "
            "FROM CICLO_COLT_UTILIZZA_SEMI_MISSIONE CCU "
            "WHERE CCU.DATA_ARRIVO_SEMI=SM.DATA_ARRIVO_SEMI "
            "AND CCU.NOME_SEMI=SM.NOME_SEMI"
        ") "
        "UNION "
        "SELECT "
            "SM.*, "
            "SM.QUANTITA_SEMI-("
                "SELECT SUM(CCU.QUANTITA) "
                "FROM CICLO_COLT_UTILIZZA_SEMI_MISSIONE CCU "
                "WHERE CCU.DATA_ARRIVO_SEMI=SM.DATA_ARRIVO_SEMI "
                "AND CCU.NOME_SEMI=SM.NOME_SEMI"
            ") AS QUANTITA_RESIDUA "
        "FROM SEMI_MISSIONE SM "
        "WHERE EXISTS("
            "SELECT * "
            "FROM CICLO_COLT_UTILIZZA_SEMI_MISSIONE CCU "
            "WHERE CCU.DATA_ARRIVO_SEMI=SM.DATA_ARRIVO_SEMI "
            "AND CCU.NOME_SEMI=SM.NOME_SEMI"
        ") "
        "AND SM.QUANTITA_SEMI>("
            "SELECT SUM(CCU.QUANTITA) "
            "FROM CICLO_COLT_UTILIZZA_SEMI_MISSIONE CCU "
            "WHERE CCU.DATA_ARRIVO_SEMI=SM.DATA_ARRIVO_SEMI "
            "AND CCU.NOME_SEMI=SM.NOME_SEMI"
        ")"
    )