--NOME_TIPO_COLTURA, NOME_PRODOTTO, QUANTITA_STIMATE_PER_UNITA_SEMI
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Grano duro', 'Grano duro', 18.00);
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Grano duro', 'Semi di grano duro', 3.50);

INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Mais', 'Mais', 20.00);
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Mais', 'Semi di mais', 3.50);

INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Patata', 'Patata', 15.00);
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Patata', 'Talee di patata', 4.00);

INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Pomodoro', 'Pomodoro', 25.00);
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Pomodoro', 'Semi di pomodoro', 5.00);

INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Lattuga', 'Lattuga', 12.00);
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Lattuga', 'Semi di lattuga', 4.00);

INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Spinaci', 'Spinaci', 10.00);
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Spinaci', 'Semi di spinaci', 4.00);

INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Carota', 'Carota', 14.00);
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Carota', 'Semi di carota', 4.00);

INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Zucchina', 'Zucchina', 22.00);
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Zucchina', 'Semi di zucchina', 5.00);

INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Cetriolo', 'Cetriolo', 24.00);
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Cetriolo', 'Semi di cetriolo', 5.00);

INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Melanzana', 'Melanzana', 18.00);
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Melanzana', 'Semi di melanzana', 4.00);

INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Peperone', 'Peperone', 18.00);
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Peperone', 'Semi di peperone', 4.50);

INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Fagiolo', 'Fagiolo', 9.00);
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Fagiolo', 'Semi di fagiolo', 3.00);

INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Ceci', 'Ceci', 8.00);
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Ceci', 'Semi di ceci', 3.00);

INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Lenticchie', 'Lenticchie', 7.00);
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Lenticchie', 'Semi di lenticchie', 3.00);

INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Piselli', 'Piselli', 7.00);
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Piselli', 'Semi di piselli', 3.00);


INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Soia', 'Soia', 8.00);
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Soia', 'Semi di soia', 3.00);

INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Fragola', 'Fragola', 8.00);
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Fragola', 'Semi di fragola', 3.00);


COMMIT;
