--NOME_TIPO_COLTURA, NOME_PRODOTTO, QUANTITA_STIMATE_PER_UNITA_SEMI
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Grano duro', 'Grano duro', 18.00);
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Grano duro', 'Semi di grano duro', 3.50);

INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Mais', 'Mais', 20.00);
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Mais', 'Semi di mais', 3.50);

INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Pomodoro', 'Pomodoro', 25.00);
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Pomodoro', 'Semi di pomodoro', 5.00);

INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Lattuga', 'Lattuga', 12.00);
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Lattuga', 'Semi di lattuga', 4.00);

INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Soia', 'Soia', 8.00);
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Soia', 'Semi di soia', 3.00);

COMMIT;
