--NOME_TIPO_COLTURA, NOME_PRODOTTO, QUANTITA_STIMATE_PER_KG_SEMI
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Grano duro', 'Grano duro', 18.00);
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Grano duro', 'Semi di grano duro', 1.20);

INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Mais', 'Mais', 20.00);
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Mais', 'Semi di mais', 1.10);

INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Patata', 'Patata', 15.00);
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Patata', 'Talee di patata', 1.50);

INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Pomodoro', 'Pomodoro', 25.00);
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Pomodoro', 'Semi di pomodoro', 0.20);

INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Lattuga', 'Lattuga', 12.00);
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Lattuga', 'Semi di lattuga', 0.15);

INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Spinaci', 'Spinaci', 10.00);
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Spinaci', 'Semi di spinaci', 0.20);

INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Carota', 'Carota', 14.00);
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Carota', 'Semi di carota', 0.18);

INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Zucchina', 'Zucchina', 22.00);
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Zucchina', 'Semi di zucchina', 0.25);

INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Cetriolo', 'Cetriolo', 24.00);
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Cetriolo', 'Semi di cetriolo', 0.25);

INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Peperone', 'Peperone', 18.00);
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Peperone', 'Semi di peperone', 0.22);

INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Fagiolo', 'Fagiolo', 9.00);
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Fagiolo', 'Semi di fagiolo', 1.10);

INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Ceci', 'Ceci', 8.00);
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Ceci', 'Semi di ceci', 1.00);

INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Lenticchie', 'Lenticchie', 7.00);
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Lenticchie', 'Semi di lenticchie', 0.90);


INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Soia', 'Soia', 8.00);
INSERT INTO TIPO_COLTURA_TIPO_PRODOTTO VALUES ('Soia', 'Semi di soia', 1.00);


COMMIT;
