--SERIALE, NOME_PRODUTTORE, NOME_MODELLO, NUMERO_BLOCCO, NOME_STRUTTURA, DATA_SMONTAGGIO, DATA_MONTAGGIO
INSERT INTO BLOCCO_ANIMALE_CONTIENE_SENSORE VALUES ('SENS-BLOCK-0002-SZ-ENERGY-01', 'MESA', 'ENERGY-SENSOR-V3', '0002', 'Struttura Zootecnica', NULL, DATE '2025-03-23');
INSERT INTO BLOCCO_ANIMALE_CONTIENE_SENSORE VALUES ('SENS-BLOCK-0002-SZ-HUM-01', 'SpaceTech', 'HUM-SENSOR-V1', '0002', 'Struttura Zootecnica', NULL, DATE '2025-03-23');
INSERT INTO BLOCCO_ANIMALE_CONTIENE_SENSORE VALUES ('SENS-BLOCK-0002-SZ-TEMP-01', 'Cainiao', 'TEMP-SENSOR-V2', '0002', 'Struttura Zootecnica', NULL, DATE '2025-03-23');

COMMIT;
