--NOME_SEMI, TIPO_COLTURA
INSERT INTO TIPO_COLTURA_USA_SEMI_DI_TIPO VALUES ('Semi di grano duro','Grano duro');
INSERT INTO TIPO_COLTURA_USA_SEMI_DI_TIPO VALUES ('Semi di mais','Mais');

INSERT INTO TIPO_COLTURA_USA_SEMI_DI_TIPO VALUES ('Talee di patata','Patata');
INSERT INTO TIPO_COLTURA_USA_SEMI_DI_TIPO VALUES ('Semi di pomodoro','Pomodoro');
INSERT INTO TIPO_COLTURA_USA_SEMI_DI_TIPO VALUES ('Semi di lattuga','Lattuga');
INSERT INTO TIPO_COLTURA_USA_SEMI_DI_TIPO VALUES ('Semi di spinaci','Spinaci');
INSERT INTO TIPO_COLTURA_USA_SEMI_DI_TIPO VALUES ('Semi di carota','Carota');
INSERT INTO TIPO_COLTURA_USA_SEMI_DI_TIPO VALUES ('Semi di zucchina','Zucchina');
INSERT INTO TIPO_COLTURA_USA_SEMI_DI_TIPO VALUES ('Semi di cetriolo','Cetriolo');
INSERT INTO TIPO_COLTURA_USA_SEMI_DI_TIPO VALUES ('Semi di peperone','Peperone');

INSERT INTO TIPO_COLTURA_USA_SEMI_DI_TIPO VALUES ('Semi di fagiolo','Fagiolo');
INSERT INTO TIPO_COLTURA_USA_SEMI_DI_TIPO VALUES ('Semi di ceci','Ceci');
INSERT INTO TIPO_COLTURA_USA_SEMI_DI_TIPO VALUES ('Semi di lenticchie','Lenticchie');
INSERT INTO TIPO_COLTURA_USA_SEMI_DI_TIPO VALUES ('Semi di soia','Soia');

COMMIT;