--NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE, NOME_DIETA, DATA_INIZIO, DATA_FINE
INSERT INTO STADIO_CRESCITA_PREVEDE_DIETA VALUES ('Vitello', 'Bovino', 'Dieta Bovino Vitello', DATE '2025-01-01', NULL);
INSERT INTO STADIO_CRESCITA_PREVEDE_DIETA VALUES ('Giovane', 'Bovino', 'Dieta Bovino Giovane', DATE '2025-01-01', NULL);
INSERT INTO STADIO_CRESCITA_PREVEDE_DIETA VALUES ('Adulto', 'Bovino', 'Dieta Bovino Adulto', DATE '2025-01-01', DATE '2026-01-04');
INSERT INTO STADIO_CRESCITA_PREVEDE_DIETA VALUES ('Adulto', 'Bovino', 'Dieta Bovino Adulto V2', DATE '2026-01-05', NULL);

INSERT INTO STADIO_CRESCITA_PREVEDE_DIETA VALUES ('Capretto', 'Capra', 'Dieta Capra Capretto', DATE '2025-01-01', NULL);
INSERT INTO STADIO_CRESCITA_PREVEDE_DIETA VALUES ('Giovane', 'Capra', 'Dieta Capra Giovane', DATE '2025-01-01', NULL);
INSERT INTO STADIO_CRESCITA_PREVEDE_DIETA VALUES ('Adulto', 'Capra', 'Dieta Capra Adulto', DATE '2025-01-01', NULL);

INSERT INTO STADIO_CRESCITA_PREVEDE_DIETA VALUES ('Pulcino', 'Gallina', 'Dieta Gallina Pulcino', DATE '2025-01-01', NULL);
INSERT INTO STADIO_CRESCITA_PREVEDE_DIETA VALUES ('Giovane', 'Gallina', 'Dieta Gallina Giovane', DATE '2025-01-01', NULL);
INSERT INTO STADIO_CRESCITA_PREVEDE_DIETA VALUES ('Adulto', 'Gallina', 'Dieta Gallina Adulto', DATE '2025-01-01', NULL);

INSERT INTO STADIO_CRESCITA_PREVEDE_DIETA VALUES ('Cucciolo', 'Coniglio', 'Dieta Coniglio Cucciolo', DATE '2025-01-01', NULL);
INSERT INTO STADIO_CRESCITA_PREVEDE_DIETA VALUES ('Giovane', 'Coniglio', 'Dieta Coniglio Giovane', DATE '2025-01-01', DATE '2026-01-05');
INSERT INTO STADIO_CRESCITA_PREVEDE_DIETA VALUES ('Giovane', 'Coniglio', 'Dieta Coniglio Giovane V2', DATE '2026-01-06', NULL);
INSERT INTO STADIO_CRESCITA_PREVEDE_DIETA VALUES ('Adulto', 'Coniglio', 'Dieta Coniglio Adulto', DATE '2025-01-01', NULL);
COMMIT;
