--NOME_PRODOTTO, NOME_DIETA, QUANTITA
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Bovino Vitello', 8.00);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mais', 'Dieta Bovino Vitello', 0.80);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Grano duro', 'Dieta Bovino Vitello', 0.50);

INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Bovino Giovane', 20.00);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mais', 'Dieta Bovino Giovane', 2.00);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Lattuga', 'Dieta Bovino Giovane', 0.60);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Grano duro', 'Dieta Bovino Giovane', 1.50);

INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Bovino Adulto', 35.00);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mais', 'Dieta Bovino Adulto', 3.00);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Soia', 'Dieta Bovino Adulto', 1.00);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Grano duro', 'Dieta Bovino Adulto', 2.00);

INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Bovino Adulto V2', 45.00);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mais', 'Dieta Bovino Adulto V2', 4.00);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Soia', 'Dieta Bovino Adulto V2', 1.50);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Grano duro', 'Dieta Bovino Adulto V2', 2.50);

INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Capra Capretto', 2.00);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mais', 'Dieta Capra Capretto', 0.20);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Grano duro', 'Dieta Capra Capretto', 0.15);

INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Capra Giovane', 4.00);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mais', 'Dieta Capra Giovane', 0.60);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Grano duro', 'Dieta Capra Giovane', 0.40);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Lattuga', 'Dieta Capra Giovane', 0.15);

INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Capra Adulto', 6.00);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mais', 'Dieta Capra Adulto', 0.80);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Grano duro', 'Dieta Capra Adulto', 0.60);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Soia', 'Dieta Capra Adulto', 0.20);

INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Gallina Pulcino', 0.25);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mais', 'Dieta Gallina Pulcino', 0.035);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Grano duro', 'Dieta Gallina Pulcino', 0.020);

INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Gallina Giovane', 0.40);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mais', 'Dieta Gallina Giovane', 0.070);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Grano duro', 'Dieta Gallina Giovane', 0.040);

INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Gallina Adulto', 0.50);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mais', 'Dieta Gallina Adulto', 0.100);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Grano duro', 'Dieta Gallina Adulto', 0.060);

INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Coniglio Cucciolo', 0.15);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Carota', 'Dieta Coniglio Cucciolo', 0.020);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Lattuga', 'Dieta Coniglio Cucciolo', 0.030);

INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Coniglio Giovane', 0.45);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Carota', 'Dieta Coniglio Giovane', 0.050);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Lattuga', 'Dieta Coniglio Giovane', 0.080);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mais', 'Dieta Coniglio Giovane', 0.020);

INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Coniglio Giovane V2', 0.55);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Carota', 'Dieta Coniglio Giovane V2', 0.080);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Lattuga', 'Dieta Coniglio Giovane V2', 0.120);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mais', 'Dieta Coniglio Giovane V2', 0.020);

INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Coniglio Adulto', 0.70);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Carota', 'Dieta Coniglio Adulto', 0.100);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Lattuga', 'Dieta Coniglio Adulto', 0.150);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mais', 'Dieta Coniglio Adulto', 0.030);

COMMIT;
