--NOME_PRODOTTO, NOME_DIETA, QUANTITA
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Bovino Vitello', 8.00);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mais', 'Dieta Bovino Vitello', 0.80);

INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Bovino Giovane', 20.00);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mais', 'Dieta Bovino Giovane', 2.00);

INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Grano duro', 'Dieta Bovino Adulto', 2.00);

INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Bovino Adulto V2', 45.00);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mais', 'Dieta Bovino Adulto V2', 4.00);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Soia', 'Dieta Bovino Adulto V2', 1.50);

INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mais', 'Dieta Capra Capretto', 0.20);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mais', 'Dieta Capra Giovane', 0.60);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Acqua potabile', 'Dieta Capra Adulto', 6.00);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mais', 'Dieta Capra Adulto', 0.80);

INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mais', 'Dieta Gallina Pulcino', 0.035);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mais', 'Dieta Gallina Giovane', 0.070);
INSERT INTO DIETA_COMPRENDE_PRODOTTO VALUES ('Mais', 'Dieta Gallina Adulto', 0.100);

COMMIT;
