--NOME_PRODOTTO, NOME_SOSTANZA, LIVELLO_PRESENZA

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Latte bovino', 'Lattosio', 'ALTO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Latte bovino', 'Caseina', 'ALTO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Latte bovino', 'Proteine del siero del latte', 'MEDIO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Latte bovino', 'Albumina sierica bovina', 'BASSO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Latte caprino', 'Lattosio', 'ALTO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Latte caprino', 'Caseina', 'ALTO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Latte caprino', 'Proteine del siero del latte', 'MEDIO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Latte ovino', 'Lattosio', 'ALTO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Latte ovino', 'Caseina', 'ALTO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Latte ovino', 'Proteine del siero del latte', 'MEDIO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Formaggio fresco', 'Caseina', 'ALTO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Formaggio fresco', 'Lattosio', 'BASSO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Formaggio fresco', 'Proteine del siero del latte', 'BASSO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Yogurt naturale', 'Lattosio', 'MEDIO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Yogurt naturale', 'Caseina', 'MEDIO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Yogurt naturale', 'Proteine del siero del latte', 'BASSO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Burro', 'Lattosio', 'BASSO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Burro', 'Caseina', 'BASSO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Panna', 'Lattosio', 'MEDIO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Panna', 'Caseina', 'BASSO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Uova di gallina', 'Proteine dell uovo', 'ALTO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Uova di gallina', 'Ovoalbumina', 'ALTO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Uova di gallina', 'Ovomucoide', 'MEDIO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Uova di quaglia', 'Proteine dell uovo', 'ALTO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Uova di quaglia', 'Ovoalbumina', 'ALTO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Uova di quaglia', 'Ovomucoide', 'MEDIO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Carne bovina', 'Alfa gal', 'MEDIO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Carne bovina', 'Proteine della carne bovina', 'ALTO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Carne bovina', 'Albumina sierica bovina', 'BASSO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Carne suina', 'Alfa gal', 'MEDIO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Carne suina', 'Proteine della carne suina', 'ALTO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Carne ovina', 'Alfa gal', 'MEDIO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Carne ovina', 'Proteine della carne ovina', 'ALTO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Carne caprina', 'Alfa gal', 'MEDIO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Carne caprina', 'Proteine della carne caprina', 'ALTO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Carne di pollo', 'Proteine della carne avicola', 'ALTO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Carne di tacchino', 'Proteine della carne avicola', 'ALTO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Carne di coniglio', 'Proteine della carne di coniglio', 'ALTO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Grano duro', 'Glutine', 'ALTO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Grano duro', 'Gliadina', 'ALTO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Grano duro', 'Glutenina', 'ALTO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Grano duro', 'Fruttani', 'MEDIO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Farina di grano', 'Glutine', 'ALTO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Farina di grano', 'Gliadina', 'ALTO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Farina di grano', 'Glutenina', 'ALTO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Farina di grano', 'Fruttani', 'MEDIO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Mais', 'Proteine del mais', 'ALTO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Mais', 'Fruttani', 'BASSO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Patata', 'Solanina', 'BASSO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Patata', 'Ossalati', 'BASSO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Pomodoro', 'Fruttosio', 'BASSO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Pomodoro', 'Salicilati naturali', 'MEDIO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Pomodoro', 'Solanina', 'BASSO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Pomodoro', 'Istamina', 'BASSO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Lattuga', 'Salicilati naturali', 'BASSO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Lattuga', 'Nichel alimentare', 'BASSO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Spinaci', 'Ossalati', 'ALTO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Spinaci', 'Nichel alimentare', 'MEDIO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Spinaci', 'Salicilati naturali', 'BASSO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Carota', 'Salicilati naturali', 'BASSO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Zucchina', 'Salicilati naturali', 'BASSO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Cetriolo', 'Salicilati naturali', 'BASSO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Melanzana', 'Solanina', 'MEDIO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Melanzana', 'Salicilati naturali', 'BASSO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Melanzana', 'Istamina', 'BASSO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Peperone', 'Capsaicina', 'MEDIO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Peperone', 'Salicilati naturali', 'MEDIO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Fagiolo', 'Proteine dei legumi', 'ALTO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Fagiolo', 'Vicilina', 'MEDIO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Fagiolo', 'Convicilina', 'MEDIO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Fagiolo', 'Lectine vegetali', 'MEDIO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Fagiolo', 'Galatto oligosaccaridi', 'ALTO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Fagiolo', 'Raffinosio', 'MEDIO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Fagiolo', 'Stachiosio', 'MEDIO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Ceci', 'Proteine dei legumi', 'ALTO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Ceci', 'Vicilina', 'MEDIO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Ceci', 'Convicilina', 'MEDIO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Ceci', 'Lectine vegetali', 'MEDIO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Ceci', 'Galatto oligosaccaridi', 'ALTO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Ceci', 'Raffinosio', 'MEDIO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Ceci', 'Stachiosio', 'MEDIO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Lenticchie', 'Proteine dei legumi', 'ALTO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Lenticchie', 'Vicilina', 'MEDIO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Lenticchie', 'Convicilina', 'MEDIO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Lenticchie', 'Lectine vegetali', 'MEDIO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Lenticchie', 'Galatto oligosaccaridi', 'ALTO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Lenticchie', 'Raffinosio', 'MEDIO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Lenticchie', 'Stachiosio', 'MEDIO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Piselli', 'Proteine dei legumi', 'ALTO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Piselli', 'Vicilina', 'MEDIO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Piselli', 'Convicilina', 'MEDIO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Piselli', 'Lectine vegetali', 'BASSO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Piselli', 'Galatto oligosaccaridi', 'MEDIO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Piselli', 'Raffinosio', 'BASSO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Piselli', 'Stachiosio', 'BASSO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Soia', 'Proteine della soia', 'ALTO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Soia', 'Lecitina di soia', 'MEDIO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Soia', 'Lectine vegetali', 'MEDIO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Soia', 'Galatto oligosaccaridi', 'ALTO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Soia', 'Raffinosio', 'MEDIO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Soia', 'Stachiosio', 'MEDIO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Fragola', 'Fruttosio', 'MEDIO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Fragola', 'Salicilati naturali', 'MEDIO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Fragola', 'Istamina', 'MEDIO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Uva', 'Fruttosio', 'MEDIO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Uva', 'Salicilati naturali', 'BASSO');

COMMIT;
