--NOME_PRODOTTO, NOME_SOSTANZA, LIVELLO_PRESENZA

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Latte bovino', 'Lattosio', 'ALTO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Latte bovino', 'Caseina', 'ALTO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Latte caprino', 'Lattosio', 'ALTO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Latte caprino', 'Caseina', 'ALTO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Uova di gallina', 'Proteine dell uovo', 'ALTO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Uova di gallina', 'Ovoalbumina', 'ALTO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Uova di gallina', 'Ovomucoide', 'MEDIO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Grano duro', 'Glutine', 'ALTO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Grano duro', 'Gliadina', 'ALTO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Mais', 'Proteine del mais', 'ALTO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Mais', 'Fruttani', 'BASSO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Pomodoro', 'Fruttosio', 'BASSO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Pomodoro', 'Solanina', 'BASSO');

INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Lattuga', 'Salicilati naturali', 'BASSO');
INSERT INTO PRODOTTO_CONTIENE_SOSTANZA VALUES ('Soia', 'Proteine della soia', 'ALTO');

COMMIT;
