--NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE, NOME_SOSTANZA
INSERT INTO STADIO_CRESCITA_INTOLLERANTE_SOSTANZA VALUES ('Vitello', 'Bovino', 'Proteine della soia');
INSERT INTO STADIO_CRESCITA_INTOLLERANTE_SOSTANZA VALUES ('Vitello', 'Bovino', 'Lectine vegetali');

INSERT INTO STADIO_CRESCITA_INTOLLERANTE_SOSTANZA VALUES ('Giovane', 'Bovino', 'Proteine della soia');

INSERT INTO STADIO_CRESCITA_INTOLLERANTE_SOSTANZA VALUES ('Capretto', 'Capra', 'Proteine della soia');
INSERT INTO STADIO_CRESCITA_INTOLLERANTE_SOSTANZA VALUES ('Capretto', 'Capra', 'Lectine vegetali');

INSERT INTO STADIO_CRESCITA_INTOLLERANTE_SOSTANZA VALUES ('Giovane', 'Capra', 'Proteine della soia');

INSERT INTO STADIO_CRESCITA_INTOLLERANTE_SOSTANZA VALUES ('Pulcino', 'Gallina', 'Lectine vegetali');
INSERT INTO STADIO_CRESCITA_INTOLLERANTE_SOSTANZA VALUES ('Pulcino', 'Gallina', 'Galatto oligosaccaridi');

INSERT INTO STADIO_CRESCITA_INTOLLERANTE_SOSTANZA VALUES ('Giovane', 'Gallina', 'Lectine vegetali');

INSERT INTO STADIO_CRESCITA_INTOLLERANTE_SOSTANZA VALUES ('Cucciolo', 'Coniglio', 'Lectine vegetali');
INSERT INTO STADIO_CRESCITA_INTOLLERANTE_SOSTANZA VALUES ('Cucciolo', 'Coniglio', 'Galatto oligosaccaridi');

INSERT INTO STADIO_CRESCITA_INTOLLERANTE_SOSTANZA VALUES ('Giovane', 'Coniglio', 'Galatto oligosaccaridi');
INSERT INTO STADIO_CRESCITA_INTOLLERANTE_SOSTANZA VALUES ('Giovane', 'Coniglio', 'Raffinosio');

COMMIT;
