--NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE, NOME_SOSTANZA
INSERT INTO STADIO_CRESCITA_INTOLLERANTE_SOSTANZA VALUES ('Vitello', 'Bovino', 'Proteine della soia');
INSERT INTO STADIO_CRESCITA_INTOLLERANTE_SOSTANZA VALUES ('Capretto', 'Capra', 'Glutine');
INSERT INTO STADIO_CRESCITA_INTOLLERANTE_SOSTANZA VALUES ('Pulcino', 'Gallina', 'Caseina');

COMMIT;
