--NOME_TIPO_ANIMALE, NUMERO_BLOCCO, NOME_STRUTTURA
INSERT INTO BLOCCO_AMMETTE_TIPO_ANIMALE VALUES ('Gallina', '0001', 'Struttura Zootecnica');

INSERT INTO BLOCCO_AMMETTE_TIPO_ANIMALE VALUES ('Bovino', '0002', 'Struttura Zootecnica');
INSERT INTO BLOCCO_AMMETTE_TIPO_ANIMALE VALUES ('Capra', '0002', 'Struttura Zootecnica');
INSERT INTO BLOCCO_AMMETTE_TIPO_ANIMALE VALUES ('Gallina', '0002', 'Struttura Zootecnica');

INSERT INTO BLOCCO_AMMETTE_TIPO_ANIMALE VALUES ('Bovino', '0003', 'Struttura Zootecnica');
INSERT INTO BLOCCO_AMMETTE_TIPO_ANIMALE VALUES ('Capra', '0003', 'Struttura Zootecnica');
INSERT INTO BLOCCO_AMMETTE_TIPO_ANIMALE VALUES ('Coniglio', '0003', 'Struttura Zootecnica');

INSERT INTO BLOCCO_AMMETTE_TIPO_ANIMALE VALUES ('Gallina', '0001', 'Struttura Mista');

INSERT INTO BLOCCO_AMMETTE_TIPO_ANIMALE VALUES ('Bovino', '0002', 'Struttura Mista');
INSERT INTO BLOCCO_AMMETTE_TIPO_ANIMALE VALUES ('Capra', '0002', 'Struttura Mista');

COMMIT;
