--NOME_PRODOTTO, NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE, QUANTITA_STIMATA_GIORNALIERA
INSERT INTO PRODOTTO_DA_STADIO_CRESCITA VALUES ('Letame bovino', 'Vitello', 'Bovino', 8.00);
INSERT INTO PRODOTTO_DA_STADIO_CRESCITA VALUES ('Letame bovino', 'Giovane', 'Bovino', 15.00);
INSERT INTO PRODOTTO_DA_STADIO_CRESCITA VALUES ('Letame bovino', 'Adulto', 'Bovino', 25.00);
INSERT INTO PRODOTTO_DA_STADIO_CRESCITA VALUES ('Latte bovino', 'Adulto', 'Bovino', 22.00);

INSERT INTO PRODOTTO_DA_STADIO_CRESCITA VALUES ('Latte caprino', 'Adulto', 'Capra', 2.50);

INSERT INTO PRODOTTO_DA_STADIO_CRESCITA VALUES ('Pollina', 'Pulcino', 'Gallina', 0.03);
INSERT INTO PRODOTTO_DA_STADIO_CRESCITA VALUES ('Pollina', 'Giovane', 'Gallina', 0.06);
INSERT INTO PRODOTTO_DA_STADIO_CRESCITA VALUES ('Pollina', 'Adulto', 'Gallina', 0.10);
INSERT INTO PRODOTTO_DA_STADIO_CRESCITA VALUES ('Uova di gallina', 'Adulto', 'Gallina', 0.06);

COMMIT;
