--NOME_TIPO_COLTURA, NOME_MODALITA_COLTIVAZIONE
INSERT INTO TIPO_COLT_ACCETTA_MOD_COLT VALUES ('Grano duro', 'Idro cereali base');
INSERT INTO TIPO_COLT_ACCETTA_MOD_COLT VALUES ('Mais', 'Idro cereali base');
INSERT INTO TIPO_COLT_ACCETTA_MOD_COLT VALUES ('Pomodoro', 'Idro frutto concentrata');
INSERT INTO TIPO_COLT_ACCETTA_MOD_COLT VALUES ('Lattuga', 'Idro foglia base');
INSERT INTO TIPO_COLT_ACCETTA_MOD_COLT VALUES ('Soia', 'Organica letame bovino');

COMMIT;
