CREATE PROCEDURE CONTROLLO_ANOMALIE_SENSORI(
    DATA_VERIFICA DATE
)
AS 
    NUMERO_ANOMALIE LOG_ANOMALIE_SENSORI.NUMERO_ANOMALIE%TYPE;

BEGIN 

    
    SELECT COUNT(*)
    INTO NUMERO_ANOMALIE
    FROM ANOMALIA_SENSORE
    WHERE TRUNC(DATA_SECONDI)=TRUNC(DATA_VERIFICA);
    

    INSERT INTO LOG_ANOMALIE_SENSORI VALUES(
        DATA_VERIFICA,
        NUMERO_ANOMALIE
    );

    COMMIT;

EXCEPTION 
    WHEN OTHERS
        THEN 
            ROLLBACK;
            RAISE;
END;
/
