--PERMETTE DI TERMINARE L'ALLOCAZIONE
--ATTUALE DI UN ANIMALE IN UN BLOCCO

CREATE PROCEDURE TERMINA_ALLOCAZIONE_ANIMALE(
    IN_ETICHETTA ANIMALE_ALLOCATO_BLOCCO.ETICHETTA_ANIMALE%TYPE,
    NEW_DATA_DEALLOCAZIONE DATE
)
AS

    OLD_NUMERO_BLOCCO CHAR(4);
    OLD_NOME_STRUTTURA VARCHAR(60);
    OLD_DATA_ALLOCAZIONE DATE;

    IS_VALID NUMBER(1,0);

    ANIMALE_NON_PRESENTE EXCEPTION;
    DATA_DEALLOCAZIONE_NULLA EXCEPTION;

BEGIN 

    IF NEW_DATA_DEALLOCAZIONE IS NULL
        THEN 
            RAISE DATA_DEALLOCAZIONE_NULLA;
    END IF;

    --1: VERIFICO LA ALLOCAZIONE ATTUALE DELL'ANIMALE
    SELECT COUNT(*)
    INTO IS_VALID
    FROM ANIMALE_ALLOCATO_BLOCCO
    WHERE ETICHETTA_ANIMALE=IN_ETICHETTA
    AND DATA_DEALLOCAZIONE IS NULL;

    IF IS_VALID = 0
        THEN 
            RAISE ANIMALE_NON_PRESENTE;
    END IF;

    SELECT NUMERO_BLOCCO, NOME_STRUTTURA, DATA_ALLOCAZIONE
    INTO OLD_NUMERO_BLOCCO, OLD_NOME_STRUTTURA, OLD_DATA_ALLOCAZIONE
    FROM ANIMALE_ALLOCATO_BLOCCO
    WHERE ETICHETTA_ANIMALE=IN_ETICHETTA
    AND DATA_DEALLOCAZIONE IS NULL;

    --2: IMPOSTO DATA DEALLOCAZIONE NELLA ALLOCAZIONE ATTUALE

    UPDATE ANIMALE_ALLOCATO_BLOCCO
    SET DATA_DEALLOCAZIONE=NEW_DATA_DEALLOCAZIONE
    WHERE NUMERO_BLOCCO=OLD_NUMERO_BLOCCO
    AND NOME_STRUTTURA=OLD_NOME_STRUTTURA
    AND ETICHETTA_ANIMALE=IN_ETICHETTA
    AND DATA_ALLOCAZIONE=OLD_DATA_ALLOCAZIONE;

    COMMIT;

EXCEPTION
    WHEN ANIMALE_NON_PRESENTE
        THEN 
            ROLLBACK;
            RAISE_APPLICATION_ERROR(
                -20006,
                'L''animale selezionato non è
                allocato in alcun blocco'
            );
    WHEN DATA_DEALLOCAZIONE_NULLA
        THEN 
            RAISE_APPLICATION_ERROR(
                -20008,
                'È necessario inserire una data di deallocazione
                per terminare l''allocazione dell''animale'
            );

    WHEN OTHERS
        THEN
            ROLLBACK;
            RAISE;
END;
/
