--PERMETTE DI TERMINARE L'ALLOCAZIONE
--ATTUALE DI UN SENSORE

CREATE PROCEDURE TERMINA_ALLOCAZIONE_SENSORE(
    IN_SERIALE SENSORE.SERIALE%TYPE,
    IN_NOME_PRODUTTORE SENSORE.NOME_PRODUTTORE%TYPE,
    IN_NOME_MODELLO SENSORE.NOME_MODELLO%TYPE,
    NEW_DATA_SMONTAGGIO DATE
)
AS 
    OLD_CODICE_BLOCCO CHAR(4);
    OLD_NOME_STRUTTURA VARCHAR(60);
    OLD_DATA_MONTAGGIO DATE;

    IS_VALID NUMBER(1,0);

    SENSORE_INESISTENTE EXCEPTION;
    DATA_SMONTAGGIO_NULLA EXCEPTION;

BEGIN 

    IF NEW_DATA_SMONTAGGIO IS NULL
        THEN 
            RAISE DATA_SMONTAGGIO_NULLA;
    END IF;

    --1: TROVIAMO IL SENSORE
    SELECT COUNT(*)
    INTO IS_VALID
    FROM ALLOCAZIONI_SENSORI ASE
    WHERE ASE.SERIALE=IN_SERIALE
    AND ASE.NOME_PRODUTTORE=IN_NOME_PRODUTTORE
    AND ASE.NOME_MODELLO=IN_NOME_MODELLO
    AND ASE.DATA_SMONTAGGIO IS NULL;

    IF IS_VALID = 0
        THEN 
            RAISE SENSORE_INESISTENTE;
    END IF;

    SELECT CODICE_BLOCCO, NOME_STRUTTURA, DATA_MONTAGGIO
    INTO OLD_CODICE_BLOCCO, OLD_NOME_STRUTTURA, OLD_DATA_MONTAGGIO
    FROM ALLOCAZIONI_SENSORI ASE
    WHERE ASE.SERIALE=IN_SERIALE
    AND ASE.NOME_PRODUTTORE=IN_NOME_PRODUTTORE
    AND ASE.NOME_MODELLO=IN_NOME_MODELLO
    AND ASE.DATA_SMONTAGGIO IS NULL;

    --2:SE ESISTE RIMUOVIAMO IL SENSORE

    IF REGEXP_LIKE(RTRIM(OLD_CODICE_BLOCCO), '[[:digit:]]$') --FINISCE CON UN NUMERO È UN BLOCCO ANIMALE
        THEN
            
            UPDATE BLOCCO_ANIMALE_CONTIENE_SENSORE
            SET DATA_SMONTAGGIO=NEW_DATA_SMONTAGGIO
            WHERE NUMERO_BLOCCO=OLD_CODICE_BLOCCO
            AND NOME_STRUTTURA=OLD_NOME_STRUTTURA
            AND NOME_PRODUTTORE=IN_NOME_PRODUTTORE
            AND NOME_MODELLO=IN_NOME_MODELLO
            AND SERIALE=IN_SERIALE
            AND DATA_MONTAGGIO=OLD_DATA_MONTAGGIO;
            
        ELSE

            UPDATE CELLA_IDR_CONTIENE_SENSORE
            SET DATA_SMONTAGGIO=NEW_DATA_SMONTAGGIO
            WHERE CODICE_CELLA_IDR=OLD_CODICE_BLOCCO
            AND NOME_STRUTTURA=OLD_NOME_STRUTTURA
            AND NOME_PRODUTTORE=IN_NOME_PRODUTTORE
            AND NOME_MODELLO=IN_NOME_MODELLO
            AND SERIALE=IN_SERIALE
            AND DATA_MONTAGGIO=OLD_DATA_MONTAGGIO;

    END IF;

    COMMIT;

EXCEPTION
    WHEN SENSORE_INESISTENTE
        THEN 
            ROLLBACK;
            RAISE_APPLICATION_ERROR(
                -20006,
                'Il sensore selezionato non è
                allocato in alcun blocco animale o cella idroponica'
            );
    WHEN DATA_SMONTAGGIO_NULLA
        THEN 
            RAISE_APPLICATION_ERROR(
                -20008,
                'È necessario inserire una data di smontaggio
                per terminare l''allocazione del sensore'
            );

    WHEN OTHERS 
        THEN 
            ROLLBACK;
            RAISE;
END;
/
