--PERMETTE DI TRASFERIRE UN ANIMALE DA UN BLOCCO
--A UN ALTRO

CREATE PROCEDURE TRASFERISCI_ANIMALE(
    IN_ETICHETTA IN CHAR, 
    IN_NUMERO_BLOCCO IN CHAR,
    IN_NOME_STRUTTURA IN CHAR,
    IN_DATA_ALLOCAZIONE IN CHAR
)
AS

    OLD_NUMERO_BLOCCO CHAR(4);
    OLD_NOME_STRUTTURA VARCHAR(60);
    OLD_DATA_ALLOCAZIONE DATE;

    ANIMALE_NON_PRESENTE EXCEPTION;

BEGIN 

    --1: VERIFICO LA ALLOCAZIONE ATTUALE DELL'ANIMALE
    SELECT NUMERO_BLOCCO, NOME_STRUTTURA, DATA_ALLOCAZIONE
    INTO OLD_NUMERO_BLOCCO, OLD_NOME_STRUTTURA, OLD_DATA_ALLOCAZIONE
    FROM ANIMALE_ALLOCATO_BLOCCO
    WHERE ETICHETTA_ANIMALE=IN_ETICHETTA
    AND DATA_DEALLOCAZIONE IS NULL;

    IF OLD_NUMERO_BLOCCO IS NULL 
        THEN 
            RAISE ANIMALE_NON_PRESENTE;
    END IF;

    --2: IMPOSTO DATA DEALLOCAZIONE NELLA VECCHIA ALLOCAZIONE

    UPDATE ANIMALE_ALLOCATO_BLOCCO
    SET DATA_DEALLOCAZIONE=IN_DATA_ALLOCAZIONE
    WHERE NUMERO_BLOCCO=OLD_NUMERO_BLOCCO
    AND NOME_STRUTTURA=OLD_NOME_STRUTTURA
    AND ETICHETTA_ANIMALE=IN_ETICHETTA
    AND DATA_ALLOCAZIONE=OLD_DATA_ALLOCAZIONE;

    --3: IMPOSTO LA NUOVA ALLOCAZIONE

    INSERT INTO ANIMALE_ALLOCATO_BLOCCO VALUES(
        IN_NUMERO_BLOCCO,
        IN_NOME_STRUTTURA,
        IN_ETICHETTA,
        IN_DATA_ALLOCAZIONE,
        NULL
    );


    COMMIT;

EXCEPTION
    WHEN ANIMALE_NON_PRESENTE
        THEN 
            ROLLBACK;
            RAISE_APPLICATION_ERROR(
                -20006,
                'L''animale selezionato non è
                allocato in alcun blocco'
            );

    WHEN OTHERS
        THEN
            ROLLBACK;
            RAISE;
END;
/