

CREATE PROCEDURE SPOSTA_SENSORE(
    NEW_CODICE_BLOCCO ALLOCAZIONI_SENSORI.CODICE_BLOCCO%TYPE,
    NEW_NOME_STRUTTURA ALLOCAZIONI_SENSORI.NOME_STRUTTURA%TYPE,
    NEW_DATA_MONTAGGIO DATE,
    IN_SERIALE SENSORE.SERIALE%TYPE,
    IN_NOME_PRODUTTORE SENSORE.NOME_PRODUTTORE%TYPE,
    IN_NOME_MODELLO SENSORE.NOME_MODELLO%TYPE
)
AS 
    OLD_CODICE_BLOCCO CHAR(4);
    OLD_NOME_STRUTTURA VARCHAR(60);
    OLD_DATA_MONTAGGIO DATE;

    SENSORE_INESISTENTE EXCEPTION;
    DATA_MONTAGGIO_NULLA EXCEPTION;
BEGIN 

    IF NEW_DATA_MONTAGGIO IS NULL
        THEN 
            RAISE DATA_MONTAGGIO_NULLA;
    END IF;

    --1: TROVIAMO IL SENSORE
    SELECT CODICE_BLOCCO, NOME_STRUTTURA, DATA_MONTAGGIO
    INTO OLD_CODICE_BLOCCO, OLD_NOME_STRUTTURA, OLD_DATA_MONTAGGIO
    FROM ALLOCAZIONI_SENSORI ASE
    WHERE ASE.SERIALE=IN_SERIALE
    AND ASE.NOME_PRODUTTORE=IN_NOME_PRODUTTORE
    AND ASE.NOME_MODELLO=IN_NOME_MODELLO
    AND ASE.DATA_SMONTAGGIO IS NULL;

    --2: SE ESISTE RIMUOVIAMO IL SENSORE

    IF REGEXP_LIKE(RTRIM(OLD_CODICE_BLOCCO), '[[:digit:]]$') --FINISCE CON UN NUMERO È UN BLOCCO ANIMALE
        THEN
            
            UPDATE BLOCCO_ANIMALE_CONTIENE_SENSORE
            SET DATA_SMONTAGGIO=NEW_DATA_MONTAGGIO
            WHERE NUMERO_BLOCCO=OLD_CODICE_BLOCCO
            AND NOME_STRUTTURA=OLD_NOME_STRUTTURA
            AND NOME_PRODUTTORE=IN_NOME_PRODUTTORE
            AND NOME_MODELLO=IN_NOME_MODELLO
            AND SERIALE=IN_SERIALE
            AND DATA_MONTAGGIO=OLD_DATA_MONTAGGIO;
            
        ELSE

            UPDATE CELLA_IDR_CONTIENE_SENSORE
            SET DATA_SMONTAGGIO=NEW_DATA_MONTAGGIO
            WHERE CODICE_CELLA_IDR=OLD_CODICE_BLOCCO
            AND NOME_STRUTTURA=OLD_NOME_STRUTTURA
            AND NOME_PRODUTTORE=IN_NOME_PRODUTTORE
            AND NOME_MODELLO=IN_NOME_MODELLO
            AND SERIALE=IN_SERIALE
            AND DATA_MONTAGGIO=OLD_DATA_MONTAGGIO;

    END IF;

    --3: PROCEDIAMO CON L'INSERIMENTO
    IF REGEXP_LIKE(RTRIM(NEW_CODICE_BLOCCO), '[[:digit:]]$') --FINISCE CON UN NUMERO È UN BLOCCO ANIMALE
        THEN
            
            INSERT INTO BLOCCO_ANIMALE_CONTIENE_SENSORE VALUES(
                IN_SERIALE,
                IN_NOME_PRODUTTORE,
                IN_NOME_MODELLO,
                NEW_CODICE_BLOCCO,
                NEW_NOME_STRUTTURA,
                NULL,
                NEW_DATA_MONTAGGIO
            );
            
        ELSE

            INSERT INTO CELLA_IDR_CONTIENE_SENSORE VALUES(
                IN_SERIALE,
                IN_NOME_PRODUTTORE,
                IN_NOME_MODELLO,
                NEW_CODICE_BLOCCO,
                NEW_NOME_STRUTTURA,
                NULL,
                NEW_DATA_MONTAGGIO
            );
    END IF;


    COMMIT;

EXCEPTION
    WHEN DATA_MONTAGGIO_NULLA
        THEN 
            RAISE_APPLICATION_ERROR(
                -20008,
                'È necessario inserire una data di montaggio
                per spostare il sensore'
            );

    WHEN OTHERS 
        THEN 
            ROLLBACK;
            RAISE;
END;
/
