--PERMETTE DI COMPARARE
--VARI INDICATORI DI DIFFERENTI
--MODALITA COLTIVAZIONE PER UN 
--TIPO DI COLTURA

CREATE PROCEDURE COMPARA_MODALITA_COLTIVAZIONE(
   IN_NOME_TIPO_COLTURA TIPO_COLTURA.NOME_TIPO_COLTURA%TYPE
)
AS 

BEGIN

    FOR RW IN(
        SELECT 
        MC.NOME_MODALITA_COLTIVAZIONE,
        MC.NOME_PRODOTTO AS PRODOTTO_UTILIZZATO,
        SUM(PA.QUANTITA) AS QUANTITA_PRODOTTA,
        SUM(SEMI.QUANTITA) AS QUANTITA_SEMI_PIANTATI,
        SUM(MC.ACQUA_ORA*(24)*(((CC.DATA_FINE_EFFETTIVA - CC.DATA_INIZIO)))) AS QUANTITA_ACQUA,
        SUM(MC.QUANTITA_SOLUZIONE_ORA *(24)*((CC.DATA_FINE_EFFETTIVA - CC.DATA_INIZIO))) AS QUANTITA_SOLUZIONE,
        SUM(PA.QUANTITA)/SUM(MC.ACQUA_ORA*(24)*(((CC.DATA_FINE_EFFETTIVA - CC.DATA_INIZIO)))) AS RAPPORTO_QUANTITA_PRODOTTA_ACQUA_UTILIZZATA,
        SUM(PA.QUANTITA)/SUM(MC.QUANTITA_SOLUZIONE_ORA *(24)*((CC.DATA_FINE_EFFETTIVA - CC.DATA_INIZIO))) AS RAPPORTO_QUANTITA_PRODOTTA_SOLUZIONE_UTILIZZATA,
        SUM(PA.QUANTITA)/SUM(SEMI.QUANTITA) AS RAPPORTO_QUANTITA_PRODOTTA_SEMI_PIANTATI

    FROM CICLO_COLTIVAZIONE CC

    JOIN MODALITA_COLTIVAZIONE MC
    ON MC.NOME_MODALITA_COLTIVAZIONE=CC.NOME_MOD_COLTIVAZIONE

    JOIN TIPO_COLTURA TC 
    ON TC.NOME_TIPO_COLTURA=CC.NOME_TIPO_COLTURA

    JOIN PRODUZIONE_AGRICOLA PA 
    ON PA.DATA_INIZIO_CICLO_COLTIVAZIONE=CC.DATA_INIZIO
    AND PA.CODICE_CELLA_IDR=CC.CODICE_CELLA_IDR
    AND PA.NOME_STRUTTURA=CC.NOME_STRUTTURA
    AND UPPER(PA.NOME_PRODOTTO)=UPPER(IN_NOME_TIPO_COLTURA)

    LEFT JOIN (
        SELECT 
            DATA_INIZIO,
            CODICE_CELLA_IDR,
            NOME_STRUTTURA,
            SUM(QUANTITA) AS QUANTITA
        FROM (
            SELECT 
                DATA_INIZIO,
                CODICE_CELLA_IDR,
                NOME_STRUTTURA,
                QUANTITA
            FROM CICLO_COLT_UTILIZZA_SEMI_MISSIONE

            UNION ALL

            SELECT 
                DATA_INIZIO,
                CODICE_CELLA_IDR,
                NOME_STRUTTURA,
                QUANTITA
            FROM CICLO_COLT_UTILIZZA_PRODUZIONE_AGRICOLA
        )
        GROUP BY DATA_INIZIO, CODICE_CELLA_IDR, NOME_STRUTTURA
    ) SEMI
    ON SEMI.DATA_INIZIO=CC.DATA_INIZIO
    AND SEMI.CODICE_CELLA_IDR=CC.CODICE_CELLA_IDR
    AND SEMI.NOME_STRUTTURA=CC.NOME_STRUTTURA

    JOIN TIPO_COLTURA_TIPO_PRODOTTO TCTP 
    ON TCTP.NOME_PRODOTTO=PA.NOME_PRODOTTO
    AND TCTP.NOME_TIPO_COLTURA=CC.NOME_TIPO_COLTURA

    WHERE CC.DATA_FINE_EFFETTIVA IS NOT NULL

    GROUP BY MC.NOME_MODALITA_COLTIVAZIONE, MC.NOME_PRODOTTO
    )LOOP

        DBMS_OUTPUT.PUT_LINE('modalita coltivazione: '|| RW.NOME_MODALITA_COLTIVAZIONE);
        DBMS_OUTPUT.PUT_LINE('prodotto utilizzato: '|| RW.PRODOTTO_UTILIZZATO);
        DBMS_OUTPUT.PUT_LINE('quantita prodotta: '|| RW.QUANTITA_PRODOTTA);
        DBMS_OUTPUT.PUT_LINE('quantita semi piantati: '|| RW.QUANTITA_SEMI_PIANTATI);
        DBMS_OUTPUT.PUT_LINE('quantita acqua: '|| RW.QUANTITA_ACQUA);
        DBMS_OUTPUT.PUT_LINE('quantita soluzione: '|| RW.QUANTITA_SOLUZIONE);
        DBMS_OUTPUT.PUT_LINE('rapporto quantita prodotta acqua utilizzata: '|| RW.RAPPORTO_QUANTITA_PRODOTTA_ACQUA_UTILIZZATA);
        DBMS_OUTPUT.PUT_LINE('rapporto quantita prodotta soluzione utilizzata: '|| RW.RAPPORTO_QUANTITA_PRODOTTA_SOLUZIONE_UTILIZZATA);
        DBMS_OUTPUT.PUT_LINE('rapporto quantita prodotta semi piantati: '|| RW.RAPPORTO_QUANTITA_PRODOTTA_SEMI_PIANTATI);
        DBMS_OUTPUT.PUT_LINE('');

    END LOOP;

END;
/
