CREATE PROCEDURE REGISTRA_NUOVO_ANIMALE(
    IN_MESE_NASCITA ANIMALE.MESE_NASCITA%TYPE,
    IN_ETICHETTA_ANIMALE ANIMALE.ETICHETTA%TYPE,
    IN_SESSO ANIMALE.SESSO%TYPE,
    IN_ETICHETTA_GENITORE_1 ANIMALE.ETICHETTA_GENITORE_1%TYPE,
    IN_ETICHETTA_GENITORE_2 ANIMALE.ETICHETTA_GENITORE_2%TYPE,
    IN_ANNO_NASCITA ANIMALE.ANNO_NASCITA%TYPE,
    IN_NOME_TIPO_ANIMALE ANIMALE.NOME_TIPO_ANIMALE%TYPE,

    IN_NUMERO_BLOCCO ANIMALE_ALLOCATO_BLOCCO.NUMERO_BLOCCO%TYPE,
    IN_NOME_STRUTTURA ANIMALE_ALLOCATO_BLOCCO.NOME_STRUTTURA%TYPE,
    IN_DATA_ALLOCAZIONE DATE,
    IN_DATA_DEALLOCAZIONE DATE
)AS 

BEGIN 

    INSERT INTO ANIMALE VALUES(
        IN_ETICHETTA_ANIMALE,
        IN_ETICHETTA_GENITORE_1,
        IN_ETICHETTA_GENITORE_2,
        IN_SESSO,
        IN_MESE_NASCITA,
        IN_ANNO_NASCITA,
        IN_NOME_TIPO_ANIMALE
    );

    INSERT INTO ANIMALE_ALLOCATO_BLOCCO VALUES(
        IN_NUMERO_BLOCCO,
        IN_NOME_STRUTTURA,
        IN_ETICHETTA_ANIMALE,
        IN_DATA_ALLOCAZIONE,
        IN_DATA_DEALLOCAZIONE
    );

    COMMIT;

EXCEPTION
    WHEN OTHERS 
        THEN 
            ROLLBACK;
            RAISE;

    END;
/
