CREATE PROCEDURE CAMBIA_DIETA(
    IN_NOME_STADIO_CRESCITA STADIO_CRESCITA_PREVEDE_DIETA.NOME_STADIO_CRESCITA%TYPE,
    IN_NOME_TIPO_ANIMALE STADIO_CRESCITA_PREVEDE_DIETA.NOME_TIPO_ANIMALE%TYPE,
    NEW_NOME_DIETA STADIO_CRESCITA_PREVEDE_DIETA.NOME_DIETA%TYPE,
    NEW_DATA_INIZIO DATE

)
AS 
    OLD_NOME_DIETA VARCHAR(60);
    OLD_DATA_INIZIO DATE;

    DATA_INIZIO_NULLA EXCEPTION;

BEGIN 

    IF NEW_DATA_INIZIO IS NULL 
        THEN 
            RAISE DATA_INIZIO_NULLA;
    END IF;

    SELECT NOME_DIETA, DATA_INIZIO 
    INTO OLD_NOME_DIETA, OLD_DATA_INIZIO
    FROM STADIO_CRESCITA_PREVEDE_DIETA 
    WHERE NOME_TIPO_ANIMALE=IN_NOME_TIPO_ANIMALE
    AND NOME_STADIO_CRESCITA=IN_NOME_STADIO_CRESCITA
    AND DATA_FINE IS NULL;

    UPDATE STADIO_CRESCITA_PREVEDE_DIETA
    SET DATA_FINE=NEW_DATA_INIZIO-1
    WHERE NOME_TIPO_ANIMALE=IN_NOME_TIPO_ANIMALE
    AND NOME_STADIO_CRESCITA=IN_NOME_STADIO_CRESCITA
    AND NOME_DIETA=OLD_NOME_DIETA
    AND DATA_INIZIO=OLD_DATA_INIZIO;

    INSERT INTO STADIO_CRESCITA_PREVEDE_DIETA VALUES(
        IN_NOME_STADIO_CRESCITA,
        IN_NOME_TIPO_ANIMALE,
        NEW_NOME_DIETA,
        NEW_DATA_INIZIO,
        NULL
    );

    COMMIT;

EXCEPTION
    WHEN DATA_INIZIO_NULLA
        THEN 
            RAISE_APPLICATION_ERROR(
                -20008,
                'È necessario inserire una data di inizio
                per cambiare la dieta'
            );

    WHEN OTHERS 
        THEN 
            ROLLBACK;
            RAISE;
END;
/
