CREATE PROCEDURE TERMINA_CICLO_COLTIVAZIONE(
   IN_DATA_INIZIO DATE,
   IN_CODICE_CELLA_IDR CICLO_COLTIVAZIONE.CODICE_CELLA_IDR%TYPE,
   IN_NOME_STRUTTURA CICLO_COLTIVAZIONE.NOME_STRUTTURA%TYPE,
   NEW_DATA_FINE_EFFETTIVA DATE
)
AS 

GIA_FINITO DATE;

DATA_FINE_NULLA EXCEPTION;
CICLO_GIA_TERMINATO EXCEPTION;

BEGIN 

    IF NEW_DATA_FINE_EFFETTIVA IS NULL 
        THEN 
            RAISE DATA_FINE_NULLA;
    END IF;

    SELECT DATA_FINE_EFFETTIVA
    INTO GIA_FINITO
    FROM CICLO_COLTIVAZIONE
    WHERE DATA_INIZIO=IN_DATA_INIZIO
    AND CODICE_CELLA_IDR=IN_CODICE_CELLA_IDR
    AND NOME_STRUTTURA=IN_NOME_STRUTTURA; 

    IF GIA_FINITO IS NOT NULL
        THEN 
            RAISE CICLO_GIA_TERMINATO;
    END IF;

    UPDATE CICLO_COLTIVAZIONE
    SET DATA_FINE_EFFETTIVA=NEW_DATA_FINE_EFFETTIVA
    WHERE DATA_INIZIO=IN_DATA_INIZIO
    AND CODICE_CELLA_IDR=IN_CODICE_CELLA_IDR
    AND NOME_STRUTTURA=IN_NOME_STRUTTURA;

    COMMIT;

EXCEPTION
    WHEN DATA_FINE_NULLA
        THEN 
            RAISE_APPLICATION_ERROR(
                -20008,
                'È necessario inserire una data di fine
                per terminare il ciclo coltivazione'
            );
    WHEN CICLO_GIA_TERMINATO
        THEN 
            RAISE_APPLICATION_ERROR(
                -20009,
                'Non è possibile terminare un ciclo
                di coltivazione già terminato'
            );

    WHEN OTHERS 
        THEN 
            ROLLBACK;
            RAISE;

END;
/
