CREATE TABLE SOSTANZA(
    NOME_SOSTANZA VARCHAR2(30),
    IS_POTENZIALE_ALLERGENE NUMBER(1,0),
    IS_POTENZIALE_INTOLLERANTE NUMBER(1,0),
    

    --PK
    CONSTRAINT PK_SOSTANZA PRIMARY KEY (NOME_SOSTANZA),

    --CHECK
    CONSTRAINT CK_SOSTANZA_IS_POTENZIALE_ALLERGENE
        CHECK (IS_POTENZIALE_ALLERGENE IN (1, 0)),
    
    CONSTRAINT CK_SOSTANZA_IS_POTENZIALE_INTOLLERANTE
        CHECK (IS_POTENZIALE_INTOLLERANTE IN (1, 0))
);