CREATE TABLE MODALITA_CONSERVAZIONE(
    NOME_CONSERVAZIONE VARCHAR2(30),
    DURATA_MASSIMA_GIORNI NUMBER(4,0),
    TEMPERATURA_MAX NUMBER(4,0),
    TEMPERATURA_MIN NUMBER(4,0),
    UMIDITA_MIN NUMBER(3,0),
    UMIDITA_MAX NUMBER(3,0),

    --PK
    CONSTRAINT PK_MODALITA_CONSERVAZIONE
        PRIMARY KEY (NOME_CONSERVAZIONE),
    
    --CHECK
    CONSTRAINT CK_MODALITA_CONSERVAZIONE_DURATA_MAX
        CHECK (DURATA_MASSIMA_GIORNI >= 0),
    
    CONSTRAINT CK_MODALITA_CONSERVAZIONE_TEMPERATURA_MAX
        CHECK (TEMPERATURA_MAX > 0),

    CONSTRAINT CK_MODALITA_CONSERVAZIONE_TEMPERATURA_MIN
        CHECK (TEMPERATURA_MIN > 0),

    CONSTRAINT CK_MODALITA_CONSERVAZIONE_UMIDITA_MIN
        CHECK (UMIDITA_MIN >= 0 AND UMIDITA_MIN <= 100),

    CONSTRAINT CK_MODALITA_CONSERVAZIONE_UMIDITA_MAX
        CHECK (UMIDITA_MAX >= 0 AND UMIDITA_MAX <= 100)
);