CREATE TABLE UNITA_DI_MISURA(
        CODICE_UNITA VARCHAR(10), --ES.: KG
        GRANDEZZA VARCHAR(60) --ES.: MASSA
            CONSTRAINT NN_UNITA_MISURA_GRANDEZZA NOT NULL,
        NOME_UNITA VARCHAR(60) --ES.: CHILOGRAMMO
            CONSTRAINT NN_UNITA_MISURA_NOME_UNITA NOT NULL,

        --PK
            CONSTRAINT PK_UNITA_DI_MISURA PRIMARY KEY (CODICE_UNITA)
);