SELECT *
FROM STADIO_CRESCITA_PREVEDE_DIETA SCPD
    JOIN STADIO_CRESCITA_INTOLLERANTE_SOSTANZA SCIC 
    ON SCIC.NOME_STADIO_CRESCITA=SCPD.NOME_STADIO_CRESCITA
    AND SCIC.NOME_TIPO_ANIMALE=SCPD.NOME_TIPO_ANIMALE
    WHERE SCPD.NOME_DIETA='Dieta Bovino Vitello'
    AND SCIC.NOME_SOSTANZA IN(
        SELECT NOME_SOSTANZA
        FROM PRODOTTO_CONTIENE_SOSTANZA
        WHERE NOME_PRODOTTO='Fagiolo'
    );