
SELECT 
    'Pomodoro' AS NOME_COLTURA,
    MC.NOME_MODALITA_COLTIVAZIONE,
    MC.NOME_PRODOTTO AS SOLUZIONE_NUTRITIVA,
    SUM(PA.QUANTITA) AS QUANTITA_PRODOTTA,
    SUM((NVL(CCSM.QUANTITA,0)+NVL(CCPA.QUANTITA,0))) AS QUANTITA_SEMI_PIANTATI,
    SUM(MC.ACQUA_ORA*(24)*(((CC.DATA_FINE_EFFETTIVA - CC.DATA_INIZIO)))) AS QUANTITA_ACQUA,
    SUM(MC.QUANTITA_SOLUZIONE_ORA *(24)*((CC.DATA_FINE_EFFETTIVA - CC.DATA_INIZIO))) AS QUANTITA_SOLUZIONE,
    SUM(PA.QUANTITA)/SUM(MC.ACQUA_ORA*(24)*(((CC.DATA_FINE_EFFETTIVA - CC.DATA_INIZIO)))) AS RAPPORTO_QUANTITA_PRODOTTA_ACQUA_UTILIZZATA,
    SUM(PA.QUANTITA)/SUM(MC.QUANTITA_SOLUZIONE_ORA *(24)*((CC.DATA_FINE_EFFETTIVA - CC.DATA_INIZIO))) AS RAPPORTO_QUANTITA_PRODOTTA_SOLUZIONE_UTILIZZATA,
    SUM(PA.QUANTITA)/SUM((NVL(CCSM.QUANTITA,0)+NVL(CCPA.QUANTITA,0))) AS EFFICENZA

FROM CICLO_COLTIVAZIONE CC

JOIN MODALITA_COLTIVAZIONE MC
ON MC.NOME_MODALITA_COLTIVAZIONE=CC.NOME_MOD_COLTIVAZIONE

JOIN TIPO_COLTURA TC 
ON TC.NOME_TIPO_COLTURA=CC.NOME_TIPO_COLTURA

JOIN PRODUZIONE_AGRICOLA PA 
ON PA.DATA_INIZIO_CICLO_COLTIVAZIONE=CC.DATA_INIZIO
AND PA.CODICE_CELLA_IDR=CC.CODICE_CELLA_IDR
AND PA.NOME_STRUTTURA=CC.NOME_STRUTTURA
AND PA.NOME_PRODOTTO='Pomodoro'

LEFT JOIN CICLO_COLT_UTILIZZA_SEMI_MISSIONE CCSM 
ON CCSM.DATA_INIZIO=CC.DATA_INIZIO
AND CCSM.CODICE_CELLA_IDR=CC.CODICE_CELLA_IDR
AND CCSM.NOME_STRUTTURA=CC.NOME_STRUTTURA

LEFT JOIN CICLO_COLT_UTILIZZA_PRODUZIONE_AGRICOLA CCPA
ON CCPA.DATA_INIZIO=CC.DATA_INIZIO
AND CCPA.CODICE_CELLA_IDR=CC.CODICE_CELLA_IDR
AND CCPA.NOME_STRUTTURA=CC.NOME_STRUTTURA

JOIN TIPO_COLTURA_TIPO_PRODOTTO TCTP 
ON TCTP.NOME_PRODOTTO=PA.NOME_PRODOTTO
AND TCTP.NOME_TIPO_COLTURA=CC.NOME_TIPO_COLTURA

WHERE CC.DATA_FINE_EFFETTIVA IS NOT NULL

GROUP BY NOME_MODALITA_COLTIVAZIONE, MC.NOME_PRODOTTO
