SELECT COUNT(*)
FROM STRUTTURA S 
JOIN(
    SELECT 
        CI2.NOME_STRUTTURA,
        CI2.DATA_MONTAGGIO AS ISTANTE,
        SUM(CI.SUPERFICIE_MQ) AS SUPERFICIE_OCCUPATA

    FROM ELEMENTI_PRODUTTIVI CI
    JOIN ELEMENTI_PRODUTTIVI CI2
    ON CI.NOME_STRUTTURA=CI2.NOME_STRUTTURA
    WHERE CI.DATA_MONTAGGIO <= CI2.DATA_MONTAGGIO
    AND(
        CI.DATA_SMONTAGGIO IS NULL 
        OR CI.DATA_SMONTAGGIO > CI2.DATA_MONTAGGIO
    )
    GROUP BY 
        CI2.NOME_STRUTTURA,
        CI2.DATA_MONTAGGIO
) T

ON S.NOME_STRUTTURA=T.NOME_STRUTTURA
WHERE S.SUPERFICIE_MQ<T.SUPERFICIE_OCCUPATA