--TENGO TRACCIA DI TUTTI I CONSUMI DEI CICLI DI COLTIVAZIONE


(
    (
        select b.codice_cella_idr, b.CODICE_AREA, b.NOME_STRUTTURA, b.DATA_INIZIO,A.NOME_MODALITA_COLTIVAZIONE,
        (b.data_fine_effettiva-b.DATA_INIZIO)as giorni, b.DATA_FINE_EFFETTIVA, 
        CEIL((a.ACQUA_ML_ORA*(b.data_fine_effettiva-b.DATA_INIZIO)*24)/1000) AS TOT_LITRI_ACQUA,
        CEIL((a.QUANTITA_SOLUZIONE_ML_ORA*(b.data_fine_effettiva-b.DATA_INIZIO)*24)/1000) AS TOT_LITRI_SOLUZIONE_NUTRITIVA
        from CICLO_COLTIVAZIONE b
        join  MODALITA_COLTIVAZIONE a
        on a.NOME_MODALITA_COLTIVAZIONE = b.NOME_MOD_COLTIVAZIONE 
        where b.DATA_FINE_EFFETTIVA is not null
    )

    UNION
    (
        select b.codice_cella_idr, b.CODICE_AREA, b.NOME_STRUTTURA, b.DATA_INIZIO, A.NOME_MODALITA_COLTIVAZIONE, 
        CEIL(sysdate-b.DATA_INIZIO)as giorni, b.DATA_FINE_EFFETTIVA,
        CEIL((a.ACQUA_ML_ORA*(sysdate-b.DATA_INIZIO)*24)/1000) AS TOT_LITRI_ACQUA,
        CEIL((a.QUANTITA_SOLUZIONE_ML_ORA*(sysdate-b.DATA_INIZIO)*24)/1000) AS TOT_LITRI_SOLUZIONE_NUTRITIVA
        from CICLO_COLTIVAZIONE b
        join  MODALITA_COLTIVAZIONE a
        on a.NOME_MODALITA_COLTIVAZIONE = b.NOME_MOD_COLTIVAZIONE 
        where b.DATA_FINE_EFFETTIVA is  null
    )
);
