WITH GIORNI AS (
    SELECT DATE '2025-05-01' + LEVEL - 1 AS GIORNO
    FROM DUAL
    CONNECT BY DATE '2025-05-01' + LEVEL - 1 <= DATE '2025-05-12'
)
SELECT NOME_PRODOTTO, SUM(QUANTITA_CONSUMATA) AS QUANTITA_CONSUMATA
FROM (
    -- consumi da dieta per ogni giorno
    SELECT DCP.NOME_PRODOTTO, SUM(DCP.QUANTITA) AS QUANTITA_CONSUMATA
    FROM GIORNI G
    JOIN ANIMALE ANM
    ON EXISTS (
        SELECT 1
        FROM ANIMALE_ALLOCATO_BLOCCO AAB
        WHERE AAB.ETICHETTA_ANIMALE = ANM.ETICHETTA
        AND AAB.DATA_ALLOCAZIONE <= G.GIORNO
        AND (
            AAB.DATA_DEALLOCAZIONE IS NULL
            OR AAB.DATA_DEALLOCAZIONE > G.GIORNO
        )
    )
    JOIN STADIO_CRESCITA SC
    ON SC.NOME_TIPO_ANIMALE = ANM.NOME_TIPO_ANIMALE
    AND SC.ETA_MINIMA_MESI = (
        SELECT MAX(SC2.ETA_MINIMA_MESI)
        FROM STADIO_CRESCITA SC2
        WHERE SC2.NOME_TIPO_ANIMALE = ANM.NOME_TIPO_ANIMALE
        AND SC2.ETA_MINIMA_MESI <=
            ((EXTRACT(YEAR FROM G.GIORNO) - ANM.ANNO_NASCITA) * 12)
            + (EXTRACT(MONTH FROM G.GIORNO) - ANM.MESE_NASCITA)
    )
    JOIN STADIO_CRESCITA_PREVEDE_DIETA SCPD
    ON SCPD.NOME_STADIO_CRESCITA = SC.NOME_STADIO_CRESCITA
    AND SCPD.NOME_TIPO_ANIMALE = SC.NOME_TIPO_ANIMALE
    AND SCPD.DATA_INIZIO <= G.GIORNO
    AND (
        SCPD.DATA_FINE IS NULL
        OR SCPD.DATA_FINE > G.GIORNO
    )
    JOIN DIETA_COMPRENDE_PRODOTTO DCP
    ON DCP.NOME_DIETA = SCPD.NOME_DIETA
    GROUP BY DCP.NOME_PRODOTTO

    UNION ALL

    -- consumi da prescrizione per ogni giorno
    SELECT PA.NOME_PRODOTTO, SUM(PA.QUANTITA_GIORNALIERA) AS QUANTITA_CONSUMATA
    FROM GIORNI G
    JOIN PRESCRIZIONE_ANIMALE PA
    ON PA.DATA_VISITA <= G.GIORNO
    AND PA.DATA_VISITA + PA.DURATA_GIORNI >= G.GIORNO
    GROUP BY PA.NOME_PRODOTTO
)
GROUP BY NOME_PRODOTTO;