--Attivato se la dieta comprende 
--un prodotto, che genera intolleranze
--allo stadio crescita relativo

CREATE or replace TRIGGER TRG_STADIO_CRESCITA_PREVEDE_DIETA
BEFORE INSERT OR UPDATE ON STADIO_CRESCITA_PREVEDE_DIETA
FOR EACH ROW 

DECLARE 
    IS_INVALID NUMBER(3,0);
    INTOLLERANTE EXCEPTION;

BEGIN

    SELECT COUNT(*)
    INTO IS_INVALID
    FROM DIETA_COMPRENDE_PRODOTTO DCP
    WHERE DCP.NOME_DIETA=:NEW.NOME_DIETA
    AND DCP.NOME_PRODOTTO IN (
        SELECT NOME_PRODOTTO
        FROM PRODOTTO_CONTIENE_SOSTANZA PCS 
        WHERE PCS.NOME_SOSTANZA IN (
            SELECT SCIS.NOME_SOSTANZA
            FROM STADIO_CRESCITA_INTOLLERANTE_SOSTANZA SCIS
            WHERE SCIS.NOME_STADIO_CRESCITA=:NEW.NOME_STADIO_CRESCITA
            AND SCIS.NOME_TIPO_ANIMALE=:NEW.NOME_TIPO_ANIMALE
        )
    );

    IF IS_INVALID <> 0
        THEN 
            RAISE INTOLLERANTE;
    END IF;

EXCEPTION
    WHEN INTOLLERANTE
        THEN 
            RAISE_APPLICATION_ERROR(
                -20001,
                'Lo stadio crescita è intollerante a uno dei prodotti della dieta'
            );

END;
/


--Attivato se vi è già un altra
--dieta attiva

CREATE TRIGGER TRG_STADIO_CRESCITA_PREVEDE_DIETA_UNICITA
AFTER INSERT OR UPDATE ON STADIO_CRESCITA_PREVEDE_DIETA

DECLARE 
    IS_INVALID NUMBER(3,0);

    DIETA_DOPPIA EXCEPTION;

BEGIN 

    SELECT COUNT(*)
    INTO IS_INVALID
    FROM STADIO_CRESCITA_PREVEDE_DIETA SC1
    JOIN STADIO_CRESCITA_PREVEDE_DIETA SC2 
    ON SC1.NOME_STADIO_CRESCITA=SC2.NOME_STADIO_CRESCITA
    AND SC1.NOME_TIPO_ANIMALE=SC2.NOME_TIPO_ANIMALE
    WHERE SC1.NOME_DIETA <> SC2.NOME_DIETA
    AND SC1.DATA_INIZIO <= SC2.DATA_INIZIO
    AND (
        SC1.DATA_FINE IS NULL 
        OR SC1.DATA_FINE >= SC2.DATA_INIZIO 
    );

    IF IS_INVALID <> 0 
        THEN 
            RAISE DIETA_DOPPIA;
    END IF;

EXCEPTION 
    WHEN DIETA_DOPPIA
        THEN 
            RAISE_APPLICATION_ERROR(
                -20001,
                'Vi è già una dieta attiva
                per questo intervallo di tempo.
                Si prega di utilizzare la procedura
                di cambio dieta'
            );
END;
/
