--Attivato se la dieta comprende 
--un prodotto, che genera intolleranze
--allo stadio crescita relativo

CREATE or replace TRIGGER TRG_STADIO_CRESCITA_PREVEDE_DIETA
BEFORE INSERT OR UPDATE ON STADIO_CRESCITA_PREVEDE_DIETA
FOR EACH ROW 

DECLARE 
    IS_INVALID NUMBER(3,0);
    INTOLLERANTE EXCEPTION;

BEGIN

    SELECT COUNT(*)
    INTO IS_INVALID
    FROM DIETA_COMPRENDE_PRODOTTO DCP
    WHERE DCP.NOME_DIETA=:NEW.NOME_DIETA
    AND DCP.NOME_PRODOTTO IN (
        SELECT NOME_PRODOTTO
        FROM PRODOTTO_CONTIENE_SOSTANZA PCS 
        WHERE PCS.NOME_SOSTANZA IN (
            SELECT SCIS.NOME_SOSTANZA
            FROM STADIO_CRESCITA_INTOLLERANTE_SOSTANZA SCIS
            WHERE SCIS.NOME_STADIO_CRESCITA=:NEW.NOME_STADIO_CRESCITA
            AND SCIS.NOME_TIPO_ANIMALE=:NEW.NOME_TIPO_ANIMALE
        )
    );

    IF IS_INVALID <> 0
        THEN 
            RAISE INTOLLERANTE;
    END IF;

EXCEPTION
    WHEN INTOLLERANTE
        THEN 
            RAISE_APPLICATION_ERROR(
                -20001,
                'Lo stadio crescita è intollerante a uno dei prodotti della dieta'
            );

END;
/


