--Attivato se l'animale è allocato
--in un blocco non compatibile con
--il tipo di animale

CREATE TRIGGER TRG_ANIMALE_ALLOCATO_BLOCCO_COMPATIBILE
BEFORE INSERT OR UPDATE ON ANIMALE_ALLOCATO_BLOCCO 
FOR EACH ROW 

DECLARE 
    IS_VALID NUMBER(1,0);
    ALLOCAZIONE_NON_AMMISSIBILE EXCEPTION;
BEGIN 
    
    SELECT COUNT(*)
    INTO IS_VALID 
    FROM BLOCCO_AMMETTE_TIPO_ANIMALE BATA
    WHERE BATA.NUMERO_BLOCCO=:NEW.NUMERO_BLOCCO
    AND BATA.NOME_STRUTTURA=:NEW.NOME_STRUTTURA
    AND BATA.NOME_TIPO_ANIMALE=(
        SELECT NOME_TIPO_ANIMALE
        FROM ANIMALE
        WHERE ANIMALE.ETICHETTA=:NEW.ETICHETTA_ANIMALE
    );

    IF IS_VALID = 0 
        THEN 
            RAISE ALLOCAZIONE_NON_AMMISSIBILE;
    END IF;


EXCEPTION
    WHEN ALLOCAZIONE_NON_AMMISSIBILE
        THEN 
            RAISE_APPLICATION_ERROR(
                -20001,
                'Animale allocato in un blocco non compatibile'
            );
END;
/

--Attivaso se non vi è spazio disponibile
--all'interno del blocco

CREATE TRIGGER TRG_ANIMALE_ALLOCATO_SPAZIO_DISPONIBILE
AFTER INSERT OR UPDATE ON ANIMALE_ALLOCATO_BLOCCO 

DECLARE 
    IS_INVALID NUMBER(3,0);
    SPAZIO_INSUFFICIENTE EXCEPTION;

BEGIN 

    SELECT COUNT(*)
    INTO IS_INVALID
    FROM(
        SELECT BA.NUMERO_BLOCCO, BA.NOME_STRUTTURA, BA.SUPERFICIE_MQ, SUM(TA.SPAZIO_MINIMO_MQ) SPAZIO_OCCUPATO, AAB.DATA_CHECK
            FROM (
                SELECT NUMERO_BLOCCO, NOME_STRUTTURA, DATA_ALLOCAZIONE AS DATA_CHECK
                FROM ANIMALE_ALLOCATO_BLOCCO 
            ) AAB

        JOIN ANIMALE_ALLOCATO_BLOCCO AAB2 --FACCIO IN MODO DI CONTROLLARE SOLO ANIMALI ALLCATI NELLO STESSO INTERVALLO TEMPORALE
        ON AAB.NUMERO_BLOCCO=AAB2.NUMERO_BLOCCO
        AND AAB.NOME_STRUTTURA=AAB2.NOME_STRUTTURA
        AND AAB2.DATA_ALLOCAZIONE<=AAB.DATA_CHECK
        AND(
            AAB2.DATA_DEALLOCAZIONE IS NULL 
            OR AAB2.DATA_DEALLOCAZIONE>AAB.DATA_CHECK
        )

        JOIN BLOCCO_ANIMALE BA 
        ON BA.NUMERO_BLOCCO=AAB2.NUMERO_BLOCCO
        AND BA.NOME_STRUTTURA=AAB2.NOME_STRUTTURA
        JOIN TIPO_ANIMALE TA 
        ON TA.NOME_TIPO_ANIMALE=(
            SELECT NOME_TIPO_ANIMALE
            FROM ANIMALE
            WHERE ETICHETTA=AAB2.ETICHETTA_ANIMALE
        )
        GROUP BY BA.NUMERO_BLOCCO, BA.NOME_STRUTTURA, BA.SUPERFICIE_MQ, AAB.DATA_CHECK
        HAVING(SUM(TA.SPAZIO_MINIMO_MQ) > BA.SUPERFICIE_MQ)

    );

    IF IS_INVALID <> 0
        THEN 
            RAISE SPAZIO_INSUFFICIENTE;
    END IF;


EXCEPTION
    WHEN SPAZIO_INSUFFICIENTE
        THEN 
            RAISE_APPLICATION_ERROR(
                -20001,
                'Non vi è abbastanza spazio per allocare l''animale'
            );
END;
/

--Attivato se vi sono incompatibilità
--sulle date di allocazione

CREATE TRIGGER TRG_ANIMALE_ALLOCATO_BLOCCO_DATE_BLOCCO
BEFORE INSERT OR UPDATE ON ANIMALE_ALLOCATO_BLOCCO
FOR EACH ROW 

DECLARE 
    IS_VALID NUMBER(1,0);
    BLOCCO_INESISTENTE EXCEPTION;

BEGIN 

    SELECT COUNT(*)
    INTO IS_VALID
    FROM BLOCCO_ANIMALE BA
    WHERE BA.NUMERO_BLOCCO=:NEW.NUMERO_BLOCCO
    AND BA.NOME_STRUTTURA=:NEW.NOME_STRUTTURA
    AND BA.DATA_MONTAGGIO <= :NEW.DATA_ALLOCAZIONE
    AND(
        BA.DATA_SMONTAGGIO IS NULL 
        OR BA.DATA_SMONTAGGIO > :NEW.DATA_ALLOCAZIONE
    )
    AND(
        :NEW.DATA_DEALLOCAZIONE IS NULL 
        OR (
            BA.DATA_SMONTAGGIO IS NULL 
            OR :NEW.DATA_DEALLOCAZIONE <= BA.DATA_SMONTAGGIO
        )
    );

    IF IS_VALID = 0
        THEN 
            RAISE BLOCCO_INESISTENTE;
    END IF;

EXCEPTION
    WHEN BLOCCO_INESISTENTE
        THEN 
            RAISE_APPLICATION_ERROR(
                -20003,
                'Il blocco selezionato non esiste nelle date di allcoazione/deallocazione inserite'
            );
END;
/


--Attivato se la data di deallocazione è 
--precedente a quelal di allocazione

CREATE TRIGGER TRG_ANIMALE_ALLOCATO_BLOCCO_DATA_DEALLOC
BEFORE INSERT OR UPDATE ON ANIMALE_ALLOCATO_BLOCCO
FOR EACH ROW 

DECLARE
    DEALLOCAZIONE_INCOMPATIBILE EXCEPTION;

BEGIN

    IF :NEW.DATA_DEALLOCAZIONE IS NOT NULL
        AND :NEW.DATA_ALLOCAZIONE > :NEW.DATA_DEALLOCAZIONE
        THEN 
            RAISE DEALLOCAZIONE_INCOMPATIBILE;
    END IF;

EXCEPTION 
    WHEN DEALLOCAZIONE_INCOMPATIBILE
        THEN 
            RAISE_APPLICATION_ERROR(
                -20004,
                'La data di deallocazione è precedente a quella
                di allocazione'
            );
END;
/


--Attivato se l'animale
--è gia allocato in un altro blocco

CREATE TRIGGER TRG_ANIMALE_ALLOCATO_BLOCCO_GIA_ALLOCATO
AFTER INSERT OR UPDATE ON ANIMALE_ALLOCATO_BLOCCO

DECLARE
    IS_INVALID NUMBER(1,0);
    GIA_ALLOCATO EXCEPTION;

BEGIN

    SELECT COUNT(*)
    INTO IS_INVALID 
    FROM ANIMALE_ALLOCATO_BLOCCO A1
    JOIN ANIMALE_ALLOCATO_BLOCCO A2 
    ON A1.ETICHETTA_ANIMALE=A2.ETICHETTA_ANIMALE
    WHERE A1.DATA_ALLOCAZIONE < A2.DATA_ALLOCAZIONE
    AND(
        A1.DATA_DEALLOCAZIONE IS NULL
        OR A1.DATA_DEALLOCAZIONE > A2.DATA_ALLOCAZIONE
    );

    IF IS_INVALID <> 0
        THEN 
            RAISE GIA_ALLOCATO;
    END IF;

EXCEPTION 
    WHEN GIA_ALLOCATO
        THEN 
            RAISE_APPLICATION_ERROR(
                -20001,
                'L''animale è già allocato
                in un altro blocco'
            );
END;
/
