--POSSIBILE POICHÈ I CODICI DELLE CELLE IDROPONICHE SONO
--SEMPRE DIVERSI DA QUELLI DEI BLOCCHI ANIMALI

CREATE VIEW ALLOCAZIONI_SENSORI
AS

SELECT 
        SERIALE, 
        NOME_PRODUTTORE,
        NOME_MODELLO,
        CODICE_CELLA_IDR AS CODICE_BLOCCO,
        NOME_STRUTTURA,
        DATA_MONTAGGIO,
        DATA_SMONTAGGIO
    FROM CELLA_IDR_CONTIENE_SENSORE

    UNION

    SELECT 
        SERIALE, 
        NOME_PRODUTTORE,
        NOME_MODELLO,
        NUMERO_BLOCCO AS CODICE_BLOCCO,
        NOME_STRUTTURA,
        DATA_MONTAGGIO,
        DATA_SMONTAGGIO
    FROM BLOCCO_ANIMALE_CONTIENE_SENSORE