CREATE VIEW ELEMENTI_PRODUTTIVI --BLOCCHI ANIMALI E CELLE IDROPONICHE
AS 

SELECT 
    CODICE_CELLA_IDR AS CODICE_ELEMENTO,
    NOME_STRUTTURA,
    DATA_SMONTAGGIO,
    SUPERFICIE_MQ,
    DATA_MONTAGGIO
FROM CELLA_IDROPONICA

UNION
SELECT 
    NUMERO_BLOCCO AS CODICE_ELEMENTO,
    NOME_STRUTTURA,
    DATA_SMONTAGGIO,
    SUPERFICIE_MQ,
    DATA_MONTAGGIO
FROM BLOCCO_ANIMALE;