--PERMETTE DI VERIFICARE SE UNA MISURAZIONE
--SI DISCOSTA MOLTO DALLA MEDIA DI UN SENSORE
--MOSTRANDO L'ANOMALIA

CREATE VIEW ANOMALIA_SENSORE
AS

SELECT 
    RS.SERIALE,
    RS.NOME_PRODUTTORE,
    RS.NOME_MODELLO,
    RS.MISURAZIONE,
    RS.DATA_SECONDI,
    MEDIA.MEDIA,
    ABS(MISURAZIONE-MEDIA.MEDIA)/MISURAZIONE AS ERRORE_RELATIVO

FROM REGISTRAZIONE_SENSORE RS
JOIN(
    SELECT SERIALE, NOME_PRODUTTORE, NOME_MODELLO, SUM(MISURAZIONE)/COUNT(MISURAZIONE) AS MEDIA
    FROM REGISTRAZIONE_SENSORE 
    GROUP BY SERIALE, NOME_PRODUTTORE, NOME_MODELLO
)MEDIA
ON RS.SERIALE=MEDIA.SERIALE
AND RS.NOME_PRODUTTORE=MEDIA.NOME_PRODUTTORE
AND RS.NOME_MODELLO=MEDIA.NOME_MODELLO
WHERE ABS(MISURAZIONE-MEDIA.MEDIA)/MISURAZIONE > 0.5
