CREATE TABLE STRUTTURA(
    NOME_STRUTTURA VARCHAR(60),
    DATA_TERMINAZIONE DATE,
    QUOTA NUMBER(7,2),
    LONGITUDINE NUMBER(9,6),
    LATITUDINE NUMBER(8,6),
    VOLUME_M3 NUMBER(10,2)
        CONSTRAINT NN_STRUTTURA_VOLUME_M3 NOT NULL,
    SUPERFICIE_MQ NUMBER(8,2) 
        CONSTRAINT NN_STRUTTURA_SUPERFICIE_MQ NOT NULL,
    DATA_ATTIVAZIONE DATE
        CONSTRAINT NN_STRUTTURA_DATA_ATTIVAZIONE NOT NULL,
    
    --PK
    CONSTRAINT PK_STRUTTURA PRIMARY KEY (NOME_STRUTTURA),

    --CHECK
    CONSTRAINT CK_STRUTTURA_QUOTA
        CHECK (QUOTA >= 0),
    
    CONSTRAINT CK_STRUTTURA_LONGITUDINE
        CHECK (LONGITUDINE >= -180 AND LONGITUDINE <= 180),
    
    CONSTRAINT CK_STRUTTURA_LATITUDINE
        CHECK (LATITUDINE >= -90 AND LATITUDINE <= 90),

    CONSTRAINT CK_STRUTTURA_VOLUME_M3
        CHECK (VOLUME_M3 > 0),
    
    CONSTRAINT CK_STRUTTURA_SUPERFICIE_MQ
        CHECK (SUPERFICIE_MQ > 0)   
);
