CREATE TABLE AREA_ST(
    CODICE_AREA CHAR(4), --L00L
    NOME_STRUTTURA VARCHAR2(30),
    DATA_TERMINAZIONE DATE,
    TEMPERATURA_MIN NUMBER(3,0) 
        CONSTRAINT NN_AREA_ST_TEMPERATURA_MIN NOT NULL,
    TEMPERATURA_MAX NUMBER(3,0)
        CONSTRAINT NN_AREA_ST_TEMPERATURA_MAX NOT NULL,
    UMIDITA_MIN NUMBER(3,0)
        CONSTRAINT NN_AREA_ST_UMIDITA_MIN NOT NULL,
    UMIDITA_MAX NUMBER(3,0)
        CONSTRAINT NN_AREA_ST_UMIDITA_MAX NOT NULL,
    LIVELLO_SICUREZZA CHAR(2)
        CONSTRAINT NN_AREA_ST_LIVELLO_SICUREZZA NOT NULL,
    PRESSIONE_PA NUMBER(6,0)
        CONSTRAINT NN_AREA_ST_PRESSIONE_PA NOT NULL,
    VOLUME_M3 NUMBER(10,2)
        CONSTRAINT NN_AREA_ST_VOLUME_M3 NOT NULL,
    SUPERFICIE_MQ NUMBER(8,2)
        CONSTRAINT NN_AREA_ST_SUPERFICIE_MQ NOT NULL,
    DATA_ATTIVAZIONE DATE
        CONSTRAINT NN_AREA_ST_DATA_ATTIVAZIONE NOT NULL,



    
    --PK
    CONSTRAINT PK_AREA_ST PRIMARY KEY (CODICE_AREA, NOME_STRUTTURA),

    --FK
    CONSTRAINT FK_AREA_ST_STRUTTURA 
        FOREIGN KEY (NOME_STRUTTURA)
        REFERENCES STRUTTURA (NOME_STRUTTURA),
    
    --CHECK
    CONSTRAINT CK_AREA_ST_CODICE_AREA
        CHECK (REGEXP_LIKE(CODICE_AREA, '^[A-Z][0-9]{2}[A-Z]$')),

    CONSTRAINT CK_AREA_ST_TEMPERATURA_MIN
        CHECK (TEMPERATURA_MIN > 0),
    
    CONSTRAINT CK_AREA_ST_TEMPERATURA_MAX
        CHECK (TEMPERATURA_MAX > 0),

    CONSTRAINT CK_AREA_ST_UMIDITA_MIN
        CHECK (UMIDITA_MIN >= 0 AND UMIDITA_MIN <= 100),

    CONSTRAINT CK_AREA_ST_UMIDITA_MAX
        CHECK (UMIDITA_MAX >= 0 AND UMIDITA_MAX <= 100),

    CONSTRAINT CK_AREA_ST_LIVELLO_SICUREZZA
        CHECK (REGEXP_LIKE(LIVELLO_SICUREZZA, '^L[0-9]$')),

    CONSTRAINT CK_AREA_ST_PRESSIONE_PA
        CHECK (PRESSIONE_PA >= 0),
    
    CONSTRAINT CK_AREA_ST_VOLUME_M3
        CHECK (VOLUME_M3 > 0),
    
    CONSTRAINT CK_AREA_ST_SUPERFICIE_MQ
        CHECK (SUPERFICIE_MQ > 0)
);