CREATE TABLE BLOCCO_ANIMALE(
    NUMERO_BLOCCO CHAR(4), --0000
    NOME_STRUTTURA VARCHAR(60),
    DATA_SMONTAGGIO DATE,
    SUPERFICIE_MQ NUMBER(8,2)
        CONSTRAINT NN_BLOCCO_ANIMALE_SUPERFICIE_MQ NOT NULL,
    DATA_MONTAGGIO DATE
        CONSTRAINT NN_BLOCCO_ANIMALE_DATA_MONTAGGIO NOT NULL,
    --PK
    CONSTRAINT PK_BLOCCO_ANIMALE 
        PRIMARY KEY (NUMERO_BLOCCO, NOME_STRUTTURA),
    
    --FK
    CONSTRAINT FK_BLOCCO_ANIMALE_STR
        FOREIGN KEY (NOME_STRUTTURA)
        REFERENCES STRUTTURA (NOME_STRUTTURA),
    
    --CHECK
    CONSTRAINT CK_BLOCCO_ANIMALE_NUMERO_BLOCCO
        CHECK (REGEXP_LIKE(NUMERO_BLOCCO, '^[0-9]+$')),

    CONSTRAINT CK_BLOCCO_ANIMALE_SUPERFICIE_MQ
        CHECK (SUPERFICIE_MQ > 0)
);