CREATE TABLE BLOCCO_ANIMALE(
    NUMERO_BLOCCO CHAR(4), --0000
    NOME_STRUTTURA VARCHAR2(30),
    CODICE_AREA CHAR(4),
    DATA_SMONTAGGIO DATE,
    SUPERFICIE_MQ NUMBER(8,2)
        CONSTRAINT NN_BLOCCO_ANIMALE_SUPERFICIE_MQ NOT NULL,
    LIMITE_ALLOCAZIONE NUMBER(3)
        CONSTRAINT NN_BLOCCO_ANIMALE_LIMITE_ALLOCAZIONE NOT NULL,
    DATA_MONTAGGIO DATE
        CONSTRAINT NN_BLOCCO_ANIMALE_DATA_MONTAGGIO NOT NULL,
    --PK
    CONSTRAINT PK_BLOCCO_ANIMALE 
        PRIMARY KEY (NUMERO_BLOCCO, CODICE_AREA, NOME_STRUTTURA),
    
    --FK
    CONSTRAINT FK_BLOCCO_ANIMALE_AREA_ST
        FOREIGN KEY (CODICE_AREA, NOME_STRUTTURA)
        REFERENCES AREA_ST (CODICE_AREA, NOME_STRUTTURA),
    
    --CHECK
    CONSTRAINT CK_BLOCCO_ANIMALE_NUMERO_BLOCCO
        CHECK (REGEXP_LIKE(CODICE_AREA, '^[0-9]+$')),

    CONSTRAINT CK_BLOCCO_ANIMALE_SUPERFICIE_MQ
        CHECK (SUPERFICIE_MQ > 0),

    CONSTRAINT CK_BLOCCO_ANIMALE_LIMITE_ALLOCAZIONE
        CHECK (LIMITE_ALLOCAZIONE > 0)
);