CREATE TABLE CELLA_IDROPONICA(
    CODICE_CELLA_IDR CHAR(4), --000A
    NOME_STRUTTURA VARCHAR(60),
    DATA_SMONTAGGIO DATE,
    DATA_MONTAGGIO DATE
        CONSTRAINT NN_CELLA_IDROPONICA_DATA_MONTAGGIO NOT NULL,
    
    --PK
    CONSTRAINT PK_CELLA_IDROPONICA
        PRIMARY KEY (CODICE_CELLA_IDR, NOME_STRUTTURA),

    --FK
    CONSTRAINT FK_CELLA_IDROPONICA_STR
        FOREIGN KEY (NOME_STRUTTURA)
        REFERENCES STRUTTURA (NOME_STRUTTURA),
    
    --CHECK
    CONSTRAINT CK_CELLA_IDROPONICA_CODICE_CELLA_IDR
        CHECK (REGEXP_LIKE(CODICE_CELLA_IDR, '^[0-9]{3}[A-Z]$'))
);