CREATE TABLE SCAFFALE(
    NUMERO_SCAFFALE CHAR(4), --0000 
    CODICE_AREA CHAR(4),
    NOME_STRUTTURA VARCHAR2(30),
    DATA_SMONTAGGIO DATE,
    DATA_MONTAGGIO DATE
        CONSTRAINT NN_SCAFFALE_DATA_MONTAGGIO NOT NULL,
    CAPACITA_KG NUMBER(4,0)
        CONSTRAINT NN_SCAFFALE_CAPACITA_KG NOT NULL,
    DIMENSIONE_M3 NUMBER(4,0)
        CONSTRAINT NN_SCAFFALE_DIMENSIONE_M3 NOT NULL,
    
    --PK
    CONSTRAINT PK_SCAFFALE
        PRIMARY KEY (NUMERO_SCAFFALE, CODICE_AREA, NOME_STRUTTURA),
    
    --FK
    CONSTRAINT FK_SCAFFALE_AREA_ST
        FOREIGN KEY (CODICE_AREA, NOME_STRUTTURA)
        REFERENCES AREA_ST (CODICE_AREA, NOME_STRUTTURA),

    --CHECK 
    CONSTRAINT CK_SCAFFALE_NUMERO_SCAFFALE
        CHECK (REGEXP_LIKE(NUMERO_SCAFFALE, '^[0-9]+$')),
        
    CONSTRAINT CK_SCAFFALE_CAPACITA_KG
        CHECK (CAPACITA_KG > 0),

    CONSTRAINT CK_SCAFFALE_DIMENSIONE_M3
        CHECK (DIMENSIONE_M3 > 0)
);