CREATE TABLE TIPO_SENSORE(
    NOME_PRODUTTORE VARCHAR(60),
    NOME_MODELLO VARCHAR(60),
    VALORE_MIN NUMBER(32,16)
        CONSTRAINT NN_TIPO_SENSORE_VALORE_MIN NOT NULL,
    VALORE_MAX NUMBER(32,16)
        CONSTRAINT NN_TIPO_SENSORE_VALORE_MAX NOT NULL,
    PRECISIONE NUMBER(3,0)
        CONSTRAINT NN_TIPO_SENSORE_PRECISIONE NOT NULL,
    GRANDEZZA_MISURATA VARCHAR(15)
        CONSTRAINT NN_TIPO_SENSORE_GRANDEZZA_MISURATA NOT NULL,
    CODICE_UNITA VARCHAR(10)
        CONSTRAINT NN_TIPO_SENSORE_CODICE_UNITA NOT NULL,
    FREQUENZA_RILEVAMENTO_HZ NUMBER(9,0)
        CONSTRAINT NN_TIPO_SENSORE_FREQUENZA_RILEVAMENTO NOT NULL,

    --PK
    CONSTRAINT PK_TIPO_SENSORE
        PRIMARY KEY (NOME_PRODUTTORE, NOME_MODELLO),

    --FK
    CONSTRAINT FK_TIPO_SENSORE_CODICE_UNITA
        FOREIGN KEY (CODICE_UNITA)
        REFERENCES UNITA_DI_MISURA (CODICE_UNITA),

    --CHECK
    CONSTRAINT CK_TIPO_SENSORE_PRECISIONE
        CHECK (PRECISIONE > 0 AND PRECISIONE <= 100),

    CONSTRAINT CK_TIPO_SENSORE_FREQUENZA_RILEVAMENTO
        CHECK (FREQUENZA_RILEVAMENTO_HZ > 0 )
);
