CREATE TABLE SERBATOIO(
    NUMERO_SERBATOIO CHAR(4), --L000 
    CODICE_AREA CHAR(4),
    NOME_STRUTTURA VARCHAR2(30),
    DATA_SMONTAGGIO DATE,
    DATA_MONTAGGIO DATE
        CONSTRAINT NN_SERBATOIO_DATA_MONTAGGIO NOT NULL,
    PRESSIONE_MAX_PA NUMBER(4,0)
        CONSTRAINT NN_SERBATOIO_PRESSIONE_MAX NOT NULL,
    DIMENSIONE_M3 NUMBER(4,0)
        CONSTRAINT NN_SERBATOIO_DIMENSIONE_M3 NOT NULL,
    
    --PK
    CONSTRAINT PK_SERBATOIO
        PRIMARY KEY (NUMERO_SERBATOIO, CODICE_AREA, NOME_STRUTTURA),
    
    --FK
    CONSTRAINT FK_SERBATOIO_AREA_ST
        FOREIGN KEY (CODICE_AREA, NOME_STRUTTURA)
        REFERENCES AREA_ST (CODICE_AREA, NOME_STRUTTURA),

    --CHECK 
    CONSTRAINT CK_SERBATOIO_NUMERO_SERBATOIO
        CHECK (REGEXP_LIKE(NUMERO_SERBATOIO, '^[A-Z][0-9]+$')),
        
    CONSTRAINT CK_SERBATOIO_PRESSIONE_MAX
        CHECK (PRESSIONE_MAX_PA > 0),

    CONSTRAINT CK_SERBATOIO_DIMENSIONE_M3
        CHECK (DIMENSIONE_M3 > 0)
);