CREATE TABLE SENSORE(
    SERIALE VARCHAR(60),
    NOME_PRODUTTORE VARCHAR(60),
    NOME_MODELLO VARCHAR(60),

    --PK 
    CONSTRAINT PK_SENSORE
        PRIMARY KEY (SERIALE, NOME_PRODUTTORE, NOME_MODELLO),

    --FK 
    CONSTRAINT FK_SENSORE_TIPO_SENSORE
        FOREIGN KEY (NOME_PRODUTTORE, NOME_MODELLO)
        REFERENCES TIPO_SENSORE (NOME_PRODUTTORE, NOME_MODELLO)
);
