CREATE TABLE SENSORE(
    SERIALE VARCHAR(60),
    NOME_PRODUTTORE VARCHAR(60),
    NOME_MODELLO VARCHAR(60),
    NUMERO_BLOCCO CHAR(4),
    NUMERO_CELLA_IDR CHAR(4),
    NOME_STRUTTURA VARCHAR(60)
        CONSTRAINT NN_SENSORE_NOME_STRUTTURA NOT NULL,

    --PK 
    CONSTRAINT PK_SENSORE
        PRIMARY KEY (SERIALE, NOME_PRODUTTORE, NOME_MODELLO),
    --FK 
    CONSTRAINT FK_SENSORE_TIPO_SENSORE
        FOREIGN KEY (NOME_PRODUTTORE, NOME_MODELLO)
        REFERENCES TIPO_SENSORE (NOME_PRODUTTORE, NOME_MODELLO),

    CONSTRAINT FK_SENSORE_BLOCCO_ANIMALE
        FOREIGN KEY (NUMERO_BLOCCO, NOME_STRUTTURA)
        REFERENCES BLOCCO_ANIMALE (NUMERO_BLOCCO, NOME_STRUTTURA),

    CONSTRAINT FK_SENSORE_CELLA_IDR
        FOREIGN KEY (NUMERO_CELLA_IDR, NOME_STRUTTURA)
        REFERENCES CELLA_IDROPONICA (CODICE_CELLA_IDR, NOME_STRUTTURA)    
);