CREATE TABLE REGISTRAZIONE_SENSORE(
    SERIALE VARCHAR(60),
    DATA_SECONDI DATE,
    NOME_PRODUTTORE VARCHAR(60),
    NOME_MODELLO VARCHAR(60),
    MISURAZIONE NUMBER(32,16),
        CONSTRAINT NN_REGISTRAZIONE_SENSORE_MISURAZIONE NOT NULL,

    --PK 
    CONSTRAINT PK_REGISTRAZIONE_SENSORE
        PRIMARY KEY (SERIALE, DATA_SECONDI, NOME_PRODUTTORE, NOME_MODELLO),
    
    --FK 
    CONSTRAINT FK_REGISTRAZIONE_SENSORE_A_SENSORE
        FOREIGN KEY (SERIALE, NOME_PRODUTTORE,NOME_MODELLO)
        REFERENCES SENSORE (SERIALE, NOME_PRODUTTORE,NOME_MODELLO)
);