CREATE TABLE TIPO_SENSORE(
    NOME_PRODUTTORE VARCHAR2(30),
    NOME_MODELLO VARCHAR2(30),
    VALORE_MIN NUMBER(32,16)
        CONSTRAINT NN_TIPO_SENSORE_VALORE_MIN NOT NULL,
    VALORE_MAX NUMBER(32,16)
        CONSTRAINT NN_TIPO_SENSORE_VALORE_MAX NOT NULL,
    PRECISIONE NUMBER(3,0)
        CONSTRAINT NN_TIPO_SENSORE_PRECISIONE NOT NULL,
    GRANDEZZA_MISURATA VARCHAR2(15)
        CONSTRAINT NN_TIPO_SENSORE_GRANDEZZA_MISURATA NOT NULL,
    UNITA_MISURA VARCHAR2(15)
        CONSTRAINT NN_TIPO_SENSORE_UNITA_MISURA NOT NULL,
    FREQUENZA_RILEVAMENTO_HZ NUMBER(9,0)
        CONSTRAINT NN_TIPO_SENSORE_FREQUENZA_RILEVAMENTO NOT NULL,

    --PK
    CONSTRAINT PK_TIPO_SENSORE
        PRIMARY KEY (NOME_PRODUTTORE, NOME_MODELLO),

    --CHECK
    CONSTRAINT CK_TIPO_SENSORE_PRECISIONE
        CHECK (PRECISIONE > 0 AND PRECISIONE <= 100),

    CONSTRAINT CK_TIPO_SENSORE_FREQUENZA_RILEVAMENTO
        CHECK (FREQUENZA_RILEVAMENTO_HZ > 0 )
);