CREATE TABLE SENSORE(
    SERIALE VARCHAR2(30),
    NOME_PRODUTTORE VARCHAR2(30),
    NOME_MODELLO VARCHAR2(30)
        CONSTRAINT NN_SENSORE_NOME_MODELLO NOT NULL,
    CODICE_AREA CHAR(4)
        CONSTRAINT NN_SENSORE_CODICE_AREA NOT NULL,
    NOME_STRUTTURA VARCHAR2(30)
        CONSTRAINT NN_SENSORE_NOME_STRUTTURA NOT NULL,

    --PK 
    CONSTRAINT PK_SENSORE
        PRIMARY KEY (SERIALE, NOME_PRODUTTORE),
    --FK 
    CONSTRAINT FK_SENSORE_TIPO_SENSORE
        FOREIGN KEY (NOME_PRODUTTORE, NOME_MODELLO)
        REFERENCES TIPO_SENSORE (NOME_PRODUTTORE, NOME_MODELLO),

    CONSTRAINT FK_SENSORE_AREA_ST
        FOREIGN KEY (CODICE_AREA, NOME_STRUTTURA)
        REFERENCES AREA_ST (CODICE_AREA, NOME_STRUTTURA)    
);