--NOME_PRODOTTO, FIBRE, PROTEINE, GRASSI, CARBOIDRATI, CODICE_UNITA, IS_EDIBILE
INSERT INTO TIPO_PRODOTTO VALUES ('Latte bovino', 0, 3.2, 3.6, 4.8, 'L', 1);
INSERT INTO TIPO_PRODOTTO VALUES ('Latte caprino', 0, 3.6, 4.1, 4.5, 'L', 1);
INSERT INTO TIPO_PRODOTTO VALUES ('Uova di gallina', 0, 12.6, 10.6, 1.1, 'kg', 1);

INSERT INTO TIPO_PRODOTTO VALUES ('Grano duro', 10.0, 13.0, 2.5, 71.0, 'kg', 1);
INSERT INTO TIPO_PRODOTTO VALUES ('Mais', 7.3, 9.4, 4.7, 74.0, 'kg', 1);
INSERT INTO TIPO_PRODOTTO VALUES ('Pomodoro', 1.2, 0.9, 0.2, 3.9, 'kg', 1);
INSERT INTO TIPO_PRODOTTO VALUES ('Lattuga', 1.3, 1.4, 0.2, 2.9, 'kg', 1);
INSERT INTO TIPO_PRODOTTO VALUES ('Soia', 6.0, 36.0, 20.0, 30.0, 'kg', 1);

INSERT INTO TIPO_PRODOTTO VALUES ('Semi di grano duro', NULL, NULL, NULL, NULL, 'kg', 0);
INSERT INTO TIPO_PRODOTTO VALUES ('Semi di mais', NULL, NULL, NULL, NULL, 'kg', 0);
INSERT INTO TIPO_PRODOTTO VALUES ('Semi di pomodoro', NULL, NULL, NULL, NULL, 'kg', 0);
INSERT INTO TIPO_PRODOTTO VALUES ('Semi di lattuga', NULL, NULL, NULL, NULL, 'kg', 0);
INSERT INTO TIPO_PRODOTTO VALUES ('Semi di soia', NULL, NULL, NULL, NULL, 'kg', 0);

INSERT INTO TIPO_PRODOTTO VALUES ('Soluzione nutritiva idroponica base', NULL, NULL, NULL, NULL, 'L', 0);
INSERT INTO TIPO_PRODOTTO VALUES ('Soluzione nutritiva concentrata', NULL, NULL, NULL, NULL, 'L', 0);

INSERT INTO TIPO_PRODOTTO VALUES ('Antibiotico veterinario pollame', NULL, NULL, NULL, NULL, 'mg', 0);
INSERT INTO TIPO_PRODOTTO VALUES ('Antinfiammatorio veterinario', NULL, NULL, NULL, NULL, 'mL', 0);

INSERT INTO TIPO_PRODOTTO VALUES ('Letame bovino', NULL, NULL, NULL, NULL, 'kg', 0);
INSERT INTO TIPO_PRODOTTO VALUES ('Pollina', NULL, NULL, NULL, NULL, 'kg', 0);
INSERT INTO TIPO_PRODOTTO VALUES ('Acqua potabile', 0, 0, 0, 0, 'L', 1);
COMMIT;
