--NOME_SOSTANZA, IS_POTENZIALE_ALLERGENE, IS_POTENZIALE_INTOLLERANTE
INSERT INTO SOSTANZA VALUES ('Lattosio', 0, 1);
INSERT INTO SOSTANZA VALUES ('Caseina', 1, 0);
INSERT INTO SOSTANZA VALUES ('Proteine dell uovo', 1, 0);
INSERT INTO SOSTANZA VALUES ('Ovoalbumina', 1, 0);
INSERT INTO SOSTANZA VALUES ('Ovomucoide', 1, 0);
INSERT INTO SOSTANZA VALUES ('Glutine', 1, 1);
INSERT INTO SOSTANZA VALUES ('Gliadina', 1, 1);
INSERT INTO SOSTANZA VALUES ('Fruttani', 0, 1);
INSERT INTO SOSTANZA VALUES ('Proteine del mais', 1, 0);
INSERT INTO SOSTANZA VALUES ('Proteine della soia', 1, 0);
INSERT INTO SOSTANZA VALUES ('Lecitina di soia', 1, 0);
INSERT INTO SOSTANZA VALUES ('Lectine vegetali', 0, 1);
INSERT INTO SOSTANZA VALUES ('Fruttosio', 0, 1);
INSERT INTO SOSTANZA VALUES ('Salicilati naturali', 0, 1);
INSERT INTO SOSTANZA VALUES ('Solanina', 0, 1);
COMMIT;
