--CODICE_UNITA, GRANDEZZA, NOME_UNITA
INSERT INTO UNITA_DI_MISURA VALUES ('kg', 'MASSA', 'Chilogrammo');
INSERT INTO UNITA_DI_MISURA VALUES ('g', 'MASSA', 'Grammo');
INSERT INTO UNITA_DI_MISURA VALUES ('mg', 'MASSA', 'Milligrammo');
INSERT INTO UNITA_DI_MISURA VALUES ('L', 'VOLUME', 'Litro');
INSERT INTO UNITA_DI_MISURA VALUES ('mL', 'VOLUME', 'Millilitro');
INSERT INTO UNITA_DI_MISURA VALUES ('kWh', 'ENERGIA', 'Chilowattora');
INSERT INTO UNITA_DI_MISURA VALUES ('%', 'PERCENTUALE', 'Percentuale');
INSERT INTO UNITA_DI_MISURA VALUES ('K', 'TEMPERATURA', 'Kelvin');

COMMIT;
