--TROVARE SE UNA SPECIFICA CELLA IDROPONICA STA EFFETTUANDO UN CICLO DI COLTIVAZIONE IN UNA DATA

SELECT 'TRUE'
FROM CICLO_COLTIVAZIONE CC 
WHERE CC.DATA_FINE_EFFETTIVA IS NULL 
AND CC.CODICE_CELLA_IDR='X'
AND CC.NOME_STRUTTURA='Y';