--TROVARE ETA MASSIMA DEI STADI CRESCITA

SELECT 
    SC.NOME_TIPO_ANIMALE,
    SC.NOME_STADIO_CRESCITA,
    SC.ETA_MINIMA_MESI,
    (
        SELECT MIN(SC2.ETA_MINIMA_MESI) - 1
        FROM STADIO_CRESCITA SC2
        WHERE SC2.NOME_TIPO_ANIMALE = SC.NOME_TIPO_ANIMALE
        AND SC2.ETA_MINIMA_MESI > SC.ETA_MINIMA_MESI
    ) AS ETA_MASSIMA_MESI
FROM STADIO_CRESCITA SC
