--TROVARE LA DURATA DEL CICLO DI COLTIVAZIONE PARTENDO DAI SEMI USATI

SELECT TC.DURATA_CICLO_COLTURA_GIORNI
FROM TIPO_COLTURA TC
JOIN TIPO_COLTURA_USA_SEMI_DI_TIPO TCUDT
ON TCUDT.NOME_TIPO_COLTURA=TC.NOME_TIPO_COLTURA
WHERE TCUDT.NOME_SEMI IN(

    SELECT CCSM.NOME_SEMI
    FROM CICLO_COLT_UTILIZZA_SEMI_MISSIONE CCSM
    WHERE CCSM.DATA_INIZIO=DATE '2025-01-01'
    AND CCSM.CODICE_CELLA_IDR='000A'
    AND CCSM.NOME_STRUTTURA='Struttura Agricola'

    UNION

    SELECT CCPA.NOME_PRODOTTO
    FROM CICLO_COLT_UTILIZZA_PRODUZIONE_AGRICOLA CCPA
    WHERE CCPA.DATA_INIZIO=DATE '2025-01-01'
    AND CCPA.CODICE_CELLA_IDR='000A'
    AND CCPA.NOME_STRUTTURA='Struttura Agricola'
);
