--TROVARE TUTTE LE POSSIBILE PRODUZIONI DI UN TIPO COLTURA E LA QUANTITA DI PRODUZIONE STIMATA

SELECT NOME_PRODOTTO, QUANTITA_STIMATE_PER_KG_SEMI
FROM TIPO_COLTURA_TIPO_PRODOTTO
WHERE NOME_TIPO_COLTURA='Grano duro'