--TROVARE LA QUANTITA DI SEMI UTILIZZATA PER UN CICLO COLTIVAZIONE

SELECT SUM(Q) AS QUANTITA
FROM
(
    SELECT CCSM.QUANTITA AS Q
    FROM CICLO_COLTIVAZIONE CC 
    JOIN CICLO_COLT_UTILIZZA_SEMI_MISSIONE CCSM 
        ON CCSM.DATA_INIZIO=CC.DATA_INIZIO 
        AND CCSM.NOME_STRUTTURA=CC.NOME_STRUTTURA 
        AND CCSM.CODICE_CELLA_IDR=CC.CODICE_CELLA_IDR
    WHERE CC.DATA_INIZIO='X'
    AND CC.NOME_STRUTTURA='Y'
    AND CC.CODICE_CELLA_IDR='Z'

    UNION 

    SELECT CCPA.QUANTITA AS Q
    FROM CICLO_COLTIVAZIONE CC 
    JOIN CICLO_COLT_UTILIZZA_PRODUZIONE_AGRICOLA CCPA
        ON CCPA.DATA_INIZIO=CC.DATA_INIZIO
        AND CCPA.NOME_STRUTTURA=CC.NOME_STRUTTURA
        AND CCPA.CODICE_CELLA_IDR=CC.CODICE_CELLA_IDR
    WHERE CC.DATA_INIZIO='X'
    AND CC.NOME_STRUTTURA='Y'
    AND CC.CODICE_CELLA_IDR='Z'
);