--TROVARE TUTTI I SEMI MISSIONE NON UTILIZZATI E LA LORO PROVENIENZA E QUANTITA




--SE NON È MAI STATO UTILIZZATO UN TIPO DI SEME PRENDO QUANTITA SEMI COME RESIDUA
SELECT 
    SM.*,
    SM.QUANTITA_SEMI AS QUANTITA_RESIDUA
FROM SEMI_MISSIONE SM
WHERE NOT EXISTS(
    SELECT *
    FROM CICLO_COLT_UTILIZZA_SEMI_MISSIONE CCU
    WHERE CCU.DATA_ARRIVO_SEMI=SM.DATA_ARRIVO_SEMI
    AND CCU.NOME_SEMI=SM.NOME_SEMI
)

UNION

--UNISCO CON LA SOTTRAZIONE DELLA SOMMA DI TUTTI I SEMI UTILIZZATI DI UN CERTO TIPO
SELECT 
    SM.*,
    SM.QUANTITA_SEMI-(
        SELECT SUM(CCU.QUANTITA)
        FROM CICLO_COLT_UTILIZZA_SEMI_MISSIONE CCU
        WHERE CCU.DATA_ARRIVO_SEMI=SM.DATA_ARRIVO_SEMI
        AND CCU.NOME_SEMI=SM.NOME_SEMI
    ) AS QUANTITA_RESIDUA
FROM SEMI_MISSIONE SM
WHERE EXISTS( --PRENDO SOLO I SEMI UTILIZZATI ALMENO UNA VOLTA PER EVITARE NULL
    SELECT *
    FROM CICLO_COLT_UTILIZZA_SEMI_MISSIONE CCU
    WHERE CCU.DATA_ARRIVO_SEMI=SM.DATA_ARRIVO_SEMI
    AND CCU.NOME_SEMI=SM.NOME_SEMI
)
AND SM.QUANTITA_SEMI>( --LA QUANTITA NON PUO ESSERE NEGATIVA
    SELECT SUM(CCU.QUANTITA)
    FROM CICLO_COLT_UTILIZZA_SEMI_MISSIONE CCU
    WHERE CCU.DATA_ARRIVO_SEMI=SM.DATA_ARRIVO_SEMI
    AND CCU.NOME_SEMI=SM.NOME_SEMI
);