--TROVARE TUTTI I SEMI PRODUZIONE AGRICOLA NON UTILIZZATI E LA LORO PROVENIENZA E QUANTITA


SELECT 
    PA.DATA_PRODUZIONE_AGRICOLA,
    PA.DATA_INIZIO_CICLO_COLTIVAZIONE,
    PA.CODICE_CELLA_IDR,
    PA.NOME_STRUTTURA,
    PA.NOME_PRODOTTO,
    PA.QUANTITA AS QUANTITA_RESIDUA
FROM PRODUZIONE_AGRICOLA PA
WHERE PA.NOME_PRODOTTO IN(
    SELECT TCUDT.NOME_SEMI
    FROM TIPO_COLTURA_USA_SEMI_DI_TIPO TCUDT
)
AND NOT EXISTS(
    SELECT *
    FROM CICLO_COLT_UTILIZZA_PRODUZIONE_AGRICOLA CCPA
    WHERE CCPA.DATA_PRODUZIONE_AGRICOLA=PA.DATA_PRODUZIONE_AGRICOLA
    AND CCPA.DATA_INIZIO_CICLO_COLTIVAZIONE=PA.DATA_INIZIO_CICLO_COLTIVAZIONE
    AND CCPA.CODICE_CELLA_IDR_PROD_AGR=PA.CODICE_CELLA_IDR
    AND CCPA.NOME_STRUTTURA_PROD_AGR=PA.NOME_STRUTTURA
    AND CCPA.NOME_PRODOTTO=PA.NOME_PRODOTTO
)

UNION

SELECT 
    PA.DATA_PRODUZIONE_AGRICOLA,
    PA.DATA_INIZIO_CICLO_COLTIVAZIONE,
    PA.CODICE_CELLA_IDR,
    PA.NOME_STRUTTURA,
    PA.NOME_PRODOTTO,
    PA.QUANTITA-(
        SELECT SUM(CCPA.QUANTITA)
        FROM CICLO_COLT_UTILIZZA_PRODUZIONE_AGRICOLA CCPA
        WHERE CCPA.DATA_PRODUZIONE_AGRICOLA=PA.DATA_PRODUZIONE_AGRICOLA
        AND CCPA.DATA_INIZIO_CICLO_COLTIVAZIONE=PA.DATA_INIZIO_CICLO_COLTIVAZIONE
        AND CCPA.CODICE_CELLA_IDR_PROD_AGR=PA.CODICE_CELLA_IDR
        AND CCPA.NOME_STRUTTURA_PROD_AGR=PA.NOME_STRUTTURA
        AND CCPA.NOME_PRODOTTO=PA.NOME_PRODOTTO
    ) AS QUANTITA_RESIDUA
FROM PRODUZIONE_AGRICOLA PA
WHERE PA.NOME_PRODOTTO IN(
    SELECT TCUDT.NOME_SEMI
    FROM TIPO_COLTURA_USA_SEMI_DI_TIPO TCUDT
)
AND EXISTS(
    SELECT *
    FROM CICLO_COLT_UTILIZZA_PRODUZIONE_AGRICOLA CCPA
    WHERE CCPA.DATA_PRODUZIONE_AGRICOLA=PA.DATA_PRODUZIONE_AGRICOLA
    AND CCPA.DATA_INIZIO_CICLO_COLTIVAZIONE=PA.DATA_INIZIO_CICLO_COLTIVAZIONE
    AND CCPA.CODICE_CELLA_IDR_PROD_AGR=PA.CODICE_CELLA_IDR
    AND CCPA.NOME_STRUTTURA_PROD_AGR=PA.NOME_STRUTTURA
    AND CCPA.NOME_PRODOTTO=PA.NOME_PRODOTTO
)
AND PA.QUANTITA>(
    SELECT SUM(CCPA.QUANTITA)
    FROM CICLO_COLT_UTILIZZA_PRODUZIONE_AGRICOLA CCPA
    WHERE CCPA.DATA_PRODUZIONE_AGRICOLA=PA.DATA_PRODUZIONE_AGRICOLA
    AND CCPA.DATA_INIZIO_CICLO_COLTIVAZIONE=PA.DATA_INIZIO_CICLO_COLTIVAZIONE
    AND CCPA.CODICE_CELLA_IDR_PROD_AGR=PA.CODICE_CELLA_IDR
    AND CCPA.NOME_STRUTTURA_PROD_AGR=PA.NOME_STRUTTURA
    AND CCPA.NOME_PRODOTTO=PA.NOME_PRODOTTO
);