CREATE TABLE MODALITA_COLTIVAZIONE(
    NOME_MODALITA_COLTIVAZIONE VARCHAR(60),
    NOME_PRODOTTO VARCHAR(60) --SOLUZIONE NUTRITIVA
        CONSTRAINT NN_MODALITA_COLTIVAZIONE_NOME_PRODOTTO NOT NULL,
    PH_MIN NUMBER(2,1)
        CONSTRAINT NN_MODALITA_COLTIVAZIONE_PH_MIN NOT NULL,
    PH_MAX NUMBER(2,1)
        CONSTRAINT NN_MODALITA_COLTIVAZIONE_PH_MAX NOT NULL,
    TEMPERATURA_MIN NUMBER(4,0)
        CONSTRAINT NN_MODALITA_COLTIVAZIONE_TEMPERATURA_MIN NOT NULL,
    TEMPERATURA_MAX NUMBER(4,0)
        CONSTRAINT NN_MODALITA_COLTIVAZIONE_TEMPERATURA_MAX NOT NULL,
    UMIDITA_MIN NUMBER(3,0)
        CONSTRAINT NN_MODALITA_COLTIVAZIONE_UMIDITA_MIN NOT NULL,
    UMIDITA_MAX NUMBER(3,0)
        CONSTRAINT NN_MODALITA_COLTIVAZIONE_UMIDITA_MAX NOT NULL,
    IMPOLLINAZIONE NUMBER(1,0)
        CONSTRAINT NN_MODALITA_COLTIVAZIONE_IMPOLLINAZIONE NOT NULL,
    SISTEMA_ILLUMINAZIONE VARCHAR(30)
        CONSTRAINT NN_MODALITA_COLTIVAZIONE_SISTEMA_ILLUMINAZIONE NOT NULL,
    ACQUA_ML_ORA NUMBER(5,2)
        CONSTRAINT NN_MODALITA_COLTIVAZIONE_ACQUA_ML_ORA NOT NULL,
    ORE_LUCE_GIORNO NUMBER(2,0)
        CONSTRAINT NN_MODALITA_COLTIVAZIONE_ORE_LUCE_GIORNO NOT NULL,
    QUANTITA_SOLUZIONE_ML_ORA NUMBER(5,2) 
        CONSTRAINT NN_MODALITA_COLTIVAZIONE_QUANTITA_SOLUZIONE_ML_ORA NOT NULL,

    --PK
    CONSTRAINT PK_MODALITA_COLTIVAZIONE PRIMARY KEY (NOME_MODALITA_COLTIVAZIONE),

    --FK
    CONSTRAINT FK_MODALITA_COLTIVAZIONE_TIPO_PRODOTTO
        FOREIGN KEY (NOME_PRODOTTO)
        REFERENCES TIPO_PRODOTTO (NOME_PRODOTTO),

    --CHECK
    CONSTRAINT CK_MODALITA_COLTIVAZIONE_PH_MIN
        CHECK (PH_MIN >= 0 AND PH_MIN <= 14),

    CONSTRAINT CK_MODALITA_COLTIVAZIONE_PH_MAX
        CHECK (PH_MAX >= 0 AND PH_MAX <= 14),
    
    CONSTRAINT CK_MODALITA_COLTIVAZIONE_TEMPERATURA_MIN
        CHECK (TEMPERATURA_MIN > 0),

    CONSTRAINT CK_MODALITA_COLTIVAZIONE_TEMPERATURA_MAX
        CHECK (TEMPERATURA_MAX > 0),

    CONSTRAINT CK_MODALITA_COLTIVAZIONE_UMIDITA_MIN
        CHECK (UMIDITA_MIN >= 0 AND UMIDITA_MIN <= 100),

    CONSTRAINT CK_MODALITA_COLTIVAZIONE_UMIDITA_MAX
        CHECK (UMIDITA_MAX >= 0 AND UMIDITA_MAX <= 100),

    CONSTRAINT CK_MODALITA_COLTIVAZIONE_IMPOLLINAZIONE
        CHECK (IMPOLLINAZIONE IN (1, 0)),

    CONSTRAINT CK_MODALITA_COLTIVAZIONE_SISTEMA_ILLUMINAZIONE
        CHECK (SISTEMA_ILLUMINAZIONE IN (
            'LED_FULL',
            'LED_BLU',
            'LED_VIOLA',
            'LED_BIANCO',
            'FLUORESCENTE',
            'NATURALE'
            )),

    CONSTRAINT CK_MODALITA_COLTIVAZIONE_ACQUA_ML_ORA
        CHECK (ACQUA_ML_ORA >= 0),
    
    CONSTRAINT CK_MODALITA_COLTIVAZIONE_ORE_LUCE_GIORNO
        CHECK (ORE_LUCE_GIORNO >= 0 AND ORE_LUCE_GIORNO <= 24),

    CONSTRAINT CK_MODALITA_COLTIVAZIONE_QUANTITA_SOLUZIONE_ML_ORA
        CHECK (QUANTITA_SOLUZIONE_ML_ORA >= 0)
);

COMMIT;