CREATE TABLE TIPO_COLTURA(
    NOME_TIPO_COLTURA VARCHAR(60),
    NOME_SEMI VARCHAR(60)
        CONSTRAINT NN_TIPO_COLTURA_NOME_SEMI NOT NULL,
    CATEGORIA_COLTURA VARCHAR(60)
        CONSTRAINT NN_TIPO_COLTURA_CATEGORIA NOT NULL,
    DURATA_CICLO_COLTURA_GIORNI NUMBER(4,0)
        CONSTRAINT NN_TIPO_COLTURA_DURATA_CICLO_COLTURA NOT NULL,

    --PK
    CONSTRAINT PK_TIPO_COLTURA
        PRIMARY KEY (NOME_TIPO_COLTURA),

    --FK
    CONSTRAINT FK_TIPO_COLTURA_TIPO_PRODOTTO
        FOREIGN KEY (NOME_SEMI)
        REFERENCES TIPO_PRODOTTO (NOME_PRODOTTO),
    
    --CHECK
    CONSTRAINT CK_TIPO_COLTURA_CATEGORIA
        CHECK (CATEGORIA_COLTURA IN (
            'CEREALI',
            'LEGUMI',
            'ORTAGGI',
            'OLEAGINOSE',
            'TESSILI',
            'FRUTTA'
        )),

    CONSTRAINT CK_TIPO_COLTURA_DURATA_CICLO_COLTURA
        CHECK (DURATA_CICLO_COLTURA_GIORNI > 0)
);
