CREATE TABLE CICLO_COLTIVAZIONE(
    DATA_INIZIO DATE,
    CODICE_CELLA_IDR CHAR(4),
    CODICE_AREA CHAR(4),
    NOME_STRUTTURA VARCHAR(60),
    DATA_FINE_EFFETTIVA DATE,
    QUANTITA_SEMI NUMBER(4,2)
        CONSTRAINT NN_CICLO_COLTIVAZIONE_QUANTITA_SEMI_KG NOT NULL,
    NOME_MOD_COLTIVAZIONE VARCHAR(60)
        CONSTRAINT NN_CICLO_COLTIVAZIONE_NOME_MOD_COLTIVAZIONE NOT NULL,
    NOME_TIPO_COLTURA VARCHAR(60)
        CONSTRAINT NN_CICLO_COLTIVAZIONE_NOME_TIPO_COLTURA NOT NULL,

    --PK
    CONSTRAINT PK_CICLO_COLTIVAZIONE
        PRIMARY KEY (DATA_INIZIO, CODICE_CELLA_IDR, CODICE_AREA, NOME_STRUTTURA),
    
    --FK
    CONSTRAINT FK_CICLO_COLTIVAZIONE_CELLA_IDROPONICA
        FOREIGN KEY (CODICE_CELLA_IDR, CODICE_AREA, NOME_STRUTTURA)
        REFERENCES CELLA_IDROPONICA (CODICE_CELLA_IDR, CODICE_AREA, NOME_STRUTTURA),
    
    CONSTRAINT FK_CICLO_COLTIVAZIONE_MOD_COLTIVAZIONE
        FOREIGN KEY (NOME_MOD_COLTIVAZIONE)
        REFERENCES MODALITA_COLTIVAZIONE (NOME_MODALITA_COLTIVAZIONE),
    
    CONSTRAINT FK_CICLO_COLTIVAZIONE_TIPO_COLTURA
        FOREIGN KEY (NOME_TIPO_COLTURA)
        REFERENCES TIPO_COLTURA (NOME_TIPO_COLTURA),

    --CHECK
    CONSTRAINT CK_CICLO_COLTIVAZIONE_QUANTITA_SEMI
        CHECK (QUANTITA_SEMI > 0)
);