CREATE TABLE PRODUZIONE_AGRICOLA(
    DATA_PRODUZIONE_AGRICOLA DATE,
    DATA_INIZIO_CICLO_COLTIVAZIONE DATE,
    CODICE_CELLA_IDR CHAR(4),
    CODICE_AREA CHAR(4),
    NOME_STRUTTURA VARCHAR(60),
    NOME_PRODOTTO VARCHAR(60),
    QUANTITA NUMBER(10,2)
        CONSTRAINT NN_PRODUZIONE_AGRICOLA_QUANTITA NOT NULL,

    --PK
    CONSTRAINT PK_PRODUZIONE_AGRICOLA
        PRIMARY KEY (
            DATA_PRODUZIONE_AGRICOLA,
            DATA_INIZIO_CICLO_COLTIVAZIONE,
            CODICE_CELLA_IDR,
            CODICE_AREA,
            NOME_STRUTTURA,
            NOME_PRODOTTO
        ),

    --FK
    CONSTRAINT FK_PRODUZIONE_AGRICOLA_CICLO_COLTIVAZIONE
        FOREIGN KEY (DATA_INIZIO_CICLO_COLTIVAZIONE,
            CODICE_CELLA_IDR,
            CODICE_AREA,
            NOME_STRUTTURA
        )
        REFERENCES CICLO_COLTIVAZIONE (DATA_INIZIO,
            CODICE_CELLA_IDR,
            CODICE_AREA,
            NOME_STRUTTURA
        ),

    CONSTRAINT FK_PRODUZIONE_AGRICOLA_TIPO_PRODOTTO
        FOREIGN KEY (NOME_PRODOTTO)
        REFERENCES TIPO_PRODOTTO (NOME_PRODOTTO),
    
    --CHECK
    CONSTRAINT CK_PRODUZIONE_AGRICOLA_QUANTITA
        CHECK (QUANTITA > 0)
);