CREATE TABLE SEMI_MISSIONE(
    NOME_SEMI VARCHAR(60), --REFERENZA A TIPO PRODOTTO
    DATA_ARRIVO_SEMI DATE,
    QUANTITA_SEMI NUMBER(10,2) --NELL'UNITA DI MISURA DEFINITA NELLA TUPLA IN PRODOTTO DEL RELATIVO SEME
        CONSTRAINT NN_SEMI_MISSIONE_QUANTITA NOT NULL,

    --PK
    CONSTRAINT PK_SEMI_MISSIONE
        PRIMARY KEY (NOME_SEMI, DATA_ARRIVO_SEMI),

    --FK
    CONSTRAINT FK_SEMI_MISSIONE_PRODOTTO
        FOREIGN KEY (NOME_SEMI)
        REFERENCES TIPO_PRODOTTO (NOME_PRODOTTO),

    --CK
    CONSTRAINT CK_SEMI_MISSIONE_QUANTITA
        CHECK(QUANTITA_SEMI>0)
);