CREATE VIEW SEMI_MISSISONE_UTILIZZATI 
AS 

SELECT SM.NOME_SEMI, SM.DATA_ARRIVO_SEMI, NVL(SUM(CC.QUANTITA), 0) AS SEMI_UTILIZZATI
FROM SEMI_MISSIONE SM
LEFT JOIN CICLO_COLT_UTILIZZA_SEMI_MISSIONE CC
ON CC.NOME_SEMI=SM.NOME_SEMI 
AND CC.DATA_ARRIVO_SEMI=SM.DATA_ARRIVO_SEMI
GROUP BY SM.NOME_SEMI,  SM.DATA_ARRIVO_SEMI;