CREATE VIEW CONSUMO_CICLI_COLTIVAZIONE_2
AS

SELECT NOME_PRODOTTO, SUM(QUANTITA) AS QUANTITA
FROM (
    SELECT 
        NOME_PRODOTTO,
        QUANTITA_SOLUZIONE AS QUANTITA
    FROM CONSUMO_CICLI_COLTIVAZIONE

    UNION ALL 

    SELECT 
        'Acqua potabile' AS NOME_PRODOTTO,   
        SUM(QUANTITA_ACQUA) AS QUANTITA
    FROM CONSUMO_CICLI_COLTIVAZIONE
)
GROUP BY NOME_PRODOTTO;