--CREAZIONE TABELLA PRODOTTO


CREATE TABLE TIPO_PRODOTTO(
    NOME_PRODOTTO VARCHAR2(30),
    ALCOL NUMBER(4,2), --QUANTITA IN GRAMMI PER 100 GRAMMI DI PRODOTTO
    FIBRE NUMBER(4,2),
    PROTEINE NUMBER(4,2),
    GRASSI NUMBER(4,2),
    CARBOIDRATI NUMBER(4,2),
    UNITA_MISURA VARCHAR2(20)
        CONSTRAINT NN_PRODOTTO_UNITA_MISURA NOT NULL,
    IS_EDIBILE NUMBER(1,0) --NECESSARIO PER LA SPECIALIZZAZIONE DI PRODOTTO IN PRODOTTO_EDIBILE
        CONSTRAINT NN_PRODOTTO_IS_EDIBILE NOT NULL,
    
    --PK
    CONSTRAINT PK_PRODOTTO PRIMARY KEY (NOME_PRODOTTO),

    --CHECK
    CONSTRAINT CK_PRODOTTO_ALCOL
        CHECK (ALCOL >= 0),

    CONSTRAINT CK_PRODOTTO_FIBRE
        CHECK (FIBRE >= 0),

    CONSTRAINT CK_PRODOTTO_PROTEINE
        CHECK (PROTEINE >= 0),

    CONSTRAINT CK_PRODOTTO_GRASSI
        CHECK (GRASSI >= 0),

    CONSTRAINT CK_PRODTTO_CARBOIDRATI
        CHECK (CARBOIDRATI >= 0),

    CONSTRAINT CK_PRODOTTO_IS_EDIBILE
        CHECK (IS_EDIBILE IN (1, 0))  
);


--CREAZIONE SOSTANZA


CREATE TABLE SOSTANZA(
    NOME_SOSTANZA VARCHAR2(30),
    IS_POTENZIALE_ALLERGENE NUMBER(1,0),
    IS_POTENZIALE_INTOLLERANTE NUMBER(1,0),
    

    --PK
    CONSTRAINT PK_SOSTANZA PRIMARY KEY (NOME_SOSTANZA),

    --CHECK
    CONSTRAINT CK_SOSTANZA_IS_POTENZIALE_ALLERGENE
        CHECK (IS_POTENZIALE_ALLERGENE IN (1, 0)),
    
    CONSTRAINT CK_SOSTANZA_IS_POTENZIALE_INTOLLERANTE
        CHECK (IS_POTENZIALE_INTOLLERANTE IN (1, 0))
);