--CREAZIONE STRUTTURA

CREATE TABLE STRUTTURA(
    NOME_STRUTTURA VARCHAR2(30),
    DATA_TERMINAZIONE DATE,
    QUOTA NUMBER(7,2)
        CONSTRAINT NN_STRUTTURA_QUOTA NOT NULL,
    LONGITUDINE NUMBER(9,6)
        CONSTRAINT NN_STRUTTURA_LONGITUDINE NOT NULL,
    LATITUDINE NUMBER(8,6)
        CONSTRAINT NN_STRUTTURA_LATITUDINE NOT NULL,
    VOLUME_M3 NUMBER(10,2)
        CONSTRAINT NN_STRTTURA_VOLUME_M3 NOT NULL,
    SUPERFICIE_MQ NUMBER(8,2) 
        CONSTRAINT NN_STRUTTURA_SUPERFICIE_MQ NOT NULL,
    DATA_ATTIVAZIONE DATE
        CONSTRAINT NN_STRUTTURA_DATA_ATTIVAZIONE NOT NULL,
    
    --PK
    CONSTRAINT PK_STRUTTRA PRIMARY KEY (NOME_STRUTTURA),

    --CHECK
    CONSTRAINT CK_STRUTTURA_QUOTA
        CHECK (QUOTA >= 0),
    
    CONSTRAINT CK_STRUTTURA_LONGITUDINE
        CHECK (LONGITUDINE >= -180 AND LONGITUDINE <= 180),
    
    CONSTRAINT CK_STRUTTURA_LATITUDINE
        CHECK (LATITUDINE >= -90 AND LATITUDINE <= 90),

    CONSTRAINT CK_STRUTTURA_VOLUME_M3
        CHECK (VOLUME_M3 > 0),
    
    CONSTRAINT CK_STRUTTURA_SUPERFICIE_MQ
        CHECK (SUPERFICIE_MQ > 0),
        
    CONSTRAINT CK_STRUTTURA_DATA_ATTIVAZIONE
        CHECK (DATA_ATTIVAZIONE >= DATE '2026-01-01')
    
);


--CREAZIONE AREA_ST


CREATE TABLE AREA_ST(
    CODICE_AREA CHAR(4), --L00L
    NOME_STRUTTURA VARCHAR2(30),
    DATA_TERMINAZIONE DATE,
    TEMPERATURA_MIN NUMBER(3,0) 
        CONSTRAINT NN_AREA_ST_TEMPERATURA_MIN NOT NULL,
    TEMPERATURA_MAX NUMBER(3,0)
        CONSTRAINT NN_AREA_ST_TEMPERATURA_MAX NOT NULL,
    UMIDITA_MIN NUMBER(3,0)
        CONSTRAINT NN_AREA_ST_UMIDITA_MIN NOT NULL,
    UMIDITA_MAX NUMBER(3,0)
        CONSTRAINT NN_AREA_ST_UMIDITA_MAX NOT NULL,
    LIVELLO_SICUREZZA CHAR(2)
        CONSTRAINT NN_AREA_ST_LIVELLO_SICUREZZA NOT NULL,
    PRESSIONE_PA NUMBER(6,0)
        CONSTRAINT NN_AREA_ST_PRESSIONE_PA NOT NULL,
    VOLUME_M3 NUMBER(10,2)
        CONSTRAINT NN_AREA_ST_VOLUME_M3 NOT NULL,
    SUPERFICIE_MQ NUMBER(8,2)
        CONSTRAINT NN_AREA_ST_SUPERFICIE_MQ NOT NULL,
    DATA_ATTIVAZIONE DATE
        CONSTRAINT NN_AREA_ST_DATA_ATTIVAZIONE NOT NULL,



    
    --PK
    CONSTRAINT PK_AREA_ST PRIMARY KEY (CODICE_AREA, NOME_STRUTTURA),

    --FK
    CONSTRAINT FK_AREA_ST_STRUTTURA 
        FOREIGN KEY (NOME_STRUTTURA)
        REFERENCES STRUTTURA (NOME_STRUTTURA),
    
    --CHECK
    CONSTRAINT CK_AREA_ST_CODICE_AREA
        CHECK (REGEXP_LIKE(CODICE_AREA, '^[A-Z][0-9]{2}[A-Z]$')),

    CONSTRAINT CK_AREA_ST_TEMPERATURA_MIN
        CHECK (TEMPERATURA_MIN > 0),
    
    CONSTRAINT CK_AREA_ST_TEMPERATURA_MAX
        CHECK (TEMPERATURA_MAX > 0),

    CONSTRAINT CK_AREA_ST_UMIDITA_MIN
        CHECK (UMIDITA_MIN >= 0 AND UMIDITA_MIN <= 100),

    CONSTRAINT CK_AREA_ST_UMIDITA_MAX
        CHECK (UMIDITA_MAX >= 0 AND UMIDITA_MAX <= 100),

    CONSTRAINT CK_AREA_ST_LIVELLO_SICUREZZA
        CHECK (REGEXP_LIKE(LIVELLO_SICUREZZA, '^L[0-9]$')),

    CONSTRAINT CK_AREA_ST_PRESSIONE_PA
        CHECK (PRESSIONE_PA >= 0),
    
    CONSTRAINT CK_AREA_ST_VOLUME_M3
        CHECK (VOLUME_M3 > 0),
    
    CONSTRAINT CK_AREA_ST_SUPERFICIE_MQ
        CHECK (SUPERFICIE_MQ > 0)
);


--CREAZIONE BLOCCO_ANIMALE


CREATE TABLE BLOCCO_ANIMALE(
    NUMERO_BLOCCO CHAR(4), --0000
    NOME_STRUTTURA VARCHAR2(30),
    CODICE_AREA CHAR(4),
    DATA_SMONTAGGIO DATE,
    SUPERFICIE_MQ NUMBER(8,2)
        CONSTRAINT NN_BLOCCO_ANIMALE_SUPERFICIE_MQ NOT NULL,
    LIMITE_ALLOCAZIONE NUMBER(3)
        CONSTRAINT NN_BLOCCO_ANIMALE_LIMITE_ALLOCAZIONE NOT NULL,
    DATA_MONTAGGIO DATE
        CONSTRAINT NN_BLOCCO_ANIMALE_DATA_MONTAGGIO NOT NULL,
    --PK
    CONSTRAINT PK_BLOCCO_ANIMALE 
        PRIMARY KEY (NUMERO_BLOCCO, CODICE_AREA, NOME_STRUTTURA),
    
    --FK
    CONSTRAINT FK_BLOCCO_ANIMALE_AREA_ST
        FOREIGN KEY (CODICE_AREA, NOME_STRUTTURA)
        REFERENCES AREA_ST (CODICE_AREA, NOME_STRUTTURA),
    
    --CHECK
    CONSTRAINT CK_BLOCCO_ANIMALE_NUMERO_BLOCCO
        CHECK (REGEXP_LIKE(CODICE_AREA, '^[0-9]+$')),

    CONSTRAINT CK_BLOCCO_ANIMALE_SUPERFICIE_MQ
        CHECK (SUPERFICIE_MQ > 0),

    CONSTRAINT CK_BLOCCO_ANIMALE_LIMITE_ALLOCAZIONE
        CHECK (LIMITE_ALLOCAZIONE > 0)
);


--CREAZIZONE SCAFFALE


CREATE TABLE SCAFFALE(
    NUMERO_SCAFFALE CHAR(4), --0000 
    CODICE_AREA CHAR(4),
    NOME_STRUTTURA VARCHAR2(30),
    DATA_SMONTAGGIO DATE,
    DATA_MONTAGGIO DATE
        CONSTRAINT NN_SCAFFALE_DATA_MONTAGGIO NOT NULL,
    CAPACITA_KG NUMBER(4,0)
        CONSTRAINT NN_SCAFFALE_CAPACITA_KG NOT NULL,
    DIMENSIONE_M3 NUMBER(4,0)
        CONSTRAINT NN_SCAFFALE_DIMENSIONE_M3 NOT NULL,
    
    --PK
    CONSTRAINT PK_SCAFFALE
        PRIMARY KEY (NUMERO_SCAFFALE, CODICE_AREA, NOME_STRUTTURA),
    
    --FK
    CONSTRAINT FK_SCAFFALE_AREA_ST
        FOREIGN KEY (CODICE_AREA, NOME_STRUTTURA)
        REFERENCES AREA_ST (CODICE_AREA, NOME_STRUTTURA),

    --CHECK 
    CONSTRAINT CK_SCAFFALE_NUMERO_SCAFFALE
        CHECK (REGEXP_LIKE(NUMERO_SCAFFALE, '^[0-9]+$')),
        
    CONSTRAINT CK_SCAFFALE_CAPACITA_KG
        CHECK (CAPACITA_KG > 0),

    CONSTRAINT CK_SCAFFALE_DIMENSIONE_M3
        CHECK (DIMENSIONE_M3 > 0)
);


--CREAZIONE SERBATOIO


CREATE TABLE SERBATOIO(
    NUMERO_SERBATOIO CHAR(4), --L000 
    CODICE_AREA CHAR(4),
    NOME_STRUTTURA VARCHAR2(30),
    DATA_SMONTAGGIO DATE,
    DATA_MONTAGGIO DATE
        CONSTRAINT NN_SERBATOIO_DATA_MONTAGGIO NOT NULL,
    PRESSIONE_MAX_PA NUMBER(4,0)
        CONSTRAINT NN_SERBATOIO_PRESSIONE_MAX NOT NULL,
    DIMENSIONE_M3 NUMBER(4,0)
        CONSTRAINT NN_SERBATOIO_DIMENSIONE_M3 NOT NULL,
    
    --PK
    CONSTRAINT PK_SERBATOIO
        PRIMARY KEY (NUMERO_SERBATOIO, CODICE_AREA, NOME_STRUTTURA),
    
    --FK
    CONSTRAINT FK_SERBATOIO_AREA_ST
        FOREIGN KEY (CODICE_AREA, NOME_STRUTTURA)
        REFERENCES AREA_ST (CODICE_AREA, NOME_STRUTTURA),

    --CHECK 
    CONSTRAINT CK_SERBATOIO_NUMERO_SERBATOIO
        CHECK (REGEXP_LIKE(NUMERO_SERBATOIO, '^[A-Z][0-9]+$')),
        
    CONSTRAINT CK_SERBATOIO_PRESSIONE_MAX
        CHECK (PRESSIONE_MAX_PA > 0),

    CONSTRAINT CK_SERBATOIO_DIMENSIONE_M3
        CHECK (DIMENSIONE_M3 > 0)
);


--CREAZIONE TIPO_SENSORE


CREATE TABLE TIPO_SENSORE(
    NOME_PRODUTTORE VARCHAR2(30),
    NOME_MODELLO VARCHAR2(30),
    VALORE_MIN NUMBER(32,16)
        CONSTRAINT NN_TIPO_SENSORE_VALORE_MIN NOT NULL,
    VALORE_MAX NUMBER(32,16)
        CONSTRAINT NN_TIPO_SENSORE_VALORE_MAX NOT NULL,
    PRECISIONE NUMBER(3,0)
        CONSTRAINT NN_TIPO_SENSORE_PRECISIONE NOT NULL,
    GRANDEZZA_MISURATA VARCHAR2(15)
        CONSTRAINT NN_TIPO_SENSORE_GRANDEZZA_MISURATA NOT NULL,
    UNITA_MISURA VARCHAR2(15)
        CONSTRAINT NN_TIPO_SENSORE_UNITA_MISURA NOT NULL,
    FREQUENZA_RILEVAMENTO_HZ NUMBER(9,0)
        CONSTRAINT NN_TIPO_SENSORE_FREQUENZA_RILEVAMENTO NOT NULL,

    --PK
    CONSTRAINT PK_TIPO_SENSORE
        PRIMARY KEY (NOME_PRODUTTORE, NOME_MODELLO),

    --CHECK
    CONSTRAINT CK_TIPO_SENSORE_PRECISIONE
        CHECK (PRECISIONE > 0 AND PRECISIONE <= 100),

    CONSTRAINT CK_TIPO_SENSORE_FREQUENZA_RILEVAMENTO
        CHECK (FREQUENZA_RILEVAMENTO_HZ > 0 )

);


--CREAZIONE SENSORE 


CREATE TABLE SENSORE(
    SERIALE VARCHAR2(30),
    NOME_PRODUTTORE VARCHAR2(30),
    NOME_MODELLO VARCHAR2(30)
        CONSTRAINT NN_SENSORE_NOME_MODELLO NOT NULL,
    CODICE_AREA CHAR(4)
        CONSTRAINT NN_SENSORE_CODICE_AREA NOT NULL,
    NOME_STRUTTURA VARCHAR2(30)
        CONSTRAINT NN_SENSORE_NOME_STRUTTURA NOT NULL,

    --PK 
    CONSTRAINT PK_SENSORE
        PRIMARY KEY (SERIALE, NOME_PRODUTTORE),
    --FK 
    CONSTRAINT FK_SENSORE_TIPO_SENSORE
        FOREIGN KEY (NOME_PRODUTTORE, NOME_MODELLO)
        REFERENCES TIPO_SENSORE (NOME_PRODUTTORE, NOME_MODELLO),

    CONSTRAINT FK_SENSORE_AREA_ST
        FOREIGN KEY (CODICE_AREA, NOME_STRUTTURA)
        REFERENCES AREA_ST (CODICE_AREA, NOME_STRUTTURA)    
);


--CREAZIONE REGISTRAZIONE SENSORE 


CREATE TABLE REGISTRAZIONE_SENSORE(
    SERIALE VARCHAR2(30),
    DATA_SECONDI DATE,
    NOME_PRODUTTORE VARCHAR2(30),
    MISURAZIONE NUMBER(32,16),

    --PK 
    CONSTRAINT PK_REGISTRAZIONE_SENSORE
        PRIMARY KEY (SERIALE, DATA_SECONDI, NOME_PRODUTTORE),
    
    --FK 
    CONSTRAINT FK_REGISTRAZIONE_SENSORE_A_SENSORE
        FOREIGN KEY (SERIALE, NOME_PRODUTTORE)
        REFERENCES SENSORE (SERIALE, NOME_PRODUTTORE)
);