--CREAZIONE TIPO_ANIMALE

CREATE TABLE TIPO_ANIMALE(
    NOME_TIPO_ANIMALE VARCHAR2(30),
    SPECIE VARCHAR2(30),
    VITA_MEDIA_ANNI NUMBER(5,2),
    MODALITA_RIPRODUZIONE VARCHAR2(15),
    GIORNI_GESTAZIONE NUMBER(3,0),
    UMIDITA_IDEALE NUMBER(3,0) --UMIDITA IN PERCENTUALE
        CONSTRAINT NN_TIPO_ANIMALE_UMIDITA NOT NULL,
    SPAZIO_MINIMO_MQ NUMBER(2,2)
        CONSTRAINT NN_TIPO_ANIMALE_SPAZIO_MINIMO NOT NULL,
    TEMPERATURA_IDEALE NUMBER(3,0) --TEMPERATURA IN KELVIN
        CONSTRAINT NN_TIPO_ANIMALE_TEMPERATURA NOT NULL,

    --PK
    CONSTRAINT PK_TIPO_ANIMALE PRIMARY KEY(NOME_TIPO_ANIMALE),

    --CHECK
    CONSTRAINT CK_TIPO_ANIMALE_VITA_MEDIA_ANNI
        CHECK (VITA_MEDIA_ANNI > 0),
    
    CONSTRAINT CK_TIPO_ANIMALE_MODALITA_RIPRODUZIONE
        CHECK (MODALITA_RIPRODUZIONE IN (
                'OVIPARA', --DEPONE UOVA
                'VIVIPARA', --PARTORISCE FIGLI VIVI
                'OVOVIVIPARA',  --UOVA SI SCHIUDONO ALL'INTERNO DEL CORPO MATERNO
                'PARTENOGENESI', --RIPRODUZIONE ASESSUATA
                'ASESSUATA' --RIPRODUZIONE SENZA FECONDAZIONE
            )),
    
    CONSTRAINT CK_TIPO_ANIMALE_GIORNI_GESTAZIONE
        CHECK (GIORNI_GESTAZIONE > 0),
    
    CONSTRAINT CK_TIPO_ANIMALE_UMIDITA
        CHECK (UMIDITA_IDEALE >= 0 AND UMIDITA_IDEALE <= 100),

    CONSTRAINT CK_TIPO_ANIMALE_SPAZIO_MINIMO
        CHECK (SPAZIO_MINIMO_MQ >0),
    
    CONSTRAINT CK_TIPO_ANIMALE_TEMPERATURA
        CHECK (TEMPERATURA_IDEALE > 230 AND TEMPERATURA_IDEALE < 320) --TRA -43°C E 47°C
);


--CREAZIONE ANIMALE


CREATE TABLE ANIMALE(
    ETICHETTA CHAR(10),
    DATA_USCITA DATE,
    ETICHETTA_GENITORE CHAR(10),
    SESSO CHAR(1),
    MESE_NASCITA NUMBER(2,0) 
        CONSTRAINT NN_ANIMALE_MESE_NASCITA NOT NULL,
    ANNO_NASCITA NUMBER(4,0) 
        CONSTRAINT NN_ANIMALE_ANNO_NASCITA NOT NULL,
    DATA_INGRESSO DATE 
        CONSTRAINT NN_ANIMALE_DATA_INGRESSO NOT NULL,
    NOME_TIPO_ANIMALE VARCHAR2(30) 
        CONSTRAINT NN_ANIMALE_FK_TIPO_ANIMALE NOT NULL,

    --PK
    CONSTRAINT PK_ANIMALE PRIMARY KEY (ETICHETTA),

    --FK
    CONSTRAINT FK_ANIMALE_TIPO_ANIMALE 
        FOREIGN KEY (NOME_TIPO_ANIMALE)
        REFERENCES TIPO_ANIMALE (NOME_TIPO_ANIMALE),

    CONSTRAINT FK_ANIMALE_GENITORE
        FOREIGN KEY (ETICHETTA_GENITORE)
        REFERENCES ANIMALE (ETICHETTA),
    
    --CHECK
    CONSTRAINT CK_ANIMALE_ETICHETTA
        CHECK (REGEXP_LIKE(ETICHETTA, '^[0-9]+$')), --ETICHETTA NUMERICA

    CONSTRAINT CK_ANIMALE_SESSO 
        CHECK (SESSO IN ('M', 'F', 'I')), --MASCHIO, FEMMINA, INDETERMINATO (BIOLOGICAMENTE IMPOSSIBILE)

    CONSTRAINT CK_ANIMALE_ANNO_NASCITA 
        CHECK (ANNO_NASCITA >= 1900),
    
    CONSTRAINT CK_ANIMALE_MESE_NASCITA
        CHECK (MESE_NASCITA >= 1 AND MESE_NASCITA <= 12),

    CONSTRAINT CK_ANIMALE_DATA_INGRESSO
        CHECK (DATA_INGRESSO >= DATE '2026-01-01'),
    
    CONSTRAINT CK_ANIMALE_DATA_USCITA
        CHECK (DATA_USCITA IS NULL OR DATA_USCITA >= DATA_INGRESSO)
);


--CREAZIONE STADIO_CRESCITA


CREATE TABLE STADIO_CRESCITA(
    NOME_STADIO_CRESCITA VARCHAR2(30), 
    NOME_TIPO_ANIMALE VARCHAR2(30),
    LIVELLO_BIOSICUREZZA_MINIMO VARCHAR2(15)
        CONSTRAINT NN_STADIO_CRESCITA_LIVELLO_BIOSICUREZZA_MINIMO NOT NULL,
    ETA_MINIMA_MESI NUMBER(4,0)
        CONSTRAINT NN_STADIO_CRESCITA_ETA_MINIMA NOT NULL,
    
    
    --PK
    CONSTRAINT PK_STADIO_CRESCITA PRIMARY KEY (NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE),

    --FK
    CONSTRAINT FK_STADIO_CRESCITA_TIPO_ANIMALE
        FOREIGN KEY (NOME_TIPO_ANIMALE)
        REFERENCES TIPO_ANIMALE (NOME_TIPO_ANIMALE),
    
    --CHECK
    CONSTRAINT CK_STADIO_CRESCITA_LIVELLO_BIOSICUREZZA_MINIMO
        CHECK (LIVELLO_BIOSICUREZZA_MINIMO IN (
                'BASSO',
                'MEDIO',
                'ALTO'
            )),

    CONSTRAINT CK_STADIO_CRESCITA_ETA_MINIMA
        CHECK (ETA_MINIMA_MESI >= 0)
);


--CREAZIONE DIETA_ANIMALE


CREATE TABLE DIETA_ANIMALE( --DIETA GIORNALIERA
    NOME_DIETA VARCHAR2(30),
    OBIETTIVO_DIETA VARCHAR2(30)
        CONSTRAINT NN_DIETA_ANIMALE_OBIETTIVO NOT NULL,

    --PK
    CONSTRAINT PK_DIETA_ANIMALE PRIMARY KEY (NOME_DIETA),

    --CHECK
    CONSTRAINT CK_DIETA_ANIMALE_OBIETTIVO
        CHECK (OBIETTIVO_DIETA IN (
                'MANTENIMENTO',
                'CRESCITA',
                'RIPRODUZIONE',
                'INGRASSO',
                'DIMAGRIMENTO'
        ))
);


--CREAZIONE TIPO VACCINO


CREATE TABLE VACCINO(
    NOME_VACCINO VARCHAR2(30), --PK
    NOME_TIPO_ANIMALE VARCHAR2(30), --PK/FK
    NOME_STADIO_CRESCITA VARCHAR2(30), --PK/FK
    NOME_VACCINO_PROPEDEUTICO VARCHAR2(30), --FK
    NOME_STADIO_CRESCITA_PROPEDEUTICO VARCHAR2(30), --FK
    NOME_TIPO_ANIMALE_PROPEDEUTICO VARCHAR2(30), --FK
    IS_VACCINO_OBBLIGATORIO NUMBER(1,0),
    ETA_MINIMA_MESI NUMBER(4,0)
        CONSTRAINT NN_TIPO_VACCINO_ETA_MINIMA NOT NULL,
    DOSE_ML NUMBER(4,2)
        CONSTRAINT NN_TIPO_VACCINO_DOSE NOT NULL,

    --PK
    CONSTRAINT PK_VACCINO 
        PRIMARY KEY (NOME_VACCINO, NOME_TIPO_ANIMALE, NOME_STADIO_CRESCITA),
    
    --FK
    CONSTRAINT FK_VACCINO_PROPEDEUTICO
        FOREIGN KEY (NOME_VACCINO_PROPEDEUTICO, NOME_TIPO_ANIMALE_PROPEDEUTICO, NOME_STADIO_CRESCITA_PROPEDEUTICO)
        REFERENCES VACCINO (NOME_VACCINO, NOME_TIPO_ANIMALE, NOME_STADIO_CRESCITA),

    CONSTRAINT FK_VACCINO_STADIO_CRESCITA
        FOREIGN KEY (NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE)
        REFERENCES STADIO_CRESCITA (NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE),

    --CHECK
    CONSTRAINT CK_VACCINO_IS_OBBLIGATORIO
        CHECK (IS_VACCINO_OBBLIGATORIO IN (1, 0)),

    CONSTRAINT CK_VACCINO_ETA_MINIMA 
        CHECK (ETA_MINIMA_MESI >= 0),
    
    CONSTRAINT CK_VACCINO_DOSE
        CHECK (DOSE_ML > 0)
);

--CREAZIONE VACCINAZIONE


CREATE TABLE VACCINAZIONE(
    ETICHETTA_ANIMALE CHAR(10),
    NOME_VACCINO VARCHAR2(30),
    NOME_TIPO_ANIMALE VARCHAR2(30),
    NOME_STADIO_CRESCITA VARCHAR2(30),
    DATA_VACCINAZIONE DATE,
    MATRICOLA_SOMMINISTRATORE VARCHAR2(30)
        CONSTRAINT NN_VACCINAZIONE_SOMMINISTRATORE NOT NULL,
    
    --PK
    CONSTRAINT PK_VACCINAZIONE
        PRIMARY KEY(
            ETICHETTA_ANIMALE, 
            NOME_VACCINO, 
            NOME_TIPO_ANIMALE, 
            NOME_STADIO_CRESCITA, 
            DATA_VACCINAZIONE
        ),

    --FK
    CONSTRAINT FK_VACCINAZIONE_ANIMALE
        FOREIGN KEY (ETICHETTA_ANIMALE)
        REFERENCES ANIMALE (ETICHETTA),
    
    CONSTRAINT FK_VACCINAZIONE_VACCINO
        FOREIGN KEY (NOME_VACCINO, NOME_TIPO_ANIMALE, NOME_STADIO_CRESCITA)
        REFERENCES VACCINO (NOME_VACCINO, NOME_TIPO_ANIMALE, NOME_STADIO_CRESCITA)
);


--CREAZIONE VISITA_VETERINARIA


CREATE TABLE VISITA_VETERINARIA(
    ETICHETTA_ANIMALE CHAR(10),
    DATA_VISITA DATE,
    MATRICOLA_VETERINARIO VARCHAR2(30)
        CONSTRAINT NN_VISITA_VETERINARIA_VETERINARIO NOT NULL,
    STATO_SALUTE VARCHAR2(10)
        CONSTRAINT NN_VISITA_VETERINARIA_STATO_SALUTE NOT NULL,
    TIPO_VISITA VARCHAR(20)
        CONSTRAINT NN_VISITA_VETERINARIA_TIPO_VISITA NOT NULL,
    
    --PK
    CONSTRAINT PK_VISITA_VETERINARIA
        PRIMARY KEY (ETICHETTA_ANIMALE, DATA_VISITA),

    --FK
    CONSTRAINT FK_VISITA_VETERINARIA_ANIMALE
        FOREIGN KEY (ETICHETTA_ANIMALE)
        REFERENCES ANIMALE (ETICHETTA),

    --CHECK
    CONSTRAINT CK_VISITA_VETERINARIA_STATO_SALUTE
        CHECK (STATO_SALUTE IN(
                'BUONO',
                'DISCRETO',
                'CRITICO'
        )),

    CONSTRAINT CK_VISITA_VETERINARIA_TIPO_VISITA
        CHECK (TIPO_VISITA IN(
                'ROUTINE',
                'EMERGENZA',
                'CONTROLLO_GESTAZIONE',
                'INGRESSO',
                'BIOSICUREZZA'
        ))
);


--CREAZIONE PRESCRIZIONE_ANIMALE


CREATE TABLE PRESCRIZIONE_ANIMALE(
    NOME_FARMACO VARCHAR2(30),
    ETICHETTA_ANIMALE CHAR(10),
    DATA_VISITA DATE,
    UNITA_MISURA VARCHAR(30)
        CONSTRAINT NN_PRESCRIZIONE_ANIMALE_UNITA_MISURA NOT NULL,
    DURATA_GIORNI NUMBER(4,0)
        CONSTRAINT NN_PRESCRIZIONE_ANIMALE_DURATA_GIORNI NOT NULL,
    QUANTITA_GIORNALIERA NUMBER(6,2)
        CONSTRAINT NN_PRESCRIZIONE_ANIMALE_QUANTITA_GIORNALIERA NOT NULL,
    
    --PK
    CONSTRAINT PK_PRESCRIZIONE_ANIMALE 
        PRIMARY KEY(NOME_FARMACO, ETICHETTA_ANIMALE, DATA_VISITA),

    --FK
    CONSTRAINT FK_PRESCRIZIONE_ANIMALE_VISITA_VETERINARIA
        FOREIGN KEY(ETICHETTA_ANIMALE, DATA_VISITA)
        REFERENCES VISITA_VETERINARIA (ETICHETTA_ANIMALE, DATA_VISITA),

    --CHECK
    CONSTRAINT CK_PRESCRIZIONE_DURATA_GIORNI
        CHECK(DURATA_GIORNI > 0),
    
    CONSTRAINT CK_PRESCRIZIONE_ANIMALE_QUANTITA_GIORNALIERA
        CHECK(QUANTITA_GIORNALIERA > 0)
);
