--CREAZIONE TABELLA ASSOCIATIVA STADIO_CRESCITA COLLEGAMENTO A DIETA


CREATE TABLE STADIO_CRESCITA_PREVEDE_DIETA (
    NOME_STADIO_CRESCITA VARCHAR2(30),
    NOME_TIPO_ANIMALE VARCHAR2(30),
    NOME_DIETA VARCHAR2(30),
    DATA_INIZIO DATE,
    DATA_FINE DATE,

    --PK
    CONSTRAINT PK_STADIO_CRESCITA_PREVEDE_DIETA 
        PRIMARY KEY (NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE, NOME_DIETA, DATA_INIZIO),
    
    --FK
    CONSTRAINT FK_SCPD_STADIO_CRESCITA
        FOREIGN KEY (NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE)
        REFERENCES STADIO_CRESCITA (NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE),

    CONSTRAINT FK_SCPD_DIETA_ANIMALE
        FOREIGN KEY (NOME_DIETA)
        REFERENCES DIETA_ANIMALE (NOME_DIETA),

    --CHECK
    CONSTRAINT CK_SCPD_DATA_INIZIO
        CHECK (DATA_INIZIO >= DATE '2026-01-01')
);


--CREAZIONE TABELLA ASSOCIATIVA DIETA_ANIMALE COLLEGAMENTO A PRODOTTO


CREATE TABLE DIETA_COMPRENDE_PRODOTTO (
    NOME_PRODOTTO VARCHAR2(30),
    NOME_DIETA VARCHAR2(30),
    QUANTITA_GRAMMI NUMBER(7,2)
        CONSTRAINT NN_DCP_QUANTITA_GRAMMI NOT NULL,

    --PK 
    CONSTRAINT PK_DIETA_COMPRENDE_PRODOTTO 
        PRIMARY KEY(NOME_PRODOTTO, NOME_DIETA),

    --FK
    CONSTRAINT FK_DCP_PRODOTTO
        FOREIGN KEY (NOME_PRODOTTO)
        REFERENCES TIPO_PRODOTTO (NOME_PRODOTTO),

    CONSTRAINT FK_DCP_DIETA_ANIMALE
        FOREIGN KEY (NOME_DIETA)
        REFERENCES DIETA_ANIMALE (NOME_DIETA),

    --CHECK 
    CONSTRAINT CK_DCP_QUANTITA_GRAMMI
        CHECK(QUANTITA_GRAMMI > 0)
);

