--CREAZIONE TABELLA ASSOCIATIVA STADIO_CRESCITA COLLEGAMENTO A DIETA


CREATE TABLE STADIO_CRESCITA_PREVEDE_DIETA(
    NOME_STADIO_CRESCITA VARCHAR2(30),
    NOME_TIPO_ANIMALE VARCHAR2(30),
    NOME_DIETA VARCHAR2(30),
    DATA_INIZIO DATE,
    DATA_FINE DATE,

    --PK
    CONSTRAINT PK_STADIO_CRESCITA_PREVEDE_DIETA 
        PRIMARY KEY (NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE, NOME_DIETA, DATA_INIZIO),
    
    --FK
    CONSTRAINT FK_SCPD_STADIO_CRESCITA
        FOREIGN KEY (NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE)
        REFERENCES STADIO_CRESCITA (NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE),

    CONSTRAINT FK_SCPD_DIETA_ANIMALE
        FOREIGN KEY (NOME_DIETA)
        REFERENCES DIETA_ANIMALE (NOME_DIETA),

    --CHECK
    CONSTRAINT CK_SCPD_DATA_INIZIO
        CHECK (DATA_INIZIO >= DATE '2026-01-01')
);


--CREAZIONE TABELLA ASSOCIATIVA DIETA_ANIMALE COLLEGAMENTO A PRODOTTO


CREATE TABLE DIETA_COMPRENDE_PRODOTTO(
    NOME_PRODOTTO VARCHAR2(30),
    NOME_DIETA VARCHAR2(30),
    QUANTITA_GRAMMI NUMBER(7,2)
        CONSTRAINT NN_DCP_QUANTITA_GRAMMI NOT NULL,

    --PK 
    CONSTRAINT PK_DIETA_COMPRENDE_PRODOTTO 
        PRIMARY KEY(NOME_PRODOTTO, NOME_DIETA),

    --FK
    CONSTRAINT FK_DCP_PRODOTTO
        FOREIGN KEY (NOME_PRODOTTO)
        REFERENCES TIPO_PRODOTTO (NOME_PRODOTTO),

    CONSTRAINT FK_DCP_DIETA_ANIMALE
        FOREIGN KEY (NOME_DIETA)
        REFERENCES DIETA_ANIMALE (NOME_DIETA),

    --CHECK 
    CONSTRAINT CK_DCP_QUANTITA_GRAMMI
        CHECK(QUANTITA_GRAMMI > 0)
);


--CREAZIONE TABELLA ASSOCIATIVA PRODOTTO COLLEGAMENTO A SOSTANZA

CREATE TABLE PRODOTTO_CONTIENE_SOSTANZA(
    NOME_PRODOTTO VARCHAR2(30),
    NOME_SOSTANZA VARCHAR2(30),
    LIVELLO_PRESENZA VARCHAR2(15)
        CONSTRAINT NN_PCS_LIVELLO_PRESENZA NOT NULL,
    

    --PK 
    CONSTRAINT PK_PRODOTTO_CONTIENE_SOSTANZA 
        PRIMARY KEY(NOME_PRODOTTO, NOME_SOSTANZA),

    --FK
    CONSTRAINT FK_PCS_PRODOTTO
        FOREIGN KEY (NOME_PRODOTTO)
        REFERENCES TIPO_PRODOTTO (NOME_PRODOTTO),

    CONSTRAINT FK_PCS_SOSTANZA
        FOREIGN KEY (NOME_SOSTANZA)
        REFERENCES SOSTANZA (NOME_SOSTANZA),

    --CHECK 
    CONSTRAINT CK_PCS_LIVELLO_PRESENZA
        CHECK(LIVELLO_PRESENZA IN(
                'TRACCIA',
                'BASSO',
                'MEDIO',
                'ALTO'
        ))
);


--CREAZIONE TABELLA ASSOCIATIVA STADIO_CRESCITA COLLEGAMENTO A SOSTANZA, PER INTOLLERANZE


CREATE TABLE STADIO_CRESCITA_INTOLLERANTE_SOSTANZA(
    NOME_STADIO_CRESCITA VARCHAR2(30),
    NOME_TIPO_ANIMALE VARCHAR2(30),
    NOME_SOSTANZA VARCHAR2(30),

    --PK
    CONSTRAINT PK_SCIS 
        PRIMARY KEY(NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE, NOME_SOSTANZA),

    --FK
    CONSTRAINT FK_SCIS_STADIO_CRESCITA
        FOREIGN KEY (NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE)
        REFERENCES STADIO_CRESCITA (NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE),

    CONSTRAINT FK_SCIS_SOSTANZA
        FOREIGN KEY (NOME_SOSTANZA)
        REFERENCES SOSTANZA (NOME_SOSTANZA)
);


--CREAZIONE TABELLA ASSOCIATIVA ANIMALE COLLEGAMENTO A SOSTANZA, PER EVENTUALI BISOGNI INDIVIDUALI


CREATE TABLE ANIMALE_ALLERGICO_SOSTANZA(
    ETICHETTA_ANIMALE CHAR(10),
    NOME_SOSTANZA VARCHAR2(30),
    DATA_ATTESTAZIONE DATE,

    --PK
    CONSTRAINT PK_AAS
        PRIMARY KEY(ETICHETTA_ANIMALE, NOME_SOSTANZA),
    
    --FK
    CONSTRAINT FK_AAS_ANIMALE
        FOREIGN KEY (ETICHETTA_ANIMALE)
        REFERENCES ANIMALE (ETICHETTA),

    CONSTRAINT FK_AAS_SOSTANZA
        FOREIGN KEY (NOME_SOSTANZA)
        REFERENCES SOSTANZA (NOME_SOSTANZA)
);


--CREAZIONE TABELLA ASSOCIATIVA ANIMALE COLLEGAMENTO A DIETA, PER DIETE PERSONALIZZATE


CREATE TABLE ANIMALE_PREVEDE_DIETA_SPECIALE(
    ETICHETTA_ANIMALE CHAR(10),
    NOME_DIETA VARCHAR2(30),
    DATA_INIZIO DATE,
    DATA_FINE DATE,

    --PK
    CONSTRAINT PK_APDS
        PRIMARY KEY(ETICHETTA_ANIMALE, NOME_DIETA, DATA_INIZIO),

    --FK
    CONSTRAINT FK_APDS_ANIMALE
        FOREIGN KEY (ETICHETTA_ANIMALE)
        REFERENCES ANIMALE (ETICHETTA),

    CONSTRAINT FK_APDS_DIETA_ANIMALE
        FOREIGN KEY (NOME_DIETA)
        REFERENCES DIETA_ANIMALE (NOME_DIETA),
    
    --CHECK
    CONSTRAINT CK_APDS_DATA_INIZIO
        CHECK (DATA_INIZIO >= DATE '2026-01-01')
);


--CREAZIONE TABELLA ASSOCIATIVA STADIO_CRESCITA COLLEGAMENTO A TIPO_PRODOTTO


CREATE TABLE PRODOTTO_DA_STADIO_CRESCITA(
    NOME_PRODOTTO VARCHAR2(30),
    NOME_STADIO_CRESCITA VARCHAR2(30), 
    NOME_TIPO_ANIMALE VARCHAR2(30),

    --PK
    CONSTRAINT PK_PDSC
        PRIMARY KEY (NOME_PRODOTTO, NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE),

    --FK
    CONSTRAINT FK_PDSC_TIPO_PRODOTTO
        FOREIGN KEY (NOME_PRODOTTO)
        REFERENCES TIPO_PRODOTTO (NOME_PRODOTTO),

    CONSTRAINT FK_PDSC_STADIO_CRESCITA
        FOREIGN KEY (NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE)
        REFERENCES STADIO_CRESCITA (NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE)
);