CREATE TABLE CICLO_COLT_UTILIZZA_SEMI_MISSIONE(
    DATA_INIZIO DATE,
    CODICE_CELLA_IDR CHAR(4),
    NOME_STRUTTURA VARCHAR(60),
    NOME_SEMI VARCHAR(60),
    DATA_ARRIVO_SEMI DATE,
    QUANTITA NUMBER(6,2)
        CONSTRAINT NN_CICLO_COLT_UTILIZZA_SEMI_MISSIONE_QUANTITA NOT NULL,

    --PK
    CONSTRAINT PK_CICLO_COLT_UTILIZZA_SEMI_MISSIONE
        PRIMARY KEY (
            DATA_INIZIO,
            CODICE_CELLA_IDR, 
            NOME_STRUTTURA, 
            NOME_SEMI, 
            DATA_ARRIVO_SEMI
        ),

    --FK
    CONSTRAINT FK_CICLO_COLT_UTILIZZA_SEMI_MISSIONE_CICLO
        FOREIGN KEY (DATA_INIZIO, CODICE_CELLA_IDR, NOME_STRUTTURA)
        REFERENCES CICLO_COLTIVAZIONE(DATA_INIZIO, CODICE_CELLA_IDR, NOME_STRUTTURA),

    CONSTRAINT FK_CICLO_COLT_UTILIZZA_SEMI_MISSIONE_TO_SEMI
        FOREIGN KEY (NOME_SEMI, DATA_ARRIVO_SEMI)
        REFERENCES SEMI_MISSIONE (NOME_SEMI, DATA_ARRIVO_SEMI),

    --CHECK
    CONSTRAINT CK_CICLO_COLT_UTILIZZA_SEMI_MISSIONE_QUANTITA
        CHECK(QUANTITA > 0)
);