CREATE TABLE CICLO_COLT_UTILIZZA_PRODUZIONE_AGRICOLA(
    DATA_INIZIO DATE,
    CODICE_CELLA_IDR CHAR(4),
    NOME_STRUTTURA VARCHAR(60),
    --ATTRIBUTI PK PRODUZIONE AGRICOLA
    DATA_PRODUZIONE_AGRICOLA DATE,
    DATA_INIZIO_CICLO_COLTIVAZIONE DATE,
    CODICE_CELLA_IDR_PROD_AGR CHAR(4),
    NOME_STRUTTURA_PROD_AGR VARCHAR(60),
    NOME_PRODOTTO VARCHAR(60),
    QUANTITA NUMBER(6,2)
        CONSTRAINT NN_CICLO_COLT_UTILIZZA_PRODUZIONE_AGRICOLA_QUANTITA NOT NULL,
    

    --PK
    CONSTRAINT PK_CICLO_COLT_UTILIZZA_PRODUZIONE_AGRICOLA
        PRIMARY KEY (
            DATA_INIZIO,
            CODICE_CELLA_IDR, 
            NOME_STRUTTURA, 
            DATA_PRODUZIONE_AGRICOLA,
            DATA_INIZIO_CICLO_COLTIVAZIONE,
            CODICE_CELLA_IDR_PROD_AGR,
            NOME_STRUTTURA_PROD_AGR,
            NOME_PRODOTTO
        ),

    --FK
    CONSTRAINT FK_CICLO_COLT_UTILIZZA_PRODUZIONE_AGRICOLA_CICLO
        FOREIGN KEY (DATA_INIZIO, CODICE_CELLA_IDR, NOME_STRUTTURA)
        REFERENCES CICLO_COLTIVAZIONE(DATA_INIZIO, CODICE_CELLA_IDR, NOME_STRUTTURA),

    CONSTRAINT FK_CICLO_COLT_UTILIZZA_PRODUZIONE_AGRICOLA_TO_PROD_AGR
        FOREIGN KEY (
            DATA_PRODUZIONE_AGRICOLA,
            DATA_INIZIO_CICLO_COLTIVAZIONE,
            CODICE_CELLA_IDR_PROD_AGR,
            NOME_STRUTTURA_PROD_AGR,
            NOME_PRODOTTO
        )
        
        REFERENCES PRODUZIONE_AGRICOLA (
            DATA_PRODUZIONE_AGRICOLA,
            DATA_INIZIO_CICLO_COLTIVAZIONE,
            CODICE_CELLA_IDR,
            NOME_STRUTTURA,
            NOME_PRODOTTO
        ),

    --CHECK
    CONSTRAINT CK_CICLO_COLT_UTILIZZA_PRODUZIONE_AGRICOLA_QUANTITA
        CHECK(QUANTITA > 0)
);