CREATE TABLE BLOCCO_ANIMALE_CONTIENE_SENSORE(
    SERIALE VARCHAR(60),
    NOME_PRODUTTORE VARCHAR(60),
    NOME_MODELLO VARCHAR(60),
    NUMERO_BLOCCO CHAR(4),
    NOME_STRUTTURA VARCHAR(60),
    DATA_SMONTAGGIO DATE,
    DATA_MONTAGGIO DATE
        CONSTRAINT NN_BACS_DATA_MONTAGGIO NOT NULL,

    --PK
    CONSTRAINT PK_BLOCCO_ANIMALE_CONTIENE_SENSORE
        PRIMARY KEY (SERIALE, NOME_PRODUTTORE, NOME_MODELLO, NUMERO_BLOCCO, NOME_STRUTTURA, DATA_MONTAGGIO),

    --FK
    CONSTRAINT FK_BACS_SENSORE
        FOREIGN KEY (SERIALE, NOME_PRODUTTORE, NOME_MODELLO)
        REFERENCES SENSORE (SERIALE, NOME_PRODUTTORE, NOME_MODELLO),

    CONSTRAINT FK_BACS_BLOCCO_ANIMALE
        FOREIGN KEY (NUMERO_BLOCCO, NOME_STRUTTURA)
        REFERENCES BLOCCO_ANIMALE (NUMERO_BLOCCO, NOME_STRUTTURA)
);
