CREATE TABLE TIPO_COLTURA_USA_SEMI_DI_TIPO(
    NOME_SEMI VARCHAR(60), 
    NOME_TIPO_COLTURA VARCHAR(60),

    --PK
    CONSTRAINT PK_TIPO_COLTURA_USA_SEMI_DI_TIPO
        PRIMARY KEY (NOME_SEMI,NOME_TIPO_COLTURA),
    
    --FK
    CONSTRAINT FK_TIPO_COLTURA_USA_SEMI_DI_TIPO_TO_PRODOTTO
        FOREIGN KEY (NOME_SEMI)
        REFERENCES TIPO_PRODOTTO (NOME_PRODOTTO),

    CONSTRAINT FK_TIPO_COLTURA_USA_SEMI_DI_TIPO_COLTURA
        FOREIGN KEY (NOME_TIPO_COLTURA)
        REFERENCES TIPO_COLTURA (NOME_TIPO_COLTURA)
);