CREATE TABLE CELLA_IDR_CONTIENE_SENSORE(
    SERIALE VARCHAR(60),
    NOME_PRODUTTORE VARCHAR(60),
    NOME_MODELLO VARCHAR(60),
    CODICE_CELLA_IDR CHAR(4),
    NOME_STRUTTURA VARCHAR(60),
    DATA_SMONTAGGIO DATE,
    DATA_MONTAGGIO DATE
        CONSTRAINT NN_CICS_DATA_MONTAGGIO NOT NULL,

    --PK
    CONSTRAINT PK_CELLA_IDR_CONTIENE_SENSORE
        PRIMARY KEY (SERIALE, NOME_PRODUTTORE, NOME_MODELLO, CODICE_CELLA_IDR, NOME_STRUTTURA, DATA_MONTAGGIO),

    --FK
    CONSTRAINT FK_CICS_SENSORE
        FOREIGN KEY (SERIALE, NOME_PRODUTTORE, NOME_MODELLO)
        REFERENCES SENSORE (SERIALE, NOME_PRODUTTORE, NOME_MODELLO),

    CONSTRAINT FK_CICS_CELLA_IDROPONICA
        FOREIGN KEY (CODICE_CELLA_IDR, NOME_STRUTTURA)
        REFERENCES CELLA_IDROPONICA (CODICE_CELLA_IDR, NOME_STRUTTURA)
);
