CREATE TABLE DIETA_COMPRENDE_PRODOTTO(
    NOME_PRODOTTO VARCHAR(60),
    NOME_DIETA VARCHAR(60),
    QUANTITA NUMBER(7,2)
        CONSTRAINT NN_DCP_QUANTITA NOT NULL,

    --PK 
    CONSTRAINT PK_DIETA_COMPRENDE_PRODOTTO 
        PRIMARY KEY(NOME_PRODOTTO, NOME_DIETA),

    --FK
    CONSTRAINT FK_DCP_PRODOTTO
        FOREIGN KEY (NOME_PRODOTTO)
        REFERENCES TIPO_PRODOTTO (NOME_PRODOTTO),

    CONSTRAINT FK_DCP_DIETA_ANIMALE
        FOREIGN KEY (NOME_DIETA)
        REFERENCES DIETA_ANIMALE (NOME_DIETA),

    --CHECK 
    CONSTRAINT CK_DCP_QUANTITA
        CHECK(QUANTITA > 0)
);