CREATE TABLE PRODOTTO_CONTIENE_SOSTANZA(
    NOME_PRODOTTO VARCHAR(60),
    NOME_SOSTANZA VARCHAR(60),
    LIVELLO_PRESENZA VARCHAR(15)
        CONSTRAINT NN_PCS_LIVELLO_PRESENZA NOT NULL,
    

    --PK 
    CONSTRAINT PK_PRODOTTO_CONTIENE_SOSTANZA 
        PRIMARY KEY(NOME_PRODOTTO, NOME_SOSTANZA),

    --FK
    CONSTRAINT FK_PCS_PRODOTTO
        FOREIGN KEY (NOME_PRODOTTO)
        REFERENCES TIPO_PRODOTTO (NOME_PRODOTTO),

    CONSTRAINT FK_PCS_SOSTANZA
        FOREIGN KEY (NOME_SOSTANZA)
        REFERENCES SOSTANZA (NOME_SOSTANZA),

    --CHECK 
    CONSTRAINT CK_PCS_LIVELLO_PRESENZA
        CHECK(LIVELLO_PRESENZA IN(
                'TRACCIA',
                'BASSO',
                'MEDIO',
                'ALTO'
        ))
);