CREATE TABLE STADIO_CRESCITA_INTOLLERANTE_SOSTANZA(
    NOME_STADIO_CRESCITA VARCHAR(60),
    NOME_TIPO_ANIMALE VARCHAR(60),
    NOME_SOSTANZA VARCHAR(60),

    --PK
    CONSTRAINT PK_SCIS 
        PRIMARY KEY(NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE, NOME_SOSTANZA),

    --FK
    CONSTRAINT FK_SCIS_STADIO_CRESCITA
        FOREIGN KEY (NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE)
        REFERENCES STADIO_CRESCITA (NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE),

    CONSTRAINT FK_SCIS_SOSTANZA
        FOREIGN KEY (NOME_SOSTANZA)
        REFERENCES SOSTANZA (NOME_SOSTANZA)
);