CREATE TABLE BLOCCO_AMMETTE_TIPO_ANIMALE(
    NOME_TIPO_ANIMALE VARCHAR(60),
    NUMERO_BLOCCO CHAR(4), --0000
    NOME_STRUTTURA VARCHAR(60),

    --PK
    CONSTRAINT PK_BLOCCO_AMMETTE_TIPO_ANIMALE
        PRIMARY KEY(NOME_TIPO_ANIMALE, NUMERO_BLOCCO, NOME_STRUTTURA),
    
    --FK
    CONSTRAINT FK_BLOCCO_AMMETTE_TIPO_ANIMALE_BLOCCO
        FOREIGN KEY(NOME_STRUTTURA, NUMERO_BLOCCO)
        REFERENCES BLOCCO_ANIMALE (NOME_STRUTTURA, NUMERO_BLOCCO),

    CONSTRAINT FK_BLOCCO_AMMETTE_TIPO_ANIMALE_TIPO_ANIMALE
        FOREIGN KEY(NOME_TIPO_ANIMALE)
        REFERENCES TIPO_ANIMALE (NOME_TIPO_ANIMALE)
);