CREATE TABLE PRODOTTO_DA_STADIO_CRESCITA(
    NOME_PRODOTTO VARCHAR(60),
    NOME_STADIO_CRESCITA VARCHAR(60), 
    NOME_TIPO_ANIMALE VARCHAR(60),
    QUANTITA_STIMATA_GIORNALIERA NUMBER(7,3),

    --PK
    CONSTRAINT PK_PDSC
        PRIMARY KEY (NOME_PRODOTTO, NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE),

    --FK
    CONSTRAINT FK_PDSC_TIPO_PRODOTTO
        FOREIGN KEY (NOME_PRODOTTO)
        REFERENCES TIPO_PRODOTTO (NOME_PRODOTTO),

    CONSTRAINT FK_PDSC_STADIO_CRESCITA
        FOREIGN KEY (NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE)
        REFERENCES STADIO_CRESCITA (NOME_STADIO_CRESCITA, NOME_TIPO_ANIMALE),

    --CHECK
    CONSTRAINT CK_PRODOTTO_DA_STADIO_CRESCITA_QUANTITA_STIMATA_GIORNALIERA
        CHECK(QUANTITA_STIMATA_GIORNALIERA > 0)

);