CREATE TABLE CELLA_IDR_RISPETTA_MOD_COLT(
    CODICE_CELLA_IDR CHAR(4),
    NOME_STRUTTURA VARCHAR(60),
    NOME_MOD_COLTIVAZIONE VARCHAR(60),

    --PK
    CONSTRAINT PK_CELLA_IDR_RISPETTA_MOD_COLT
        PRIMARY KEY (CODICE_CELLA_IDR, NOME_STRUTTURA, NOME_MOD_COLTIVAZIONE),

    --FK
    CONSTRAINT FK_CELLA_IDR_RISPETTA_MOD_COLT_CELLA_IDROPONICA
        FOREIGN KEY (CODICE_CELLA_IDR, NOME_STRUTTURA)
        REFERENCES CELLA_IDROPONICA (CODICE_CELLA_IDR, NOME_STRUTTURA),
    
    CONSTRAINT FK_CELLA_IDR_RISPETTA_MOD_COLT_MOD_COLTIVAZIONE
        FOREIGN KEY (NOME_MOD_COLTIVAZIONE)
        REFERENCES MODALITA_COLTIVAZIONE (NOME_MODALITA_COLTIVAZIONE)
);