CREATE TABLE TIPO_COLT_ACCETTA_MOD_COLT(
    NOME_TIPO_COLTURA VARCHAR(60),
    NOME_MODALITA_COLTIVAZIONE VARCHAR(60),

    --PK
    CONSTRAINT PK_TIPO_COLT_ACCETTA_MOD_COLT
        PRIMARY KEY (NOME_TIPO_COLTURA, NOME_MODALITA_COLTIVAZIONE),

    --FK
    CONSTRAINT FK_TIPO_COLT_ACCETTA_MOD_COLT_TIPO_COLTURA
        FOREIGN KEY (NOME_TIPO_COLTURA)
        REFERENCES TIPO_COLTURA (NOME_TIPO_COLTURA),
    
    CONSTRAINT FK_TIPO_COLT_ACCETTA_MOD_COLT_MODALITA_COLTIVAZIONE
        FOREIGN KEY (NOME_MODALITA_COLTIVAZIONE)
        REFERENCES MODALITA_COLTIVAZIONE (NOME_MODALITA_COLTIVAZIONE)
);