--NOME_TIPO_COLTURA, NOME_SEMI, CATEGORIA_COLTURA, DURATA_CICLO_COLTURA_GIORNI
INSERT INTO TIPO_COLTURA VALUES ('Grano duro', 'Semi di grano duro', 'CEREALI', 180);
INSERT INTO TIPO_COLTURA VALUES ('Mais', 'Semi di mais', 'CEREALI', 120);
INSERT INTO TIPO_COLTURA VALUES ('Pomodoro', 'Semi di pomodoro', 'ORTAGGI', 90);
INSERT INTO TIPO_COLTURA VALUES ('Lattuga', 'Semi di lattuga', 'ORTAGGI', 45);
INSERT INTO TIPO_COLTURA VALUES ('Soia', 'Semi di soia', 'OLEAGINOSE', 120);

COMMIT;
