--NOME_TIPO_COLTURA, CATEGORIA_COLTURA, DURATA_CICLO_COLTURA_GIORNI
INSERT INTO TIPO_COLTURA VALUES ('Grano duro', 'CERALI', 180);
INSERT INTO TIPO_COLTURA VALUES ('Mais', 'CERALI', 120);

INSERT INTO TIPO_COLTURA VALUES ('Patata', 'ORTAGGI', 100);
INSERT INTO TIPO_COLTURA VALUES ('Pomodoro', 'ORTAGGI', 90);
INSERT INTO TIPO_COLTURA VALUES ('Lattuga', 'ORTAGGI', 45);
INSERT INTO TIPO_COLTURA VALUES ('Spinaci', 'ORTAGGI', 40);
INSERT INTO TIPO_COLTURA VALUES ('Carota', 'ORTAGGI', 80);
INSERT INTO TIPO_COLTURA VALUES ('Zucchina', 'ORTAGGI', 55);
INSERT INTO TIPO_COLTURA VALUES ('Cetriolo', 'ORTAGGI', 60);
INSERT INTO TIPO_COLTURA VALUES ('Melanzana', 'ORTAGGI', 90);
INSERT INTO TIPO_COLTURA VALUES ('Peperone', 'ORTAGGI', 90);

INSERT INTO TIPO_COLTURA VALUES ('Fagiolo', 'LEGUMI', 90);
INSERT INTO TIPO_COLTURA VALUES ('Ceci', 'LEGUMI', 110);
INSERT INTO TIPO_COLTURA VALUES ('Lenticchie', 'LEGUMI', 100);
INSERT INTO TIPO_COLTURA VALUES ('Piselli', 'LEGUMI', 80);

INSERT INTO TIPO_COLTURA VALUES ('Soia', 'OLEAGINOSE', 120);

INSERT INTO TIPO_COLTURA VALUES ('Fragola', 'FRUTTA', 90);

COMMIT;
