#DATA_PRODUZIONE_AGRICOLA, DATA_INIZIO_CICLO_COLTIVAZIONE, CODICE_CELLA_IDR, NOME_STRUTTURA, NOME_PRODOTTO, QUANTITA

from python.DB.action.insert.base import insert_base

def insert_agri_production(DATA_PRODUZIONE_AGRICOLA,DATA_INIZIO_CICLO_COLTIVAZIONE,CODICE_CELLA_IDR,NOME_STRUTTURA,NOME_PRODOTTO,QUANTITA):
    if hasattr(DATA_PRODUZIONE_AGRICOLA,"strftime"):
        DATA_PRODUZIONE_AGRICOLA=DATA_PRODUZIONE_AGRICOLA.strftime("%Y-%m-%d")

    if hasattr(DATA_INIZIO_CICLO_COLTIVAZIONE,"strftime"):
        DATA_INIZIO_CICLO_COLTIVAZIONE=DATA_INIZIO_CICLO_COLTIVAZIONE.strftime("%Y-%m-%d")

    insert_base(
        "INSERT INTO PRODUZIONE_AGRICOLA VALUES ("
        f"DATE '{DATA_PRODUZIONE_AGRICOLA}',"
        f"DATE '{DATA_INIZIO_CICLO_COLTIVAZIONE}',"
        f"'{CODICE_CELLA_IDR}',"
        f"'{NOME_STRUTTURA}',"
        f"'{NOME_PRODOTTO}',"
        f"{QUANTITA}"
        ")"
    )